Repository sparkdesignsystem/spark-design-system, pull requests merged in 2018-10, with the labels that each got.

#588 Release fixing
  .travis.yml
  gulpfile.js
  package-lock.json
  package.json
  packages/spark-core/.babelrc
  packages/spark-core/.gitignore
  packages/spark-core/.npmignore
  packages/spark-core/package-lock.json
  packages/spark-core/package.json
  packages/spark-core/webpack.config.js
  packages/spark-extras/components/highlight-board/.gitignore
  packages/spark-extras/components/highlight-board/.npmignore
  packages/spark-extras/components/highlight-board/package-lock.json
  packages/spark-extras/components/highlight-board/package.json
  packages/spark-extras/components/highlight-board/tests/_setup.js
  packages/spark-extras/components/highlight-board/tests/highligh-board.tests.js
  packages/spark-extras/components/highlight-board/webpack.config.js
  src/angular/package-lock.json
  src/angular/package.json
  src/angular/projects/spark-core-angular/package.json
  src/angular/projects/spark-core-angular/src/lib/components/sprk-accordion/sprk-accordion.component.spec.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-alert/sprk-alert.component.spec.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-alert/sprk-alert.component.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-promo/sprk-promo.component.spec.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.component.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-unordered-list/sprk-unordered-list.component.spec.ts
  src/angular/projects/spark-core-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.spec.ts
  src/angular/projects/spark-core-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.ts
  src/angular/projects/spark-core-angular/src/lib/directives/inputs/sprk-helper-text/sprk-helpler-text.directive.spec.ts
  src/angular/projects/spark-core-angular/src/lib/directives/inputs/sprk-input/sprk-input.directive.ts
  src/angular/projects/spark-core-angular/src/lib/directives/inputs/sprk-selection-input/sprk-selection-input.directive.ts
  src/angular/projects/spark-core-angular/src/lib/directives/sprk-stack-item/sprk-stack-item.directive.spec.ts
  src/angular/projects/spark-core-angular/src/lib/directives/sprk-table-empty-heading/sprk-table-empty-heading.directive.spec.ts
  src/angular/projects/spark-core-angular/src/lib/directives/sprk-table-grouped-column/sprk-table-grouped-column.directive.spec.ts
  src/angular/projects/spark-core-angular/src/lib/directives/sprk-table-head/sprk-table-head.directive.spec.ts
  src/angular/projects/spark-core-angular/src/lib/directives/sprk-table-row-heading/sprk-table-row-heading.directive.spec.ts
  src/angular/projects/spark-extras-angular-award/package-lock.json
  src/angular/projects/spark-extras-angular-award/package.json
  src/angular/projects/spark-extras-angular-card/package-lock.json
  src/angular/projects/spark-extras-angular-card/package.json
  src/angular/projects/spark-extras-angular-dictionary/package-lock.json
  src/angular/projects/spark-extras-angular-dictionary/package.json
  src/angular/projects/spark-extras-angular-highlight-board/package-lock.json
  src/angular/projects/spark-extras-angular-highlight-board/package.json
  src/angular/src/app/spark-docs/button-docs/button-docs.component.ts
  src/angular/src/polyfills.ts
  src/angular/tsconfig.json
  src/assets/drizzle/scripts/code-example-switch.js
  src/assets/drizzle/scripts/filter.js
  src/assets/drizzle/scripts/form-state-changer.js
  src/assets/drizzle/scripts/load-switch-setting.js
  src/assets/drizzle/scripts/modals.js
  src/assets/drizzle/scripts/pagination/default.js
  src/assets/drizzle/scripts/pagination/long.js
  src/assets/toolkit/scripts/toolkit.js
Labels: status: PR review

#589 Table stripes
  gulpfile.js
  packages/spark-core/settings/_settings.scss
  src/assets/drizzle/scripts/handlebars-helpers/concat.js
  src/assets/drizzle/scripts/handlebars-helpers/patternIdGen.js
  src/patterns/components/tables/collection.yaml
  src/patterns/components/tables/properties/collection.hbs
  src/templates/collection.hbs
  tests/patternIdGen.tests.js
Labels: fall 🎃

#586 add package.json updates
  package-lock.json
  package.json
  src/angular/package-lock.json
  src/angular/package.json
  src/angular/projects/spark-core-angular/package.json
Labels: status: PR review

#599 attempt 1
  .travis.yml
Labels: status: DO NOT MERGE

#647 Add new alert shadow and generated SVG sprite
  packages/spark-core/settings/_settings.scss
  packages/spark-core/spark-core-icons.svg
Labels: status: PR review

#644 Config date picker
  package-lock.json
  packages/spark-core/base/datePicker.js
  packages/spark-core/package-lock.json
  packages/spark-core/package.json
  packages/spark-core/spark-core.js
  packages/spark-core/tests/datePicker.tests.js
  src/angular/package-lock.json
  src/angular/package.json
  src/angular/projects/spark-core-angular/src/lib/directives/inputs/sprk-datepicker/sprk-datepicker.directive.ts
  src/angular/src/app/spark-docs/input-docs/input-docs.component.ts
  src/assets/toolkit/scripts/toolkit.js
  src/pages/gettingstarted/developers.hbs
  src/patterns/components/buttons/angular/info/base.hbs
  src/patterns/components/inputs/angular/info/datepicker.hbs
Labels: status: PR review

#659 travis cleanup
  .travis.yml
Labels: status: PR review

#660 adding an npm script that builds everything
  package.json
  packages/spark-core/package-lock.json
  packages/spark-extras/package-lock.json
Labels: status: PR review

#670 Enhance button styles
  packages/spark-core/components/_buttons.scss
  packages/spark-core/package-lock.json
  packages/spark-core/settings/_settings.scss
  src/patterns/components/buttons/angular/code/removal.hbs
  src/patterns/components/buttons/angular/info/removal.hbs
  src/patterns/components/buttons/removal.hbs
Labels: status: PR review

#680 add slidetoggle promise stub to tests
  packages/spark-core/tests/toggle.tests.js
Labels: status: PR review

#690 Build time down to ~ 8mins
  .travis.yml
  package.json
Labels: status: PR review

#656 type load
  config.js
  packages/spark-core/_spark-core.scss
  packages/spark-core/base/_typography.scss
  packages/spark-core/base/typography.js
  packages/spark-core/package-lock.json
  packages/spark-core/package.json
  packages/spark-core/settings/_settings.scss
  packages/spark-core/spark-core-prerender.js
  packages/spark-core/spark-core.js
  packages/spark-core/tests/toggle.tests.js
  packages/spark-core/tests/typography.tests.js
  packages/spark-core/webpack.config.js
  src/angular/src/app/app.component.scss
  src/assets/drizzle/styles/utility/_toolkit-overrides.scss
  src/assets/toolkit/scripts/toolkit-prerender.js
  src/assets/toolkit/scripts/toolkit.js
  src/assets/toolkit/styles/toolkit.scss
  src/pages/gettingstarted/developers.hbs
  src/patterns/fundamentals/typography/body-four.hbs
  src/patterns/fundamentals/typography/body-one.hbs
  src/patterns/fundamentals/typography/body-three.hbs
  src/patterns/fundamentals/typography/body-two.hbs
  src/patterns/fundamentals/typography/collection.yaml
  src/patterns/fundamentals/typography/display-eight.hbs
  src/patterns/fundamentals/typography/display-five.hbs
  src/patterns/fundamentals/typography/display-four.hbs
  src/patterns/fundamentals/typography/display-one.hbs
  src/patterns/fundamentals/typography/display-seven.hbs
  src/patterns/fundamentals/typography/display-six.hbs
  src/patterns/fundamentals/typography/display-three.hbs
  src/patterns/fundamentals/typography/display-two.hbs
  src/patterns/fundamentals/typography/fallback.hbs
  src/patterns/fundamentals/typography/line-height-collision.hbs
  src/patterns/fundamentals/typography/outside-sizing.hbs
  src/patterns/fundamentals/typography/setting-up.hbs
  src/patterns/fundamentals/typography/typekit.hbs
  src/templates/blank.hbs
Labels: status: PR review

#695 Refactor input HTML and CSS into BEM implementation
  packages/spark-core/base/_inputs.scss
  packages/spark-core/base/inputs/_labels.scss
  packages/spark-core/base/inputs/_text-input.scss
  src/angular/projects/spark-extras-angular-dictionary/src/lib/spark-extras-angular-dictionary.component.ts
  src/angular/src/app/spark-docs/input-docs/input-docs.component.ts
  src/pages/tests/dictionary.hbs
  src/patterns/components/dictionary/base.hbs
  src/patterns/components/dictionary/striped.hbs
  src/patterns/components/inputs/angular/code/datepicker-disabled.hbs
  src/patterns/components/inputs/angular/code/datepicker-error.hbs
  src/patterns/components/inputs/angular/code/datepicker.hbs
  src/patterns/components/inputs/angular/code/monetary-disabled.hbs
  src/patterns/components/inputs/angular/code/monetary-error.hbs
  src/patterns/components/inputs/angular/code/monetary.hbs
  src/patterns/components/inputs/datepicker.hbs
  src/patterns/components/inputs/monetary.hbs
Labels: fall 🎃, scope: core, status: DO NOT MERGE, type: enhancement

#699 Fall Footer
  packages/spark-core/objects/_stack.scss
  packages/spark-core/utilities/_utilities.scss
  src/angular/projects/spark-core-angular/src/lib/components/sprk-footer/sprk-footer.component.spec.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-footer/sprk-footer.component.ts
  src/angular/projects/spark-extras-angular-award/src/lib/spark-extras-angular-award.component.spec.ts
  src/angular/projects/spark-extras-angular-award/src/lib/spark-extras-angular-award.component.ts
  src/angular/src/app/spark-docs/award-docs/award-docs.component.ts
  src/angular/src/app/spark-docs/footer-docs/footer-docs.component.ts
  src/angular/src/styles.scss
  src/assets/drizzle/styles/utility/_toolkit-overrides.scss
  src/pages/tests/footer.hbs
  src/patterns/components/awards/primary.hbs
  src/patterns/components/footer/angular/code/base-awards-product.hbs
  src/patterns/components/footer/angular/code/base-footer.hbs
  src/patterns/components/footer/angular/code/base-with-awards.hbs
  src/patterns/components/footer/angular/code/base.hbs
  src/patterns/components/footer/angular/code/optional-with-awards.hbs
  src/patterns/components/footer/angular/code/optional.hbs
  src/patterns/components/footer/angular/docs/base-with-awards.hbs
  src/patterns/components/footer/angular/docs/base.hbs
  src/patterns/components/footer/angular/docs/optional-with-awards.hbs
  src/patterns/components/footer/angular/docs/optional.hbs
  src/patterns/components/footer/angular/info/base-footer.hbs
  src/patterns/components/footer/angular/info/base-with-awards.hbs
  src/patterns/components/footer/angular/info/base.hbs
  src/patterns/components/footer/angular/info/optional.hbs
  src/patterns/components/footer/base-awards-product.hbs
  src/patterns/components/footer/base-footer.hbs
  src/patterns/components/footer/base-items.hbs
  src/patterns/components/footer/base-with-awards.hbs
  src/patterns/components/footer/base.hbs
  src/patterns/components/footer/feedback-links.hbs
  src/patterns/components/footer/nav-link-columns.hbs
  src/patterns/components/footer/optional-with-awards.hbs
  src/patterns/components/footer/optional.hbs
  src/patterns/components/footer/social-links.hbs
  src/patterns/fundamentals/grid/stack-object-options.hbs
  src/patterns/utilities/single-property/typography.hbs
Labels: status: PR review

#653 [BUILD] Add a global site footer to Spark Docs
  packages/spark-core/package-lock.json
  packages/spark-extras/components/highlight-board/package-lock.json
  src/assets/drizzle/styles/base/_color.scss
  src/assets/drizzle/styles/base/_icons.scss
  src/assets/drizzle/styles/base/_type.scss
  src/assets/drizzle/styles/components/_footer.scss
  src/assets/drizzle/styles/main.scss
  src/assets/drizzle/styles/objects/_main-layout.scss
  src/assets/drizzle/styles/settings/_settings.scss
  src/assets/drizzle/styles/utility/_utility.scss
  src/templates/blank.hbs
  src/templates/collection.hbs
  src/templates/default.hbs
  src/templates/drizzle/footer.hbs
Labels: status: DO NOT MERGE, status: PR review

#718 add ng code for grid docs and fix grid docs typos
  package-lock.json
  packages/spark-core/package-lock.json
  src/angular/src/app/spark-docs/stack-docs/stack-docs.component.ts
  src/patterns/fundamentals/grid/angular/code/stack-object-five-cols.hbs
  src/patterns/fundamentals/grid/angular/code/stack-object-mixed-cols.hbs
  src/patterns/fundamentals/grid/angular/code/stack-object-seventy-twenty-five-cols.hbs
  src/patterns/fundamentals/grid/angular/code/stack-object-six-cols.hbs
  src/patterns/fundamentals/grid/angular/code/stack-object-sixty-forty-cols.hbs
  src/patterns/fundamentals/grid/angular/code/stack-object-three-cols.hbs
  src/patterns/fundamentals/grid/angular/code/stack-object-two-cols.hbs
  src/patterns/fundamentals/grid/stack-object-five-cols.hbs
  src/patterns/fundamentals/grid/stack-object-four-cols.hbs
  src/patterns/fundamentals/grid/stack-object-mixed-cols.hbs
  src/patterns/fundamentals/grid/stack-object-options.hbs
  src/patterns/fundamentals/grid/stack-object-seventy-twenty-five-cols.hbs
  src/patterns/fundamentals/grid/stack-object-six-cols.hbs
  src/patterns/fundamentals/grid/stack-object-sixty-forty-cols.hbs
  src/patterns/fundamentals/grid/stack-object-three-cols.hbs
  src/patterns/fundamentals/grid/stack-object-two-cols.hbs
Labels: status: PR review

#717 Angular pagination
  src/angular/projects/spark-core-angular/src/lib/components/sprk-pagination/sprk-pagination.component.spec.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-pagination/sprk-pagination.component.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-pagination/sprk-pagination.module.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-unordered-list/sprk-unordered-list.component.spec.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-unordered-list/sprk-unordered-list.component.ts
  src/angular/projects/spark-core-angular/src/lib/spark-core-angular.module.ts
  src/patterns/components/pagination/default.hbs
  src/patterns/components/pagination/long.hbs
Labels: status: PR review

#719 brought in the dictionary scss, fixes #710
  packages/spark-extras/components/dictionary/package-lock.json
  packages/spark-extras/package-lock.json
  src/angular/projects/spark-extras-angular-dictionary/src/lib/spark-extras-angular-dictionary.component.scss
  src/angular/projects/spark-extras-angular-dictionary/src/lib/spark-extras-angular-dictionary.component.ts
Labels: status: PR review

#723 Banner stuff
  src/pages/gettingstarted/design-principles.hbs
  src/pages/gettingstarted/designers.hbs
  src/pages/gettingstarted/developers.hbs
  src/pages/index.hbs
  src/patterns/components/masthead/base.hbs
  src/patterns/components/masthead/warning.hbs
  src/patterns/components/navigation/narrow.hbs
  src/patterns/components/navigation/secondary.hbs
  src/patterns/components/navigation/warning.hbs
  src/patterns/components/navigation/wide.hbs
  src/templates/collection.hbs
  src/templates/drizzle/update-warning.hbs
Labels: status: PR review

#725 Fix extras scss
  packages/spark-core/package-lock.json
  src/angular/projects/spark-extras-angular-card/src/lib/spark-extras-angular-card.component.scss
  src/angular/projects/spark-extras-angular-card/src/lib/spark-extras-angular-card.component.ts
  src/angular/projects/spark-extras-angular-dictionary/src/lib/spark-extras-angular-dictionary.component.scss
  src/angular/projects/spark-extras-angular-dictionary/src/lib/spark-extras-angular-dictionary.component.ts
  src/angular/projects/spark-extras-angular-highlight-board/package.json
  src/angular/src/app/spark-docs/stack-docs/stack-docs.component.ts
  src/angular/src/styles.scss
Labels: status: PR review

#728 Fall tabbed nav
  packages/spark-core/components/_tabs.scss
Labels: status: PR review

#727 Icon fixes
  packages/spark-core/components/_alerts.scss
  packages/spark-core/components/_icons.scss
  packages/spark-core/settings/_settings.scss
  src/angular/projects/spark-core-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.ts
  src/angular/src/app/spark-docs/footer-docs/footer-docs.component.ts
  src/angular/src/app/spark-docs/icon-set-docs/icon-set-docs.component.ts
  src/data/icons.yaml
  src/pages/tests/alerts.hbs
  src/pages/tests/example-one.hbs
  src/pages/tests/example-two.hbs
  src/pages/tests/navigation.hbs
  src/patterns/components/accordions/base.hbs
  src/patterns/components/awards/primary.hbs
  src/patterns/components/card/base.hbs
  src/patterns/components/footer/angular/code/base-awards-product.hbs
  src/patterns/components/footer/angular/code/base-footer.hbs
  src/patterns/components/footer/angular/code/base-with-awards.hbs
  src/patterns/components/footer/angular/code/optional-with-awards.hbs
  src/patterns/components/footer/angular/code/optional.hbs
  src/patterns/components/footer/base-awards-product.hbs
  src/patterns/components/footer/base-footer.hbs
  src/patterns/components/footer/base-with-awards.hbs
  src/patterns/components/footer/optional-with-awards.hbs
  src/patterns/components/footer/optional.hbs
  src/patterns/components/inputs/checkbox.hbs
  src/patterns/components/inputs/date.hbs
  src/patterns/components/inputs/datepicker.hbs
  src/patterns/components/inputs/inline-search-input.hbs
  src/patterns/components/inputs/monetary.hbs
  src/patterns/components/inputs/password.hbs
  src/patterns/components/inputs/phone.hbs
  src/patterns/components/inputs/radios.hbs
  src/patterns/components/inputs/search-input.hbs
  src/patterns/components/inputs/select.hbs
  src/patterns/components/inputs/ssn.hbs
  src/patterns/components/inputs/text-input.hbs
  src/patterns/components/inputs/textarea.hbs
  src/patterns/components/navigation/narrow.hbs
  src/patterns/components/navigation/wide.hbs
  src/patterns/components/pagination/long.hbs
  src/patterns/components/pagination/pager.hbs
  src/patterns/components/toggle/base.hbs
Labels: status: PR review

#731 Fall nav reskin
  packages/spark-core/_spark-core.scss
  packages/spark-core/components/_accordions.scss
  packages/spark-core/components/_secondary-navigation.scss
  packages/spark-core/components/_wide-navigation.scss
  packages/spark-core/components/wide-navigation.js
  packages/spark-core/package-lock.json
  packages/spark-core/settings/_colors.scss
  packages/spark-core/settings/_settings.scss
  packages/spark-core/tests/wideNavigation.tests.js
  packages/spark-core/tools/_mixins.scss
  src/angular/projects/spark-core-angular/src/lib/components/sprk-accordion/sprk-accordion.component.spec.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-narrow-navigation-item/sprk-narrow-navigation-item.component.spec.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-narrow-navigation-item/sprk-narrow-navigation-item.component.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-secondary-navigation/sprk-secondary-navigation.component.spec.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-secondary-navigation/sprk-secondary-navigation.component.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-wide-navigation/sprk-wide-navigation.component.ts
  src/angular/src/app/spark-docs/masthead-docs/masthead-docs.component.ts
  src/angular/src/app/spark-docs/navigation-docs/navigation-docs.component.ts
  src/assets/drizzle/scripts/drizzle.js
  src/assets/drizzle/styles/components/_navigation.scss
  src/assets/drizzle/styles/utility/_toolkit-overrides.scss
  src/assets/toolkit/styles/toolkit.scss
  src/patterns/components/navigation/narrow.hbs
  src/patterns/components/navigation/secondary.hbs
  src/patterns/components/navigation/wide.hbs
Labels: status: PR review

#736 Inline search reskin
  packages/spark-core/base/inputs/_text-input.scss
  src/angular/src/app/spark-docs/input-docs/input-docs.component.ts
  src/patterns/components/inputs/angular/code/inline-search-input.hbs
  src/patterns/components/inputs/inline-search-input.hbs
Labels: status: PR review

#683 Fall promos
  packages/spark-core/_spark-core.scss
  packages/spark-core/components/_promo.scss
  packages/spark-core/settings/_settings.scss
  src/angular/projects/spark-core-angular/src/lib/components/sprk-promo/sprk-promo.component.spec.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-promo/sprk-promo.component.ts
  src/angular/src/app/spark-docs/promo-docs/promo-docs.component.ts
  src/assets/toolkit/images/blue-house.jpg
  src/assets/toolkit/styles/toolkit.scss
  src/pages/tests/promo.hbs
  src/patterns/components/promo/angular/code/default.hbs
  src/patterns/components/promo/angular/code/has-icon.hbs
  src/patterns/components/promo/angular/docs/default.hbs
  src/patterns/components/promo/angular/info/default.hbs
  src/patterns/components/promo/base.hbs
  src/patterns/components/promo/collection.yaml
  src/patterns/components/promo/default.hbs
  src/patterns/components/promo/has-icon.hbs
  src/patterns/components/promo/has-image.hbs
  src/patterns/components/promo/is-reversed.hbs
Labels: fall 🎃, status: PR review

#742 Red Dead Redemption
  packages/spark-core/base/inputs/_text-input.scss
  packages/spark-core/components/_hamburger.scss
  packages/spark-core/components/_secondary-navigation.scss
  packages/spark-core/components/_spinners.scss
  packages/spark-core/components/_tabs.scss
  packages/spark-core/components/_wide-navigation.scss
  packages/spark-core/package-lock.json
  packages/spark-core/settings/_colors.scss
  packages/spark-core/settings/_settings.scss
  src/data/colors.yaml
Labels: status: PR review

#741 Masthead reskin
  packages/spark-core/components/_hamburger.scss
  packages/spark-core/components/_masthead.scss
  src/angular/projects/spark-core-angular/src/lib/components/sprk-masthead/sprk-masthead.component.spec.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
  src/angular/src/app/spark-docs/masthead-docs/masthead-docs.component.ts
  src/patterns/components/masthead/base.hbs
Labels: status: PR review

#743 making font updates
  packages/spark-core/base/_links.scss
  packages/spark-core/base/_typography.scss
  packages/spark-core/base/typography.js
  packages/spark-core/components/_buttons.scss
  packages/spark-core/settings/_settings.scss
  src/angular/src/styles.scss
  src/assets/toolkit/scripts/toolkit-prerender.js
  src/assets/toolkit/styles/toolkit.scss
Labels: status: PR review

#739 added icons, updated where to use exclamation
  src/angular/src/app/spark-docs/icon-set-docs/icon-set-docs.component.ts
  src/angular/src/app/spark-docs/input-docs/input-docs.component.ts
  src/data/icons.yaml
  src/patterns/components/inputs/checkbox.hbs
  src/patterns/components/inputs/date.hbs
  src/patterns/components/inputs/datepicker.hbs
  src/patterns/components/inputs/inline-search-input.hbs
  src/patterns/components/inputs/monetary.hbs
  src/patterns/components/inputs/password.hbs
  src/patterns/components/inputs/phone.hbs
  src/patterns/components/inputs/radios.hbs
  src/patterns/components/inputs/search-input.hbs
  src/patterns/components/inputs/select.hbs
  src/patterns/components/inputs/ssn.hbs
  src/patterns/components/inputs/text-input.hbs
  src/patterns/components/inputs/textarea.hbs
Labels: status: PR review

#749 fixing alerts, adjusting icon stroke-width, fixing error icon
  packages/spark-core/components/_alerts.scss
  packages/spark-core/settings/_settings.scss
  packages/spark-core/utilities/validation/setInvalidTextInput.js
Labels: status: PR review

#751 Accordion fixes
  packages/spark-core/components/_accordions.scss
  packages/spark-core/components/_masthead.scss
  packages/spark-core/components/_pagination.scss
  packages/spark-core/package-lock.json
  packages/spark-core/settings/_settings.scss
  src/angular/projects/spark-core-angular/src/lib/components/sprk-pagination/sprk-pagination.component.ts
  src/pages/gettingstarted/design-principles.hbs
Labels: status: PR review

#753 updating nvmrc for netlify
  .nvmrc
Labels: status: PR review

#750 fix masthead tabbing, fix narrow nav tabbing, add type settings to ma…
  packages/spark-core/components/_accordions.scss
  packages/spark-core/components/wide-navigation.js
  packages/spark-core/settings/_settings.scss
  src/pages/tests/masthead.hbs
Labels: status: PR review
