Repository sparkdesignsystem/spark-design-system, pull requests merged in 2019-04, with the labels that each got.

#1202 [Bug] Angular Inputs: Monetary Input doesnt show the $ icon
  src/angular/src/app/spark-docs/input-docs/input-docs.component.ts
  src/patterns/components/inputs/angular/code/monetary-disabled.hbs
  src/patterns/components/inputs/angular/code/monetary-error.hbs
  src/patterns/components/inputs/angular/code/monetary.hbs
  src/patterns/components/inputs/collection.yaml
Labels: js: angular, scope: core, status: PR review, type: bug

#1244 Show React code switch in staging
  src/assets/drizzle/scripts/code-example-switch.js
  src/templates/drizzle/code-example-switch.hbs
Labels: status: PR review

#1238 updating versions
  packages/spark-card/package.json
  packages/spark-core/package-lock.json
  packages/spark-core/package.json
  packages/spark-dictionary/package.json
  packages/spark-highlight-board/package-lock.json
  packages/spark-highlight-board/package.json
Labels: status: PR review

#1212 updating dependencies
  .travis.yml
  packages/spark-core/package-lock.json
  packages/spark-core/package.json
  packages/spark-highlight-board/package-lock.json
  packages/spark-highlight-board/package.json
Labels: status: PR review

#1240 [Bug] Narrow Nav scrolling in FF / Edge / IE11
  packages/spark-core/components/_masthead.scss
  src/angular/projects/spark-core-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
Labels: status: PR review

#1282 [Bug] Angular Inputs: Date Picker Input Calendar does not appear on click
  src/angular/projects/spark-core-angular/src/lib/directives/inputs/sprk-datepicker/sprk-datepicker.directive.ts
  src/angular/projects/spark-core-angular/src/lib/spark-core-angular.module.ts
  src/angular/src/app/spark-docs/stack-docs/stack-docs.component.ts
Labels: js: angular, status: PR review, type: bug

#1290 Update React Getting Started Docs
  src/pages/gettingstarted/react.hbs
Labels: status: PR review

#1288 Accordion changes and improvements
  .eslintrc
  src/react/projects/spark-react/src/SprkAccordion/SprkAccordion.js
Labels: js: react, status: PR review

#1287 Fix bug #1246
  src/patterns/components/buttons/react/info/base.hbs
Labels: status: PR review

#1286 [Bug] React icon non-working code samples
  src/templates/drizzle/icon-gallery.hbs
Labels: js: react, status: PR review, type: documentation

#1319 updated release notes
  src/pages/docs/release-notes.hbs
Labels: status: PR review

#1242 Allow cards to be full width - #1241
  packages/spark-card/_card.scss
  src/patterns/components/card/collection.yaml
Labels: status: PR review

#1285 Fix Bug-1252
  src/patterns/components/buttons/react/info/base.hbs
  src/react/projects/spark-react/src/SprkButton/SprkButton.js
  src/react/projects/spark-react/src/SprkButton/SprkButton.test.js
  src/react/src/routes/SprkButtonDocs/SprkButtonDocs.js
Labels: status: PR review

#1199 Refactor React to use SprkLink
  src/patterns/components/links/react/code/disabled.hbs
  src/patterns/components/links/react/code/icon-text.hbs
  src/patterns/components/links/react/code/inline.hbs
  src/patterns/components/links/react/code/simple.hbs
  src/patterns/components/links/react/info/inline.hbs
  src/react/projects/spark-react/src/SprkAccordion/components/SprkAccordionItem/SprkAccordionItem.js
  src/react/projects/spark-react/src/SprkAccordion/components/SprkAccordionItem/SprkAccordionItem.test.js
  src/react/projects/spark-react/src/SprkDropdown/SprkDropdown.js
  src/react/projects/spark-react/src/SprkDropdown/SprkDropdown.test.js
  src/react/projects/spark-react/src/SprkLink/SprkLink.js
  src/react/projects/spark-react/src/SprkLink/SprkLink.test.js
  src/react/projects/spark-react/src/SprkMasthead/SprkMasthead.js
  src/react/projects/spark-react/src/SprkMasthead/SprkMasthead.test.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadAccordion/SprkMastheadAccordion.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadAccordion/SprkMastheadAccordion.test.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.test.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadBigNav/SprkMastheadBigNav.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadBigNav/SprkMastheadBigNav.test.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadDropdown/SprkMastheadDropdown.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadDropdown/SprkMastheadDropdown.test.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadLittleNav/SprkMastheadLittleNav.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadLittleNav/SprkMastheadLittleNav.test.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadMenuIcon/SprkMastheadMenuIcon.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadMenuIcon/SprkMastheadMenuIcon.test.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadNarrowNav/SprkMastheadNarrowNav.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadNarrowNav/SprkMastheadNarrowNav.test.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadSelector/SprkMastheadSelector.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadSelector/SprkMastheadSelector.test.js
  src/react/projects/spark-react/src/SprkPagination/SprkPagination.js
  src/react/projects/spark-react/src/SprkPromo/SprkPromo.js
  src/react/projects/spark-react/src/SprkToggle/SprkToggle.js
  src/react/projects/spark-react/src/SprkToggle/SprkToggle.test.js
  src/react/src/routes/SprkLinkDocs/SprkLinkDocs.js
Labels: status: PR review

#1344 Update SprkLink & Masthead for React
  src/patterns/components/links/react/info/inline.hbs
  src/patterns/components/masthead/react/info/default.hbs
  src/react/projects/spark-react/src/SprkLink/SprkLink.js
  src/react/projects/spark-react/src/SprkLink/SprkLink.test.js
  src/react/projects/spark-react/src/SprkMasthead/SprkMasthead.js
  src/react/projects/spark-react/src/SprkMasthead/SprkMasthead.test.js
  src/react/src/routes/SprkLinkDocs/SprkLinkDocs.js
Labels: status: PR review

#1350 Update components using SprkLink
  src/react/projects/spark-react/src/SprkAccordion/components/SprkAccordionItem/SprkAccordionItem.js
  src/react/projects/spark-react/src/SprkDropdown/SprkDropdown.js
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadSelector/SprkMastheadSelector.js
  src/react/projects/spark-react/src/SprkToggle/SprkToggle.js
Labels: status: PR review

#1341 add back defaultProps to promo
  src/react/projects/spark-react/src/SprkMasthead/components/SprkMastheadDropdown/SprkMastheadDropdown.js
  src/react/projects/spark-react/src/SprkPromo/SprkPromo.js
Labels: status: PO approved

#1345 Update version after new 8.0.5 publish
  src/angular/projects/spark-core-angular/package.json
Labels: status: PO approved

#1354 update SprkPagination icons
  src/pages/docs/contributions.hbs
  src/patterns/components/pagination/react/info/default.hbs
  src/react/projects/spark-react/src/SprkPagination/SprkPagination.js
  src/react/projects/spark-react/src/SprkPagination/SprkPagination.test.js
Labels: status: PR review

#1351 Add option to use custom icons in Alerts
  src/patterns/components/alerts/react/info/info.hbs
  src/react/projects/spark-react/src/SprkAlert/SprkAlert.js
  src/react/projects/spark-react/src/SprkAlert/SprkAlert.test.js
  src/react/src/routes/SprkAlertDocs/SprkAlertDocs.js
Labels: status: PR review

#1321 React modal
  src/patterns/components/modals/angular/info/choice.hbs
  src/patterns/components/modals/choice.hbs
  src/patterns/components/modals/collection.yaml
  src/patterns/components/modals/info.hbs
  src/patterns/components/modals/react/code/choice.hbs
  src/patterns/components/modals/react/code/info.hbs
  src/patterns/components/modals/react/code/wait.hbs
  src/patterns/components/modals/react/docs/choice.hbs
  src/patterns/components/modals/react/docs/info.hbs
  src/patterns/components/modals/react/docs/wait.hbs
  src/patterns/components/modals/react/info/choice.hbs
  src/patterns/components/modals/vanilla/docs/choice.hbs
  src/patterns/components/modals/vanilla/info/choice.hbs
  src/patterns/components/modals/vanilla/info/wait.hbs
  src/patterns/components/modals/wait.hbs
  src/patterns/components/pagination/collection.yaml
  src/patterns/components/promo/react/info/default.hbs
  src/react/projects/spark-react/src/SprkModal/SprkModal.js
  src/react/projects/spark-react/src/SprkModal/SprkModal.test.js
  src/react/projects/spark-react/src/SprkModal/components/CloseButton/CloseButton.js
  src/react/projects/spark-react/src/SprkModal/components/CloseButton/CloseButton.test.js
  src/react/projects/spark-react/src/SprkModal/components/Mask/Mask.js
  src/react/projects/spark-react/src/SprkModal/components/Mask/Mask.test.js
  src/react/projects/spark-react/src/SprkModal/components/ModalFooter/ModalFooter.js
  src/react/projects/spark-react/src/SprkModal/components/ModalFooter/ModalFooter.test.js
  src/react/projects/spark-react/src/SprkPromo/SprkPromo.js
  src/react/projects/spark-react/src/SprkSpinner/SprkSpinner.js
  src/react/projects/spark-react/src/index.js
  src/react/projects/spark-react/src/windowStubs.js
  src/react/src/components/SiteNav/SiteNav.js
  src/react/src/routes/Router.js
  src/react/src/routes/SprkModalDocs/SprkModalDocs.js
  src/templates/drizzle/item.hbs
Labels: status: DO NOT MERGE, status: PR review

#1357 release notes update
  _redirects
  src/pages/docs/release-notes.hbs
Labels: status: PR review

#1365 Fix external links in sprk-dropdown - Angular
  src/angular/projects/spark-core-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
Labels: status: PR review
