Repository sparkdesignsystem/spark-design-system, pull requests merged in 2019-01, with the labels that each got.

#1000 Links misc
  packages/spark-core/base/_links.scss
  packages/spark-core/settings/_settings.scss
  src/angular/projects/spark-core-angular/src/lib/components/sprk-footer/sprk-footer.component.ts
  src/patterns/components/awards/primary.hbs
  src/patterns/components/card/base.hbs
  src/patterns/components/footer/footer.hbs
  src/patterns/components/links/collection.yaml
  src/patterns/components/links/inline.hbs
Labels: status: PR review

#995 918 inputs
  packages/spark-core/_spark-core.scss
  packages/spark-core/base/_inputs.scss
  packages/spark-core/base/inputs/_error-container.scss
  packages/spark-core/base/inputs/_input-container.scss
  packages/spark-core/base/inputs/_labels.scss
  packages/spark-core/base/inputs/_select.scss
  packages/spark-core/base/inputs/_selection-container.scss
  packages/spark-core/base/inputs/_svg-icon-input.scss
  packages/spark-core/base/inputs/_text-icon-input.scss
  packages/spark-core/base/inputs/_text-input.scss
  packages/spark-core/base/inputs/_textarea.scss
  packages/spark-core/base/selectInput.js
  packages/spark-core/base/textInput.js
  packages/spark-core/components/_datepicker.scss
  packages/spark-core/settings/_mappings.scss
  packages/spark-core/settings/_settings.scss
  packages/spark-core/spark-core-exports.js
  packages/spark-core/spark-core.js
  packages/spark-core/tests/selectInput.tests.js
  packages/spark-core/tests/textInput.tests.js
  src/angular/projects/spark-core-angular/src/lib/components/inputs/sprk-icon-input-container/sprk-icon-input-container.component.ts
  src/angular/projects/spark-core-angular/src/lib/components/inputs/sprk-input-container/sprk-input-container.component.ts
  src/angular/projects/spark-core-angular/src/lib/components/inputs/sprk-textarea-container/sprk-textarea-container.component.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-icon/sprk-icon.component.ts
  src/angular/projects/spark-core-angular/src/lib/directives/inputs/sprk-input/sprk-input-select.directive.spec.ts
  src/angular/projects/spark-core-angular/src/lib/directives/inputs/sprk-input/sprk-input.directive.spec.ts
  src/angular/projects/spark-core-angular/src/lib/directives/inputs/sprk-input/sprk-input.directive.ts
  src/angular/src/app/spark-docs/input-docs/input-docs.component.ts
  src/assets/drizzle/styles/components/_code-example-switch.scss
  src/patterns/components/inputs/angular/code/inline-search-input.hbs
  src/patterns/components/inputs/collection.yaml
  src/patterns/components/inputs/date.hbs
  src/patterns/components/inputs/datepicker.hbs
  src/patterns/components/inputs/inline-search-input.hbs
  src/patterns/components/inputs/monetary.hbs
  src/patterns/components/inputs/password.hbs
  src/patterns/components/inputs/phone.hbs
  src/patterns/components/inputs/search-input.hbs
  src/patterns/components/inputs/select.hbs
  src/patterns/components/inputs/ssn.hbs
  src/patterns/components/inputs/text-input-disabled.hbs
  src/patterns/components/inputs/text-input.hbs
  src/patterns/components/inputs/textarea-error.hbs
  src/patterns/components/inputs/textarea.hbs
Labels: status: PR review

#993 #921 Add New Masthead
  packages/spark-core/components/_accordions.scss
  packages/spark-core/components/_dropdown.scss
  packages/spark-core/components/_masthead.scss
  packages/spark-core/components/masthead.js
  packages/spark-core/components/toggle.js
  packages/spark-core/settings/_settings.scss
  packages/spark-core/spark-core-exports.js
  packages/spark-core/tests/masthead.tests.js
  packages/spark-core/tests/toggle.tests.js
  packages/spark-core/tools/_mixins.scss
  packages/spark-core/utilities/_utilities.scss
  src/angular/projects/spark-core-angular/src/lib/components/sprk-narrow-navigation-item/sprk-narrow-navigation-item.component.spec.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-narrow-navigation-item/sprk-narrow-navigation-item.component.ts
  src/angular/projects/spark-core-angular/src/lib/components/sprk-narrow-navigation/sprk-narrow-navigation.component.ts
  src/pages/tests/masthead-default.hbs
  src/pages/tests/masthead-extended.hbs
  src/patterns/components/masthead/collection.yaml
  src/patterns/components/masthead/default.hbs
  src/patterns/components/masthead/extended.hbs
  src/patterns/components/masthead/navigation/big-nav.hbs
  src/patterns/components/masthead/navigation/narrow.hbs
Labels: status: DO NOT MERGE

#1027 [#1002] - Reskin pagination by changing primary color, fonts, and sizes
  packages/spark-core/components/_pagination.scss
  packages/spark-core/settings/_settings.scss
  src/angular/projects/spark-core-angular/src/lib/components/sprk-pagination/sprk-pagination.component.ts
  src/patterns/components/pagination/collection.yaml
  src/patterns/components/pagination/default.hbs
  src/patterns/components/pagination/long.hbs
  src/patterns/components/pagination/pager.hbs
Labels: status: ready to merge

#1023 (#1022) - Differing heights between select box and rest of input elements
  packages/spark-core/settings/_settings.scss
  src/patterns/components/inputs/collection.yaml
Labels: status: ready to merge

#1029 Remove top header, add test commands
  .github/pull_request_template.md
Labels: status: ready to merge

#1030 adding icon link hover style
  packages/spark-core/base/_links.scss
  packages/spark-core/settings/_settings.scss
  src/patterns/components/links/collection.yaml
Labels: status: ready to merge

#1025 update publish commands, flatten spark-extras
  .travis.yml
  docs/README.md
  docs/drizzle_default_layout.png
  gulp/angular/dev-app/angulardevapp.gulpfile.js
  gulp/spark-extras/spark-card.gulpfile.js
  gulp/spark-extras/spark-dictionary.gulpfile.js
  gulp/spark-extras/spark-extras.gulpfile.js
  gulp/spark-extras/spark-highlight-board.gulpfile.js
  gulpfile.js
  lerna.json
  package-lock.json
  package.json
  packages/spark-card/_card.scss
  packages/spark-card/package-lock.json
  packages/spark-card/package.json
  packages/spark-core/package-lock.json
  packages/spark-core/package.json
  packages/spark-dictionary/_dictionary.scss
  packages/spark-dictionary/package-lock.json
  packages/spark-dictionary/package.json
  packages/spark-extras/components/dictionary/package-lock.json
  packages/spark-extras/components/highlight-board/tests/_setup.js
  packages/spark-extras/package-lock.json
  packages/spark-extras/package.json
  packages/spark-extras/tests/example.tests.js
  packages/spark-highlight-board/.gitignore
  packages/spark-highlight-board/.npmignore
  packages/spark-highlight-board/_highlight-board.scss
  packages/spark-highlight-board/highlight-board.js
  packages/spark-highlight-board/package-lock.json
  packages/spark-highlight-board/package.json
  packages/spark-highlight-board/tests/_setup.js
  packages/spark-highlight-board/tests/highligh-board.tests.js
  packages/spark-highlight-board/webpack.config.js
  src/angular/package-lock.json
  src/angular/package.json
  src/angular/projects/spark-core-angular/package.json
  src/angular/projects/spark-core-angular/src/lib/directives/inputs/sprk-datepicker/sprk-datepicker.directive.spec.ts
  src/angular/projects/spark-extras-angular-award/package.json
  src/angular/projects/spark-extras-angular-card/package.json
  src/angular/projects/spark-extras-angular-dictionary/package.json
  src/angular/projects/spark-extras-angular-highlight-board/package.json
  src/angular/src/styles.scss
  src/assets/toolkit/scripts/toolkit.js
  src/assets/toolkit/styles/toolkit.scss
Labels: status: ready to merge

#1037 Update Release Notes
  src/pages/docs/release-notes.hbs
  src/patterns/fundamentals/layers/base.hbs
Labels: status: ready to merge

#1040 Add Masthead Functions to Exports
  packages/spark-core/components/masthead.js
  packages/spark-core/spark-core-exports.js
Labels: status: PR review, status: ready to merge

#1042 #1004 - Update Button docs
  src/patterns/components/buttons/base.hbs
  src/patterns/components/buttons/collection.yaml
  src/patterns/components/buttons/tertiary.hbs
Labels: status: PR review

#1043 #997 - Update example two test page
  src/pages/tests/example-two.hbs
Labels: status: PR review

#1046 Update code switcher to show React code if 'react' query string detected
  src/assets/drizzle/scripts/code-example-switch.js
  src/patterns/components/accordions/angular/code/secondary.hbs
  src/patterns/components/accordions/angular/docs/secondary.hbs
  src/patterns/components/accordions/angular/info/secondary.hbs
  src/patterns/components/accordions/primary.hbs
  src/patterns/components/accordions/react/code/base.hbs
  src/patterns/components/accordions/react/code/primary.hbs
  src/patterns/components/accordions/react/code/secondary.hbs
  src/patterns/components/accordions/react/docs/primary.hbs
  src/patterns/components/accordions/react/docs/secondary.hbs
  src/patterns/components/accordions/react/info/primary.hbs
  src/patterns/components/accordions/react/info/secondary.hbs
  src/templates/drizzle/code-example-switch.hbs
  src/templates/drizzle/item.hbs
Labels: status: PR review

#1058 Add Spark React Link Component
  .github/pull_request_template.md
  .travis.yml
  gulp/drizzle/config.js
  gulp/react/spark-core-react/spark-core-react.gulpfile.js
  gulpfile.js
  src/patterns/components/links/disabled.hbs
  src/patterns/components/links/icon-text.hbs
  src/patterns/components/links/inline.hbs
  src/patterns/components/links/react/code/disabled.hbs
  src/patterns/components/links/react/code/icon-text.hbs
  src/patterns/components/links/react/code/inline.hbs
  src/patterns/components/links/react/code/simple.hbs
  src/patterns/components/links/react/info/disabled.hbs
  src/patterns/components/links/react/info/icon-text.hbs
  src/patterns/components/links/react/info/inline.hbs
  src/patterns/components/links/react/info/simple.hbs
  src/patterns/components/links/simple.hbs
  src/react/package-lock.json
  src/react/package.json
  src/react/projects/spark-core-react/package-lock.json
  src/react/projects/spark-core-react/package.json
  src/react/projects/spark-core-react/src/SprkLink/SprkLink.js
  src/react/projects/spark-core-react/src/SprkLink/SprkLink.test.js
  src/react/projects/spark-core-react/src/index.js
  src/react/src/components/SiteNav/SiteNav.js
  src/react/src/routes/Router.js
  src/react/src/routes/SprkLinkDocs/SprkLinkDocs.js
Labels: status: PR review

#1057 React buttons
  .eslintignore
  .travis.yml
  gulpfile.js
  packages/spark-core/settings/_settings.scss
  src/patterns/components/buttons/at-small.hbs
  src/patterns/components/buttons/at-xsmall.hbs
  src/patterns/components/buttons/base.hbs
  src/patterns/components/buttons/disabled.hbs
  src/patterns/components/buttons/react/code/at-small.hbs
  src/patterns/components/buttons/react/code/at-xsmall.hbs
  src/patterns/components/buttons/react/code/base.hbs
  src/patterns/components/buttons/react/code/disabled.hbs
  src/patterns/components/buttons/react/code/primary.hbs
  src/patterns/components/buttons/react/code/secondary.hbs
  src/patterns/components/buttons/react/code/submission.hbs
  src/patterns/components/buttons/react/code/tertiary.hbs
  src/patterns/components/buttons/react/info/base.hbs
  src/patterns/components/buttons/react/info/secondary.hbs
  src/patterns/components/buttons/react/info/tertiary.hbs
  src/patterns/components/buttons/secondary.hbs
  src/patterns/components/buttons/submission.hbs
  src/patterns/components/buttons/tertiary.hbs
  src/react/.gitignore
  src/react/projects/spark-core-react/package-lock.json
  src/react/projects/spark-core-react/package.json
  src/react/projects/spark-core-react/src/SparkButton/SparkButton.js
  src/react/projects/spark-core-react/src/SprkButton/SprkButton.js
  src/react/projects/spark-core-react/src/SprkButton/SprkButton.test.js
  src/react/projects/spark-core-react/src/SprkLink/SprkLink.js
  src/react/projects/spark-core-react/src/SprkSpinner/SprkSpinner.js
  src/react/projects/spark-core-react/src/SprkSpinner/SprkSpinner.test.js
  src/react/projects/spark-core-react/src/index.js
  src/react/src/container/App/App.test.js
  src/react/src/containers/App/App.js
  src/react/src/containers/CentralColumnLayout/CentralColumnLayout.js
  src/react/src/containers/ExampleContainer/ExampleContainer.js
  src/react/src/index.js
  src/react/src/routes/Homepage/Homepage.js
  src/react/src/routes/Router.js
  src/react/src/routes/SparkButtonDocs/SparkButtonDocs.js
  src/react/src/routes/SprkButtonDocs/SprkButtonDocs.js
  src/react/src/routes/SprkLinkDocs/SprkLinkDocs.js
  src/templates/collection.hbs
Labels: status: PR review

#1088 Add React alert
  src/patterns/components/alerts/fail.hbs
  src/patterns/components/alerts/info.hbs
  src/patterns/components/alerts/no-dismiss.hbs
  src/patterns/components/alerts/react/code/base.hbs
  src/patterns/components/alerts/react/code/fail.hbs
  src/patterns/components/alerts/react/code/info.hbs
  src/patterns/components/alerts/react/code/no-dismiss.hbs
  src/patterns/components/alerts/react/code/success.hbs
  src/patterns/components/alerts/react/info/fail.hbs
  src/patterns/components/alerts/react/info/info.hbs
  src/patterns/components/alerts/react/info/success.hbs
  src/patterns/components/alerts/success.hbs
  src/react/projects/spark-core-react/src/SprkAlert/SprkAlert.js
  src/react/projects/spark-core-react/src/SprkAlert/SprkAlert.test.js
  src/react/projects/spark-core-react/src/index.js
  src/react/src/components/SiteNav/SiteNav.js
  src/react/src/routes/Router.js
  src/react/src/routes/SprkAlertDocs/SprkAlertDocs.js
  src/react/src/routes/SprkLinkDocs/SprkLinkDocs.js
Labels: status: PR review
