Repository sparkdesignsystem/spark-design-system, pull requests merged in 2019-07, with the labels that each got.

#1486 restructure new docs site to create pages based off mdx files instead of directories
  react/.storybook/config.js
  react/.storybook/presets.js
  react/gatsby-config.js
  react/gatsby-node.js
  react/package-lock.json
  react/package.json
  react/src/components/layout.js
  react/src/components/site-navigation.js
  react/src/templates/ComponentPage.js
  spark/components/accordions/react/SprkAccordion.stories.mdx
  spark/components/alerts/react/SprkAlert.stories.mdx
  spark/components/stepper/react/SprkStepper.stories.js
Labels: status: PR review

#1559 add storybook build to build command, update componentPage
  react/package.json
Labels: status: PR review

#1558 setup jest config, fixes imports in a few test files, set up coverage
  .gitignore
  spark/base/inputs/react/SprkRevealInput.test.js
  spark/base/inputs/react/SprkTextInput.test.js
  spark/base/lists/react/SprkList.test.js
  spark/components/alerts/react/SprkAlert.test.js
  spark/components/modals/react/SprkModal.js
  spark/components/modals/react/SprkModal.test.js
  spark/components/pagination/react/SprkPagination.js
  spark/components/pagination/react/SprkPagination.test.js
  spark/manifests/spark-react/babel.config.js
  spark/manifests/spark-react/jest-config.js
  spark/manifests/spark-react/package-lock.json
  spark/manifests/spark-react/package.json
  spark/manifests/spark-react/setup.test.js
Labels: status: PR review

#1566 Stepper - remove extraneous p tag
  src/react/projects/spark-react/src/SprkStepper/components/SprkStepperStep/SprkStepperStep.js
  src/react/src/routes/SprkStepperDocs/SprkStepperDocs.js
Labels: js: react, status: PR review

#1576 adding stylelint
  .eslintignore
  .eslintrc
  .stylelintrc
  package-lock.json
  package.json
  spark/.eslintignore
  spark/components/accordions/vanilla/accordions.stories.js
  spark/components/alerts/vanilla/alerts.stories.js
  spark/components/buttons/vanilla/button.stories.js
  spark/components/card/react/SprkCard.stories.js
  spark/components/dictionary/react/SprkDictionary.stories.js
  spark/components/dropdown/react/SprkDropdown.stories.js
  spark/components/footer/react/SprkFooter.stories.js
  spark/components/highlight-board/react/SprkHighlightBoard.stories.js
  spark/components/masthead/react/SprkMasthead.stories.js
  spark/components/modals/react/SprkModal.stories.js
  spark/components/modals/vanilla/modals.js
  spark/components/pagination/react/SprkPagination.stories.js
  spark/components/promo/react/SprkPromo.stories.js
  spark/components/stepper/react/SprkStepper.stories.js
  spark/components/tabs/react/SprkTabs.stories.js
  spark/components/toggle/react/SprkToggle.stories.js
Labels: status: PR review

#1565 adding npm install to build command
  react/package-lock.json
  react/package.json
Labels: status: DO NOT MERGE

#1587 Get React components to render in MDX files
  .gitignore
  package-lock.json
  react/.storybook/config.js
  react/gatsby-config.js
  react/gatsby-node.js
  react/package-lock.json
  react/package.json
  react/src/components/ComponentDocSample.js
  react/src/templates/ComponentPage.js
  spark/base/links/react/SprkLink.stories.mdx
  spark/components/accordions/react/SprkAccordion.stories.mdx
  spark/components/alerts/react/SprkAlert.stories.mdx
  spark/components/modals/react/SprkModal.js
Labels: status: PR review

#1588 set up algolia search
  src/assets/drizzle/styles/base/_inputs.scss
  src/assets/drizzle/styles/main.scss
  src/assets/drizzle/styles/objects/_main-layout.scss
  src/assets/drizzle/styles/vendor/_algolia.scss
  src/templates/default.hbs
  src/templates/drizzle/nav.hbs
Labels: status: PR review

#1590 React Stepper - more unit tests
  src/react/projects/spark-react/src/SprkStepper/SprkStepper.js
  src/react/projects/spark-react/src/SprkStepper/SprkStepper.test.js
  src/react/projects/spark-react/src/SprkStepper/components/SprkStepperSlider/SprkStepperSlider.test.js
  src/react/projects/spark-react/src/SprkStepper/components/SprkStepperStep/SprkStepperStep.js
  src/react/projects/spark-react/src/SprkStepper/components/SprkStepperStep/SprkStepperStep.test.js
Labels: status: PR review

#1594 Add manual testing plan checklist to PR template
  .github/pull_request_template.md
Labels: status: PR review

#1600 Add a few missing stories per issue #1398/Upgrade Storybook
  react/package-lock.json
  react/package.json
  spark/components/buttons/react/SprkButton.stories.js
  spark/components/card/react/SprkCard.stories.js
Labels: status: PR review

#1614 1609 pull gatsby to root
  .babelrc
  LICENSE copy
  README copy.md
  gatsby-browser.js
  gatsby-config.js
  gatsby-node.js
  gatsby-ssr.js
  package-lock.json
  package.json
  plugins/gatsby-symbol-set-fetch/gatsby-node.js
  plugins/gatsby-symbol-set-fetch/package-lock.json
  plugins/gatsby-symbol-set-fetch/package.json
  react/.gitignore
  react/.storybook/config.js
  react/gatsby-config.js
  react/gatsby-node.js
  react/package-lock.json
  react/package.json
  src/components/ComponentDocList.js
  src/components/ComponentDocSample.js
  src/components/content-iframe.js
  src/components/header.js
  src/components/image.js
  src/components/layout.js
  src/components/seo.js
  src/components/site-logo.js
  src/components/site-navigation.js
  src/images/gatsby-astronaut.png
  src/images/gatsby-icon.png
  src/pages/404.js
  src/pages/index.js
  src/scss/_spark-theme.scss
  src/scss/components/_header.scss
  src/scss/components/_iframe.scss
  src/scss/components/_layout.scss
  src/scss/components/_navigation.scss
  src/scss/main.scss
  src/templates/ComponentPage.js
  src/templates/DocPage.js
  src/templates/FundamentalPage.js
  storybook-spark-theme.js
Labels: status: PR review

#1615 Add Storybook Knobs for Links, Alerts, and Button components
  package-lock.json
  react/.gitignore
  react/.storybook/config.js
  react/.storybook/presets.js
  react/.storybook/webpack.config.js
  react/package-lock.json
  react/package.json
  spark/base/inputs/react/SprkInput.stories.js
  spark/base/links/react/SprkLink.stories.js
  spark/base/lists/react/SprkList.stories.js
  spark/base/tables/react/SprkTable.stories.js
  spark/components/accordions/react/SprkAccordion.stories.js
  spark/components/alerts/react/SprkAlert.stories.js
  spark/components/awards/react/SprkAward.stories.js
  spark/components/buttons/react/SprkButton.stories.js
  spark/components/card/react/SprkCard.stories.js
  spark/components/dictionary/react/SprkDictionary.stories.js
  spark/components/dividers/react/SprkDivider.stories.js
  spark/components/dropdown/react/SprkDropdown.stories.js
  spark/components/footer/react/SprkFooter.stories.js
  spark/components/highlight-board/react/SprkHighlightBoard.stories.js
  spark/components/masthead/react/SprkMasthead.stories.js
  spark/components/promo/react/SprkPromo.stories.js
  spark/components/tabs/react/SprkTabs.stories.js
  spark/components/toggle/react/SprkToggle.stories.js
Labels: status: PR review

#1589 Floating label for huge input
  packages/spark/base/hugeTextInput.js
  packages/spark/base/inputs/_input-container.scss
  packages/spark/base/inputs/_labels.scss
  packages/spark/base/inputs/_svg-icon-input.scss
  packages/spark/base/inputs/_text-icon-input.scss
  packages/spark/base/inputs/_text-input.scss
  packages/spark/components/_icons.scss
  packages/spark/settings/_settings.scss
  packages/spark/spark.js
  packages/spark/utilities/toggleClassWithValue.js
  src/patterns/components/inputs/collection.yaml
  src/patterns/components/inputs/date.hbs
  src/patterns/components/inputs/datepicker.hbs
  src/patterns/components/inputs/helper-text.hbs
  src/patterns/components/inputs/password.hbs
  src/patterns/components/inputs/phone.hbs
  src/patterns/components/inputs/search-input.hbs
  src/patterns/components/inputs/ssn.hbs
  src/patterns/components/inputs/text-input-huge-disabled.hbs
  src/patterns/components/inputs/text-input-huge-error.hbs
  src/patterns/components/inputs/text-input-huge.hbs
  src/patterns/components/toggle/collection.yaml
Labels: status: PR review

#1597 React Stepper slider animations
  .travis.yml
  packages/spark/components/_stepper.scss
  packages/spark/settings/_settings.scss
  src/patterns/components/stepper/collection.yaml
  src/react/projects/spark-react/src/SprkStepper/SprkStepper.js
  src/react/projects/spark-react/src/SprkStepper/components/SprkStepperSlider/SprkStepperSlider.js
Labels: status: DO NOT MERGE, status: PR review

#1656 added lodash to deps, adjusted import in masthead
  .travis.yml
  packages/spark/components/masthead.js
  packages/spark/package-lock.json
  packages/spark/package.json
Labels: status: PR review
