Repository sparkdesignsystem/spark-design-system, pull requests merged in 2019-11, with the labels that each got.

#2294 Fix Huge Text Input Default Value on IE/Edge - React
  react/src/base/inputs/SprkInput.stories.js
  react/src/base/inputs/SprkTextInput/SprkTextInput.js
  react/src/base/inputs/SprkTextInput/SprkTextInput.test.js
  react/src/base/inputs/components/SprkInputElement/SprkInputElement.js
Labels: status: PR review

#2269 Add list component to SB - HTML & Angular
  angular/projects/spark-angular/src/lib/components/sprk-ordered-list/sprk-list.stories.ts
  html/base/list.stories.js
Labels: status: PR review

#2267 Add example component page with iframe
  html/.storybook/config.js
  html/components/masthead.stories.js
  html/components/modals.stories.js
  html/package-lock.json
  html/package.json
  package-lock.json
  package.json
  react/src/components/alerts/SprkAlert.stories.js
  src/components/ComponentPreview.js
  src/components/DevDocLinks.js
  src/components/Footer.js
  src/components/layouts/Layout.js
  src/components/markdown-render/h1.js
  src/components/markdown-render/h2.js
  src/components/markdown-render/h3.js
  src/components/markdown-render/li.js
  src/components/markdown-render/ul.js
  src/pages/installing-spark/setting-up-your-environment.mdx
  src/pages/using-spark/components/accordion.mdx
  src/pages/using-spark/components/alert.mdx
  src/pages/using-spark/components/footer.mdx
  src/pages/using-spark/components/masthead.mdx
  src/pages/using-spark/components/modal.mdx
  src/pages/using-spark/components/stepper.mdx
  src/pages/using-spark/foundations/sass-variables.mdx
  src/scss/components/_component-preview.scss
  src/scss/components/_footer.scss
  src/scss/components/_layout.scss
  src/scss/main.scss
Labels: status: PR review

#2295 Algolia docsearch
  gatsby-browser.js
  gatsby-ssr.js
  src/components/Header.js
  src/components/Menu.js
  src/scss/_settings.scss
  src/scss/components/_header.scss
  src/scss/components/_layout.scss
  src/scss/main.scss
  src/scss/vendor/_algolia.scss
Labels: status: PR review

#2309 add SprkDivider imports to example mdx components + udpate SB Docs styles
  html/components/_dividers.scss
  react/.storybook/config.js
  react/src/base/inputs/SprkInput.stories.js
  react/src/base/links/SprkLink.stories.js
  react/src/base/lists/SprkList.stories.js
  react/src/base/tables/SprkTable.stories.js
  react/src/components/accordions/SprkAccordion.stories.js
  react/src/components/alerts/SprkAlert.stories.js
  react/src/components/awards/SprkAward.stories.js
  react/src/components/buttons/SprkButton.stories.js
  react/src/components/card/SprkCard.stories.js
  react/src/components/dictionary/SprkDictionary.stories.js
  react/src/components/dividers/SprkDivider.stories.js
  react/src/components/dropdown/SprkDropdown.stories.js
  react/src/components/footer/SprkFooter.stories.js
  react/src/components/highlight-board/SprkHighlightBoard.stories.js
  react/src/components/icons/SprkIcon.stories.js
  react/src/components/masthead/SprkMasthead.stories.js
  react/src/components/modals/SprkModal.stories.js
  react/src/components/pagination/SprkPagination.stories.js
  react/src/components/promo/SprkPromo.stories.js
  react/src/components/stepper/SprkStepper.stories.js
  react/src/components/tabs/SprkTabs.stories.js
  react/src/components/toggle/SprkToggle.stories.js
  react/src/objects/stack/SprkStack.stories.js
  src/pages/using-spark/components/masthead.mdx
  src/pages/using-spark/components/modal.mdx
  src/pages/using-spark/components/stepper.mdx
  storybook-theming/_docs.scss
  storybook-theming/storybook-spark-theme.js
Labels: status: PR review

#2262 React decorator individualized
  react/.storybook/config.js
  react/src/base/inputs/SprkInput.stories.js
  react/src/base/links/SprkLink.stories.js
  react/src/base/lists/SprkList.stories.js
  react/src/base/tables/SprkTable.stories.js
  react/src/components/accordions/SprkAccordion.stories.js
  react/src/components/alerts/SprkAlert.stories.js
  react/src/components/awards/SprkAward.stories.js
  react/src/components/buttons/SprkButton.stories.js
  react/src/components/card/SprkCard.stories.js
  react/src/components/dictionary/SprkDictionary.stories.js
  react/src/components/dividers/SprkDivider.stories.js
  react/src/components/dropdown/SprkDropdown.stories.js
  react/src/components/footer/SprkFooter.stories.js
  react/src/components/highlight-board/SprkHighlightBoard.stories.js
  react/src/components/icons/SprkIcon.stories.js
  react/src/components/masthead/SprkMasthead.stories.js
  react/src/components/modals/SprkModal.stories.js
  react/src/components/pagination/SprkPagination.stories.js
  react/src/components/promo/SprkPromo.stories.js
  react/src/components/stepper/SprkStepper.stories.js
  react/src/components/tabs/SprkTabs.stories.js
  react/src/components/toggle/SprkToggle.stories.js
  react/src/objects/stack/SprkStack.stories.js
Labels: js: react, status: PR review

#2313 masthead and footer had duplicate exports
  react/src/components/footer/SprkFooter.stories.js
  react/src/components/masthead/SprkMasthead.stories.js
Labels: Component: Footer, Component: Masthead, js: react, type: bug

#2340 add centered column to HTML sb
  html/.storybook/config.js
  html/components/centered-column.stories.js
  storybook-theming/_docs.scss
Labels: status: PR review

#2339 adding box story and preview css
  html/objects/box.stories.js
Labels: status: PR review

#2343 add Stack to html sb
  html/components/stack.stories.js
  storybook-theming/_docs.scss
Labels: status: PR review

#2344 add stack stories for angular storybook
  angular/projects/spark-angular/src/lib/components/sprk-stack/sprk-stack.stories.ts
Labels: status: PR review

#2346 add stack react sb
  html/components/stack.stories.js
  html/objects/stack.stories.js
  react/src/objects/stack/SprkStack.stories.js
Labels: status: PR review

#2345 2333 spacing html
  html/components/centered-column.stories.js
  html/objects/centered-column.stories.js
  html/utilities/spacing.stories.js
  storybook-theming/_docs.scss
  storybook-theming/scss/_spacing.scss
Labels: status: PR review

#2348 Update SBs to all be on @next, rename story files, add design docs link
  html/.storybook/config.js
  html/.storybook/presets.js
  html/base/inputs.stories.js
  html/base/link.stories.js
  html/base/list.stories.js
  html/base/table.stories.js
  html/components/accordion.stories.js
  html/components/alert.stories.js
  html/components/award.stories.js
  html/components/button.stories.js
  html/components/card.stories.js
  html/components/dictionary.stories.js
  html/components/divider.stories.js
  html/components/dropdown.stories.js
  html/components/footer.stories.js
  html/components/highlight-board.stories.js
  html/components/icons.stories.js
  html/components/masthead.stories.js
  html/components/modal.stories.js
  html/components/pagination.stories.js
  html/components/promo.stories.js
  html/components/spinners.stories.js
  html/components/stepper.stories.js
  html/components/tabs.stories.js
  html/components/toggle.stories.js
  html/objects/box.stories.js
  html/objects/centered-column.stories.js
  html/objects/flag.stories.js
  html/objects/horizontal-list.stories.js
  html/objects/stack.stories.js
  html/objects/vertical-list.stories.js
  html/package-lock.json
  html/package.json
  react/.storybook/config.js
  react/package-lock.json
  react/package.json
Labels: status: PR review

#2354 tweak iframe heights in sb docs
  angular/.storybook/config.js
  angular/projects/spark-angular/src/lib/components/inputs/sprk-input.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-divider/sprk-divider.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-link/sprk-link.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-ordered-list/sprk-list.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-stack/sprk-stack.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-table/sprk-table.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.stories.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.stories.ts
  storybook-theming/_docs.scss
Labels: status: DO NOT MERGE

#2360 2350 spacing update
  html/utilities/spacing.stories.js
  storybook-theming/scss/_spacing.scss
Labels: status: ready to merge

#2361 added typography to html sb
  html/base/typography.stories.js
  html/utilities/spacing.stories.js
Labels: status: ready to merge

#2365 breaks out the inputs into separate stories (React)
  react/src/base/inputs/Checkbox.stories.js
  react/src/base/inputs/Date.stories.js
  react/src/base/inputs/DatePicker.stories.js
  react/src/base/inputs/HelperText.stories.js
  react/src/base/inputs/HugeSelect.stories.js
  react/src/base/inputs/HugeText.stories.js
  react/src/base/inputs/Monetary.stories.js
  react/src/base/inputs/Password.stories.js
  react/src/base/inputs/Percentage.stories.js
  react/src/base/inputs/Phone.stories.js
  react/src/base/inputs/Radio.stories.js
  react/src/base/inputs/SSN.stories.js
  react/src/base/inputs/Search.stories.js
  react/src/base/inputs/Select.stories.js
  react/src/base/inputs/SprkInput.stories.js
  react/src/base/inputs/Text.stories.js
  react/src/base/inputs/Textarea.stories.js
Labels: status: PR review

#2376 2369 inputs stories angular
  angular/projects/spark-angular/src/lib/components/inputs/Checkbox.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Date.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/DatePicker.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/HelperText.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/HugeSelect.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/HugeText.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Monetary.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Password.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Percentage.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Phone.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Radio.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/SSN.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Search.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Select.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Text.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Textarea.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-input.stories.ts
Labels: status: PR review

#2371 breaking out html input stories
  html/base/inputs.stories.js
  html/base/inputs/Checkbox.stories.js
  html/base/inputs/Date.stories.js
  html/base/inputs/DatePicker.stories.js
  html/base/inputs/HelperText.stories.js
  html/base/inputs/HugeSelect.stories.js
  html/base/inputs/HugeText.stories.js
  html/base/inputs/Monetary.stories.js
  html/base/inputs/Password.stories.js
  html/base/inputs/Percentage.stories.js
  html/base/inputs/Phone.stories.js
  html/base/inputs/Radio.stories.js
  html/base/inputs/SSN.stories.js
  html/base/inputs/Search.stories.js
  html/base/inputs/Select.stories.js
  html/base/inputs/Text.stories.js
  html/base/inputs/Textarea.stories.js
  html/base/inputs/_input-container.scss
Labels: status: PR review
