Repository sparkdesignsystem/spark-design-system, pull requests merged in 2019-10, with the labels that each got.

#2080 Storybook React Tabs
  spark/components/tabs/react/SprkTabs.js
  spark/components/tabs/react/SprkTabs.stories.js
  spark/components/tabs/react/components/SprkTabsButton.js
  spark/components/tabs/react/components/SprkTabsButton.test.js
  spark/components/tabs/react/components/SprkTabsPanel.js
  spark/components/tabs/react/components/SprkTabsPanel.test.js
Labels: status: PR review

#2075 Add React Pagination to Storybook
  spark/components/pagination/react/SprkPagination.stories.js
  spark/components/pagination/react/SprkPagination.test.js
Labels: status: PR review

#2071 Adds React Modal to Storybook
  spark/components/modals/react/SprkModal.stories.js
Labels: status: PR review

#2070 Add React Stepper to Storybook
  spark/components/stepper/react/SprkStepper.js
  spark/components/stepper/react/SprkStepper.stories.js
  spark/components/stepper/react/SprkStepper.test.js
  spark/components/stepper/react/components/SprkStepperSlider/SprkStepperSlider.js
  spark/components/stepper/react/components/SprkStepperSlider/SprkStepperSlider.test.js
  spark/components/stepper/react/components/SprkStepperStep/SprkStepperStep.js
  spark/components/stepper/react/components/SprkStepperStep/SprkStepperStep.test.js
Labels: status: PR review

#2081 Update Gatsby
  package-lock.json
  package.json
Labels: status: PR review

#2083 React Storybook Inputs
  package-lock.json
  react/.storybook/presets.js
  react/.storybook/webpack.config.js
  react/package-lock.json
  react/package.json
  spark/base/inputs/react/SprkDatePickerInput/SprkDatePickerInput.js
  spark/base/inputs/react/SprkDatePickerInput/SprkDatePickerInput.test.js
  spark/base/inputs/react/SprkErrorContainer/SprkErrorContainer.js
  spark/base/inputs/react/SprkErrorContainer/SprkErrorContainer.test.js
  spark/base/inputs/react/SprkRevealInput/SprkRevealInput.js
  spark/base/inputs/react/SprkRevealInput/SprkRevealInput.test.js
  spark/base/inputs/react/SprkSelectionInput.js
  spark/base/inputs/react/SprkSelectionInput.test.js
  spark/base/inputs/react/SprkSelectionInput/SprkSelectionInput.js
  spark/base/inputs/react/SprkSelectionInput/SprkSelectionInput.test.js
  spark/base/inputs/react/SprkTextInput.js
  spark/base/inputs/react/SprkTextInput.stories.js
  spark/base/inputs/react/SprkTextInput/SprkTextInput.js
  spark/base/inputs/react/SprkTextInput/SprkTextInput.test.js
  spark/base/inputs/react/components/SprkInputIconCheck.js
  spark/base/inputs/react/components/SprkInputIconCheck.test.js
  spark/base/inputs/react/components/SprkInputLabel.js
  spark/base/inputs/react/components/SprkLabelLocationCheck.js
  spark/base/inputs/react/components/SprkTextareaCheck.js
  spark/base/inputs/styles/_datepicker.scss
  spark/base/inputs/styles/_input-container.scss
  spark/base/inputs/styles/_labels.scss
  spark/base/inputs/styles/_select.scss
  spark/base/inputs/styles/_svg-icon-input.scss
  spark/base/inputs/styles/_text-input.scss
  spark/base/inputs/styles/_textarea.scss
  spark/manifests/spark-react/package.json
  spark/manifests/spark/_spark.scss
Labels: status: PR review

#2074 Clarifying documentation on masthead component.
  src/patterns/components/masthead/default.hbs
Labels: status: PR review

#2076 React components
  spark/components/accordions/react/SprkAccordion.js
  spark/components/accordions/react/SprkAccordion.stories.js
  spark/components/accordions/react/SprkAccordion.test.js
  spark/components/accordions/react/components/SprkAccordionItem/SprkAccordionItem.js
  spark/components/accordions/react/components/SprkAccordionItem/SprkAccordionItem.test.js
  spark/components/masthead/react/SprkMasthead.js
  spark/components/masthead/react/SprkMasthead.stories.js
  spark/components/masthead/react/SprkMasthead.test.js
  spark/components/masthead/react/components/SprkMastheadAccordion/SprkMastheadAccordion.js
  spark/components/masthead/react/components/SprkMastheadAccordion/SprkMastheadAccordion.test.js
  spark/components/masthead/react/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.js
  spark/components/masthead/react/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.test.js
  spark/components/masthead/react/components/SprkMastheadBigNav/SprkMastheadBigNav.js
  spark/components/masthead/react/components/SprkMastheadBigNav/SprkMastheadBigNav.test.js
  spark/components/masthead/react/components/SprkMastheadDropdown/SprkMastheadDropdown.js
  spark/components/masthead/react/components/SprkMastheadDropdown/SprkMastheadDropdown.test.js
  spark/components/masthead/react/components/SprkMastheadLittleNav/SprkMastheadLittleNav.js
  spark/components/masthead/react/components/SprkMastheadLittleNav/SprkMastheadLittleNav.test.js
  spark/components/masthead/react/components/SprkMastheadMenuIcon/SprkMastheadMenuIcon.js
  spark/components/masthead/react/components/SprkMastheadMenuIcon/SprkMastheadMenuIcon.test.js
  spark/components/masthead/react/components/SprkMastheadNarrowNav/SprkMastheadNarrowNav.js
  spark/components/masthead/react/components/SprkMastheadNarrowNav/SprkMastheadNarrowNav.test.js
  spark/components/masthead/react/components/SprkMastheadSelector/SprkMastheadSelector.js
  spark/components/masthead/react/components/SprkMastheadSelector/SprkMastheadSelector.test.js
  spark/manifests/spark/spark-exports.js
  spark/utilities/helpers/vanilla/isElementVisible.js
  spark/utilities/helpers/vanilla/isElementVisible.tests.js
  spark/utilities/helpers/vanilla/scrollYDirection.js
  spark/utilities/helpers/vanilla/scrollYDirection.tests.js
Labels: status: PR review

#2091 address z-index issue for monetary input
  src/angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
  src/angular/src/app/spark-docs/masthead-docs/masthead-docs.component.ts
Labels: status: PR review

#2127 ready spark versions for publish
  packages/spark/package.json
  src/angular/projects/spark-angular/package.json
  src/react/projects/spark-react/package.json
Labels: status: PR review

#2132 uses visible state of alert instead of class to hide dismissed alerts
  src/angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.component.spec.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.component.ts
Labels: status: PR review

#2133 removes usage of vanilla js from stepper
  src/angular/projects/spark-angular/src/lib/components/sprk-stepper/sprk-stepper.component.ts
Labels: status: PR review

#2134 removes usage of vanilla js from carousel
  src/angular/projects/spark-angular/src/lib/components/sprk-carousel/sprk-carousel.component.ts
Labels: status: PR review

#2135 removes vanilla js usage from angular masthead
  src/angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
Labels: status: PR review

#2136 removes vanilla js usage from angular tabbed nav
  src/angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.component.ts
Labels: status: PR review

#2140 Load Icons into Storybook - React
  react/.storybook/preview-body.html
  react/.storybook/preview-head.html
Labels: status: PR review

#2146 Tables - Vanilla
  spark/base/tables/vanilla/tables.stories.js
Labels: status: PR review

#2148 Fix react proptype descriptions and update comment syntax
  package-lock.json
  package.json
  react/.storybook/webpack.config.js
  spark/base/inputs/react/SprkTextInput.stories.js
  spark/base/links/react/SprkLink.stories.js
  spark/base/lists/react/SprkList.stories.js
  spark/base/tables/react/SprkTable.stories.js
  spark/components/accordions/react/SprkAccordion.js
  spark/components/accordions/react/SprkAccordion.stories.js
  spark/components/accordions/vanilla/accordions.stories.js
  spark/components/alerts/react/SprkAlert.js
  spark/components/alerts/react/SprkAlert.stories.js
  spark/components/alerts/vanilla/alerts.stories.js
  spark/components/awards/react/SprkAward.js
  spark/components/awards/react/SprkAward.stories.js
  spark/components/buttons/react/SprkButton.js
  spark/components/buttons/react/SprkButton.stories.js
  spark/components/card/react/SprkCard.stories.js
  spark/components/dictionary/react/SprkDictionary.stories.js
  spark/components/dividers/react/SprkDivider.stories.js
  spark/components/dropdown/react/SprkDropdown.js
  spark/components/dropdown/react/SprkDropdown.stories.js
  spark/components/footer/react/SprkFooter.stories.js
  spark/components/footer/react/SprkFooter.test.js
  spark/components/highlight-board/react/SprkHighlightBoard.js
  spark/components/highlight-board/react/SprkHighlightBoard.stories.js
  spark/components/icons/react/SprkIcon.js
  spark/components/icons/react/SprkIcon.stories.js
  spark/components/masthead/react/SprkMasthead.js
  spark/components/masthead/react/SprkMasthead.stories.js
  spark/components/modals/react/SprkModal.js
  spark/components/modals/react/SprkModal.stories.js
  spark/components/pagination/react/SprkPagination.js
  spark/components/pagination/react/SprkPagination.stories.js
  spark/components/promo/react/SprkPromo.js
  spark/components/promo/react/SprkPromo.stories.js
  spark/components/stepper/react/SprkStepper.js
  spark/components/stepper/react/SprkStepper.stories.js
  spark/components/tabs/react/SprkTabs.js
  spark/components/tabs/react/SprkTabs.stories.js
  spark/components/tabs/react/SprkTabs.test.js
  spark/components/tabs/react/components/SprkTabsButton.test.js
  spark/components/tabs/react/components/SprkTabsPanel.test.js
  spark/components/toggle/react/SprkToggle.js
  spark/components/toggle/react/SprkToggle.stories.js
  spark/manifests/spark-react/package-lock.json
  spark/manifests/spark-react/package.json
  spark/manifests/spark/package-lock.json
  spark/manifests/spark/package.json
  spark/objects/stack/react/SprkStack.js
  spark/objects/stack/react/SprkStack.stories.js
  vanilla/.storybook/config.js
  vanilla/package-lock.json
Labels: status: PR review

#2145 Add vanilla divider storybook
  spark/components/dividers/react/SprkDivider.stories.js
  spark/components/dividers/vanilla/dividers.stories.js
Labels: js: vanilla, status: PR review

#2147 Icons - Vanilla
  spark/components/icons/vanilla/icons.stories.js
  vanilla/.storybook/preview-body.html
  vanilla/.storybook/preview-head.html
Labels: status: PR review

#2152 Storybook vanilla alert
  spark/components/alerts/vanilla/alerts.stories.js
Labels: js: vanilla, status: PR review

#2153 Icon Stories for React
  spark/components/icons/react/SprkIcon.stories.js
Labels: status: PR review

#2157 adds method for writing ng stories (component or directive
  angular/.storybook/config.js
  angular/.storybook/webpack.config.js
  angular/package-lock.json
  spark/components/alerts/angular/sprk-alert.stories.ts
  spark/components/buttons/angular/sprk-button.stories.ts
Labels: status: PR review

#2143 Add footer default story
  spark/components/footer/react/SprkFooter.js
  spark/components/footer/vanilla/footer.stories.js
Labels: js: vanilla, status: PR review

#2151 Fix React Pagination Unit Tests
  spark/components/pagination/react/SprkPagination.test.js
Labels: status: PR review

#2142 Add Vanilla Buttons to Story Book
  spark/components/buttons/vanilla/button.stories.js
Labels: js: vanilla, status: PR review

#2160 Add dropdowns to vanilla SB
  spark/components/dropdown/vanilla/dropdown.stories.js
Labels: status: PR review

#2156 Update accordion story for vanilla
  spark/components/accordions/vanilla/accordions.stories.js
Labels: status: PR review

#2169 Vanilla tabs hb dictionary
  spark/components/dictionary/vanilla/dictionary.stories.js
  spark/components/highlight-board/vanilla/highlight-board.stories.js
  spark/components/tabs/vanilla/tabs.stories.js
  vanilla/.storybook/preview-head.html
  vanilla/static/images/desktop--flush.jpg
  vanilla/static/images/desktop.jpg
Labels: status: PR review

#2167 Add Input stories to SB html
  spark/base/inputs/styles/_select.scss
  spark/base/inputs/vanilla/datePicker.js
  spark/base/inputs/vanilla/inputs.stories.js
  spark/objects/horizontal-list/styles/_horizontal-list.scss
Labels: status: PR review

#2168 Storybook vanilla modal
  spark/components/modals/react/SprkModal.stories.js
  spark/components/modals/vanilla/modals.stories.js
  vanilla/.storybook/config.js
Labels: status: PR review

#2182 add toggle for vanilla sb
  spark/components/accordions/styles/_accordions.scss
  spark/components/accordions/vanilla/accordions.stories.js
  spark/components/toggle/vanilla/toggle.stories.js
Labels: status: PR review

#2163 Add component stories for vanilla
  spark/components/awards/react/SprkAward.stories.js
  spark/components/awards/react/SprkAward.test.js
  spark/components/awards/vanilla/awards.stories.js
  spark/components/footer/react/SprkFooter.test.js
  spark/components/footer/react/components/SprkFooterAwards/SprkFooterAwards.test.js
  spark/components/footer/react/components/SprkFooterGlobalSection/SprkFooterGlobalSection.test.js
  spark/components/highlight-board/react/SprkHighlightBoard.stories.js
  spark/components/pagination/vanilla/pagination.stories.js
  spark/components/promo/react/SprkPromo.stories.js
  spark/components/promo/vanilla/promo.stories.js
  storybook-spark-theme.js
  vanilla/static/images/desktop--flush.jpg
  vanilla/static/images/desktop.jpg
Labels: status: PR review

#2162 Add different link stories
  spark/base/links/vanilla/links.stories.js
Labels: js: vanilla, status: PR review

#2188 Add cards to html SB
  spark/components/card/vanilla/card.stories.js
Labels: status: PR review

#2190 Add accordions/alerts to angular SB and update SB
  angular/.storybook/config.js
  angular/package-lock.json
  angular/package.json
  angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.stories.ts
  angular/src/polyfills.ts
  angular/tsconfig.json
Labels: status: PR review

#2196 Add Angular components - Divider, Dropdown
  angular/projects/spark-angular/src/lib/components/sprk-divider/sprk-divider.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
Labels: status: PR review

#2199 add spinning to sprk-button.directive
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.stories.ts
Labels: status: PR review

#2202 add angular button stories & update SB
  angular/package-lock.json
  angular/package.json
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.stories.ts
Labels: status: PR review

#2200 Add Icons to Angular Storybook
  angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.stories.ts
Labels: status: PR review

#2213 remove choiceMade input from examples
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
Labels: status: PR review

#2211 add toggle component story to angular storybook
  angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.stories.ts
Labels: status: PR review

#2194 Add Stepper to Vanilla Storybook
  spark/components/stepper/vanilla/stepper.js
  spark/components/stepper/vanilla/stepper.stories.js
  spark/components/stepper/vanilla/stepper.tests.js
Labels: status: PR review

#2170 Masthead vanilla sb
  spark/components/masthead/vanilla/masthead.js
  spark/components/masthead/vanilla/masthead.stories.js
  spark/utilities/helpers/vanilla/isElementVisible.js
  vanilla/.storybook/config.js
Labels: js: vanilla, status: PR review

#2201 Add Angular SB containers individually instead of globally
  angular/.storybook/config.js
  angular/.storybook/helpers/storyWrapper.js
  angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-divider/sprk-divider.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.stories.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.stories.ts
Labels: js: angular, status: PR review

#2215 Angular Components Storybook
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-link/sprk-link.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-table/sprk-table.stories.ts
Labels: status: PR review

#2219 Gatsby updated layout
  gatsby-browser.js
  gatsby-config.js
  gatsby-ssr.js
  package-lock.json
  package.json
  src/components/ContentWrapper.js
  src/components/ContextMenu.js
  src/components/ContextSubMenu.js
  src/components/Footer.js
  src/components/Header.js
  src/components/InstallingSparkDocsMenu.js
  src/components/Menu.js
  src/components/PrinciplesDocsMenu.js
  src/components/UsingSparkDocsMenu.js
  src/components/layouts/HomepageLayout.js
  src/components/layouts/InstallingSparkLayout.js
  src/components/layouts/Layout.js
  src/components/layouts/PrinciplesLayout.js
  src/components/layouts/UsingSparkLayout.js
  src/components/site-structure/Header.js
  src/components/site-structure/Layout.js
  src/components/site-structure/LinkList.js
  src/components/site-structure/Menu.js
  src/pages/404.js
  src/pages/index.js
  src/scss/components/_component-index.scss
  src/scss/components/_context-menu.scss
  src/scss/components/_footer.scss
  src/scss/components/_header.scss
  src/scss/components/_layout.scss
  src/scss/components/_menu.scss
  src/scss/main.scss
  src/scss/site-structure/_content.scss
  src/scss/site-structure/_header.scss
  src/scss/site-structure/_layout.scss
  src/scss/site-structure/_menu.scss
Labels: status: PR review

#2237 fix spark-react test errors by adding react component proptype
  react/src/base/links/SprkLink.js
  react/src/components/card/components/SprkCardTeaser/SprkCardTeaser.js
  react/src/components/masthead/SprkMasthead.js
Labels: status: PR review

#2228 Angular Stories
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion-item/sprk-masthead-accordion-item.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion-item/sprk-masthead-accordion-item.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion/sprk-masthead-accordion.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion/sprk-masthead-accordion.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.stories.ts
  react/src/components/modals/SprkModal.stories.js
Labels: status: PR review

#2241 remove actions from accordions, add missing dep for tests, updated np…
  react/.npmignore
  react/package-lock.json
  react/package.json
  react/src/components/accordions/SprkAccordion.stories.js
  react/src/components/toggle/SprkToggle.stories.js
Labels: status: PR review

#2242 Angular - Tabbed Navigation & Award
  angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-link/sprk-link.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-table/sprk-table.stories.ts
Labels: status: PR review

#2216 Angular Inputs for Storybook
  angular/projects/spark-angular/src/lib/components/inputs/sprk-input.stories.ts
  react/src/base/inputs/SprkInput.stories.js
Labels: Component: Inputs, js: angular, js: react, status: PR review

#2240 Promo angular sb
  angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.stories.ts
  react/src/base/inputs/SprkInput.stories.js
Labels: Component: Promo, js: angular, status: PR review

#2218 add automatically generated sass variable documentation page to NDS
  .gitignore
  gatsby-config.js
  html/settings/_colors.scss
  html/settings/_settings.scss
  package-lock.json
  package.json
  src/components/SassVarTable.js
  src/data/.gitkeep
  src/pages/using-spark/foundations/sass-variables.mdx
  src/scss/_spark-theme.scss
Labels: status: PR review

#2243 Angular card dictionary
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.stories.ts
Labels: status: PR review

#2256 Load fonts into Storybook - HTML, Angular, React
  angular/.storybook/config.js
  angular/.storybook/preview-head.html
  html/.storybook/config.js
  html/.storybook/preview-head.html
  react/.storybook/config.js
  react/.storybook/preview-head.html
  storybook-theming/font-loader.scss
  storybook-theming/icon-loader.js
  storybook-theming/storybook-spark-theme.js
Labels: status: PR review

#2257 Vanilla - Add the decorator individually for every component
  html/.storybook/config.js
  html/base/inputs.stories.js
  html/base/links.stories.js
  html/base/tables.stories.js
  html/components/accordions.stories.js
  html/components/alerts.stories.js
  html/components/awards.stories.js
  html/components/button.stories.js
  html/components/card.stories.js
  html/components/dictionary.stories.js
  html/components/dividers.stories.js
  html/components/dropdown.stories.js
  html/components/footer.stories.js
  html/components/highlight-board.stories.js
  html/components/icons.stories.js
  html/components/masthead.stories.js
  html/components/modals.stories.js
  html/components/pagination.stories.js
  html/components/promo.stories.js
  html/components/stepper.stories.js
  html/components/tabs.stories.js
  html/components/toggle.stories.js
Labels: js: vanilla, status: PR review

#2265 Sync Frameworks Naming
  angular/.storybook/config.js
  angular/projects/spark-angular/src/lib/components/inputs/sprk-input.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-link/sprk-link.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.stories.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.stories.ts
  html/.storybook/config.js
  html/base/inputs.stories.js
  html/base/links.stories.js
  html/base/tables.stories.js
  html/components/alerts.stories.js
  html/components/awards.stories.js
  html/components/button.stories.js
  html/components/dividers.stories.js
  html/components/modals.stories.js
  html/components/stepper.stories.js
  react/.storybook/config.js
  react/src/base/inputs/SprkInput.stories.js
  react/src/base/links/SprkLink.stories.js
  react/src/base/lists/SprkList.stories.js
  react/src/base/tables/SprkTable.stories.js
  react/src/components/alerts/SprkAlert.stories.js
  react/src/components/buttons/SprkButton.stories.js
  react/src/components/card/SprkCard.stories.js
  react/src/components/dropdown/SprkDropdown.stories.js
  react/src/components/pagination/SprkPagination.stories.js
  react/src/components/stepper/SprkStepper.stories.js
Labels: status: PR review

#2258 Move old "spark extras" vars to settings file.
  html/components/_card.scss
  html/components/_carousel.scss
  html/components/_dictionary.scss
  html/components/_dropdown.scss
  html/components/_highlight-board.scss
  html/settings/_settings.scss
Labels: status: PR review

#2263 adding components for markdown renderer
  gatsby-config.js
  package-lock.json
  package.json
  src/components/ContextMenu.js
  src/components/Header.js
  src/components/layouts/Layout.js
  src/components/markdown-render/a.js
  src/components/markdown-render/h1.js
  src/components/markdown-render/h2.js
  src/components/markdown-render/h3.js
  src/components/markdown-render/inlineCode.js
  src/components/markdown-render/li.js
  src/components/markdown-render/p.js
  src/components/markdown-render/ul.js
  src/pages/installing-spark/setting-up-your-environment.mdx
  src/pages/using-spark/foundations/sass-variables.mdx
  src/scss/components/_code.scss
  src/scss/components/_footer.scss
  src/scss/components/_layout.scss
  src/scss/main.scss
Labels: status: PR review

#2260 Add highlight board components
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.stories.ts
Labels: Component: Highlight Board, js: angular, status: PR review
