Repository sparkdesignsystem/spark-design-system, pull requests merged in 2019-12, with the labels that each got.

#2377 [React & Angular SB] Add awesome Subcomponent Prop Tables and prop object/array shape documentation!
  angular/package-lock.json
  angular/package.json
  angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-ordered-list/sprk-list.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-stack/sprk-stack.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-table/sprk-table.stories.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.stories.ts
  react/package-lock.json
  react/package.json
  react/src/base/lists/SprkList.stories.js
  react/src/components/accordions/SprkAccordion.stories.js
  react/src/components/accordions/components/SprkAccordionItem/SprkAccordionItem.js
  react/src/components/card/SprkCard.stories.js
  react/src/components/card/components/SprkCardHighlightedHeader/SprkCardHighlightedHeader.js
  react/src/components/card/components/SprkCardTeaser/SprkCardTeaser.js
  react/src/components/footer/SprkFooter.stories.js
  react/src/components/masthead/SprkMasthead.stories.js
  react/src/components/masthead/components/SprkMastheadAccordion/SprkMastheadAccordion.js
  react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.js
  react/src/components/masthead/components/SprkMastheadBigNav/SprkMastheadBigNav.js
  react/src/components/masthead/components/SprkMastheadDropdown/SprkMastheadDropdown.js
  react/src/components/masthead/components/SprkMastheadMenuIcon/SprkMastheadMenuIcon.js
  react/src/components/masthead/components/SprkMastheadNarrowNav/SprkMastheadNarrowNav.js
  react/src/components/modals/SprkModal.stories.js
  react/src/components/stepper/SprkStepper.stories.js
  react/src/components/stepper/components/SprkStepperSlider/SprkStepperSlider.js
  react/src/components/tabs/SprkTabs.stories.js
  react/src/components/tabs/components/SprkTabsButton/SprkTabsButton.js
  react/src/components/tabs/components/SprkTabsPanel/SprkTabsPanel.js
  react/src/objects/stack/SprkStack.stories.js
  react/src/objects/stack/components/SprkStackItem/SprkStackItem.js
Labels: Carry Over, status: PR review

#2396 2387 validation updates
  angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.stories.ts
  html/base/inputs/Checkbox.stories.js
  html/base/inputs/Date.stories.js
  html/base/inputs/DatePicker.stories.js
  html/base/inputs/HelperText.stories.js
  html/base/inputs/HugeSelect.stories.js
  html/base/inputs/HugeText.stories.js
  html/base/inputs/Monetary.stories.js
  html/base/inputs/Password.stories.js
  html/base/inputs/Percentage.stories.js
  html/base/inputs/Phone.stories.js
  html/base/inputs/Radio.stories.js
  html/base/inputs/SSN.stories.js
  html/base/inputs/Search.stories.js
  html/base/inputs/Select.stories.js
  html/base/inputs/Text.stories.js
  html/base/inputs/Textarea.stories.js
Labels: status: PR review

#2388 Add interfaces to spark-angular package
  angular/package-lock.json
  angular/package.json
  angular/projects/spark-angular/src/lib/components/inputs/DatePicker.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.interfaces.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.interfaces.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.interfaces.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.component.spec.ts
  html/base/_tables.scss
  html/components/_buttons.scss
  html/components/_dropdown.scss
  html/components/_masthead.scss
Labels: status: PR review

#2411 2409 validation updates react
  react/src/base/inputs/Checkbox.stories.js
  react/src/base/inputs/Date.stories.js
  react/src/base/inputs/DatePicker.stories.js
  react/src/base/inputs/HelperText.stories.js
  react/src/base/inputs/HugeSelect.stories.js
  react/src/base/inputs/HugeText.stories.js
  react/src/base/inputs/Monetary.stories.js
  react/src/base/inputs/Password.stories.js
  react/src/base/inputs/Percentage.stories.js
  react/src/base/inputs/Phone.stories.js
  react/src/base/inputs/Radio.stories.js
  react/src/base/inputs/SSN.stories.js
  react/src/base/inputs/Search.stories.js
  react/src/base/inputs/Select.stories.js
  react/src/base/inputs/Text.stories.js
  react/src/base/inputs/Textarea.stories.js
  react/src/components/buttons/SprkButton.stories.js
Labels: status: PR review

#2422 2410 validation updates angular
  angular/projects/spark-angular/src/lib/components/inputs/Checkbox.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Date.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/DatePicker.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/HelperText.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/HugeSelect.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/HugeText.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Monetary.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Password.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Percentage.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Phone.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Radio.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/SSN.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Search.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Select.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Text.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Textarea.stories.ts
Labels: status: PR review

#2423 add scss comments for accordion && alert
  html/components/_accordions.scss
  html/components/_alerts.scss
Labels: status: PR review

#2420 add sassdoc comments for lists, masthead and modal
  html/base/_lists.scss
  html/components/_buttons.scss
  html/components/_masthead.scss
  html/components/_modals.scss
Labels: status: PR review

#2426 add sassdoc comments for tabs and table
  angular/package-lock.json
  angular/package.json
  html/base/_tables.scss
  html/components/_tabs.scss
Labels: status: PR review

#2425 add sassdoc comments for box, flag, and stack
  html/objects/_box.scss
  html/objects/_flag.scss
  html/objects/_stack.scss
Labels: status: PR review

#2391 Add correct aria attributes to dropdown
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
  html/components/dropdown.stories.js
  react/src/components/dropdown/SprkDropdown.js
  react/src/components/dropdown/SprkDropdown.stories.js
  react/src/components/dropdown/SprkDropdown.test.js
Labels: Component: Dropdown, scope: all pkgs, status: PR review

#2477 remove hr divider stories in react and html
  html/components/divider.stories.js
  react/src/components/dividers/SprkDivider.stories.js
Labels: status: PR review

#2476 update buttons to button in angular primary
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.stories.ts
Labels: status: PR review

#2475 add sprk-u-JavaScript to tabs decorator
  html/components/tabs.stories.js
Labels: status: PR review

#2461 Add sassdoc comments to button, card, dictionary and dropdown
  html/components/_buttons.scss
  html/components/_card.scss
  html/components/_dictionary.scss
  html/components/_dropdown.scss
Labels: status: PR review

#2433 Add sass comments for pagination, promo and stepper
  html/components/_pagination.scss
  html/components/_promo.scss
  html/components/_stepper.scss
  html/package-lock.json
  html/package.json
Labels: status: PR review

#2480 Remove long pagination stories
  angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.stories.ts
  html/components/pagination.stories.js
  react/src/components/pagination/SprkPagination.stories.js
Labels: status: PR review

#2479 add drizzle alert banner about new docs site
  src/pages/index.hbs
Labels: status: PR review

#2482 Add component name to unit tests - React
  react/src/base/inputs/SprkDatePickerInput/SprkDatePickerInput.test.js
  react/src/base/inputs/SprkErrorContainer/SprkErrorContainer.test.js
  react/src/base/inputs/SprkRevealInput/SprkRevealInput.test.js
  react/src/base/inputs/SprkSelectionInput/SprkSelectionInput.test.js
  react/src/base/inputs/SprkTextInput/SprkTextInput.test.js
  react/src/base/inputs/components/SprkInputIconCheck/SprkInputIconCheck.test.js
  react/src/base/links/SprkLink.test.js
  react/src/base/lists/SprkList.test.js
  react/src/base/lists/SprkListItem.test.js
  react/src/base/tables/SprkTable.test.js
  react/src/components/accordions/SprkAccordion.test.js
  react/src/components/accordions/components/SprkAccordionItem/SprkAccordionItem.test.js
  react/src/components/alerts/SprkAlert.test.js
  react/src/components/awards/SprkAward.test.js
  react/src/components/buttons/SprkButton.test.js
  react/src/components/card/SprkCard.test.js
  react/src/components/card/components/SprkCardHighlightedHeader/SprkCardHighlightedHeader.test.js
  react/src/components/card/components/SprkCardTeaser/SprkCardTeaser.test.js
  react/src/components/dictionary/SprkDictionary.test.js
  react/src/components/dividers/SprkDivider.test.js
  react/src/components/dropdown/SprkDropdown.test.js
  react/src/components/footer/SprkFooter.test.js
  react/src/components/footer/components/SprkFooterAwards/SprkFooterAwards.test.js
  react/src/components/footer/components/SprkFooterConnectIcons/SprkFooterConnectIcons.test.js
  react/src/components/footer/components/SprkFooterGlobalSection/SprkFooterGlobalSection.test.js
  react/src/components/highlight-board/SprkHighlightBoard.test.js
  react/src/components/icons/SprkIcon.test.js
  react/src/components/masthead/SprkMasthead.test.js
  react/src/components/masthead/components/SprkMastheadAccordion/SprkMastheadAccordion.test.js
  react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.test.js
  react/src/components/masthead/components/SprkMastheadBigNav/SprkMastheadBigNav.test.js
  react/src/components/masthead/components/SprkMastheadDropdown/SprkMastheadDropdown.test.js
  react/src/components/masthead/components/SprkMastheadLittleNav/SprkMastheadLittleNav.test.js
  react/src/components/masthead/components/SprkMastheadMenuIcon/SprkMastheadMenuIcon.test.js
  react/src/components/masthead/components/SprkMastheadNarrowNav/SprkMastheadNarrowNav.test.js
  react/src/components/masthead/components/SprkMastheadSelector/SprkMastheadSelector.test.js
  react/src/components/modals/CloseButton.test.js
  react/src/components/modals/Mask.test.js
  react/src/components/modals/ModalFooter.test.js
  react/src/components/modals/SprkModal.test.js
  react/src/components/pagination/SprkPagination.test.js
  react/src/components/promo/SprkPromo.test.js
  react/src/components/spinners/SprkSpinner.test.js
  react/src/components/stepper/SprkStepper.test.js
  react/src/components/stepper/components/SprkStepperSlider/SprkStepperSlider.test.js
  react/src/components/stepper/components/SprkStepperStep/SprkStepperStep.test.js
  react/src/components/tabs/SprkTabs.test.js
  react/src/components/tabs/components/SprkTabsButton/SprkTabsButton.test.js
  react/src/components/tabs/components/SprkTabsPanel/SprkTabsPanel.test.js
  react/src/components/toggle/SprkToggle.test.js
  react/src/objects/stack/SprkStack.test.js
  react/src/objects/stack/components/SprkStackItem/SprkStackItem.test.js
Labels: status: PR review

#2486 add 'as link element' story for html button
  html/components/button.stories.js
Labels: status: PR review

#2434 add sassdoc comments for link && input
  html/base/_links.scss
  html/base/inputs/_input-container.scss
  html/base/inputs/_labels.scss
  html/base/inputs/_select.scss
  html/base/inputs/_svg-icon-input.scss
  html/base/inputs/_text-icon-input.scss
  html/base/inputs/_text-input.scss
Labels: status: PR review

#2484 Prevent Dropdown from navigating away - Vanilla
  html/components/dropdown.js
  html/components/masthead.js
Labels: status: PR review

#2483 add auto-generated Color page to Gatsby site!
  angular/package-lock.json
  angular/package.json
  html/package-lock.json
  html/package.json
  html/settings/_colors.scss
  package-lock.json
  package.json
  react/.storybook/config.js
  react/package-lock.json
  react/package.json
  src/components/ColorSwatch.js
  src/components/ColorSwatchGrid.js
  src/components/Header.js
  src/components/markdown-render/inlineCode.js
  src/images/colors-on-dark.png
  src/images/colors-on-dark@2x.png
  src/images/colors-on-dark@3x.png
  src/images/colors-on-light.png
  src/images/colors-on-light@2x.png
  src/images/colors-on-light@3x.png
  src/images/do-not-mix-colors.png
  src/images/do-not-overuse-red.png
  src/images/do-not-use-accents-in-large-amounts.png
  src/images/do-not-use-dark-bgs-for-text.png
  src/images/do-not-use-gradients.png
  src/images/legibility.png
  src/pages/using-spark/foundations/color.mdx
  src/scss/_settings.scss
  src/scss/main.scss
  src/scss/objects/_color-swatch-grid.scss
Labels: status: PR review

#2493 Add Alert docs to Gatsby site
  src/pages/using-spark/components/alert.mdx
Labels: status: PR review
