Repository sparkdesignsystem/spark-design-system, pull requests merged in 2019-08, with the labels that each got.

#1651 1602 update side navigation component
  .gitignore
  LICENSE copy
  README copy.md
  gatsby-config.js
  gatsby-node.js
  package.json
  react/package.json
  src/components/ComponentDocList.js
  src/components/ComponentDocSample.js
  src/components/ComponentIndex.js
  src/components/content-iframe.js
  src/components/context/APIDocumentationMenu.js
  src/components/context/GuidesMenu.js
  src/components/header.js
  src/components/image.js
  src/components/layout.js
  src/components/site-logo.js
  src/components/site-navigation.js
  src/components/site-structure/Footer.js
  src/components/site-structure/Header.js
  src/components/site-structure/Layout.js
  src/components/site-structure/Menu.js
  src/images/gatsby-astronaut.png
  src/images/gatsby-icon.png
  src/pages/404.js
  src/pages/apidocumentation.js
  src/pages/gettingstarted.mdx
  src/pages/index.js
  src/scss/components/_component-index.scss
  src/scss/components/_header.scss
  src/scss/components/_iframe.scss
  src/scss/components/_layout.scss
  src/scss/components/_navigation.scss
  src/scss/main.scss
  src/scss/site-structure/_content.scss
  src/scss/site-structure/_footer.scss
  src/scss/site-structure/_header.scss
  src/scss/site-structure/_layout.scss
  src/scss/site-structure/_menu.scss
  src/templates/ComponentPage.js
  src/templates/DocPage.js
  src/templates/FundamentalPage.js
Labels: status: PR review

#1653 Huge input react
  src/react/projects/spark-react/src/SprkInput/SprkTextInput/SprkTextInput.js
  src/react/projects/spark-react/src/SprkInput/SprkTextInput/SprkTextInput.test.js
  src/react/projects/spark-react/src/SprkInput/SprkTextInput/components/SprkInputIconCheck.js
  src/react/projects/spark-react/src/SprkInput/SprkTextInput/components/SprkInputLabel.js
  src/react/projects/spark-react/src/SprkInput/SprkTextInput/components/SprkLabelLocationCheck.js
  src/react/projects/spark-react/src/SprkInput/SprkTextInput/components/SprkTextareaCheck.js
  src/react/src/routes/SprkInputDocs/SprkTextInputDocs/SprkTextInputDocs.js
Labels: js: react, status: PR review

#1669 Update angular to allow individual module imports
  src/angular/projects/spark-angular/src/public_api.ts
Labels: status: PR review

#1693 Allow <ng-content> to be passed through for sprk-selection-container and sprk-selection-item-container
  package-lock.json
  src/angular/package-lock.json
  src/angular/projects/spark-angular/package.json
  src/angular/projects/spark-angular/src/lib/components/inputs/sprk-selection-container/sprk-selection-container.component.ts
  src/angular/projects/spark-angular/src/lib/components/inputs/sprk-selection-item-container/sprk-selection-item-container.component.ts
  src/angular/src/app/spark-docs/input-docs/input-docs.component.ts
  src/angular/src/styles.scss
Labels: status: PR review

#1691 Fix angular animations bug with toggles/accordions
  package-lock.json
  packages/spark/utilities/_utilities.scss
  src/angular/package-lock.json
  src/angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.spec.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion-item/sprk-masthead-accordion-item.component.spec.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion-item/sprk-masthead-accordion-item.component.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle-animations.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.spec.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.ts
  src/angular/projects/spark-angular/src/public_api.ts
  src/patterns/utilities/multi-property/typography.hbs
Labels: status: PR review

#1684 IE 11 - ordered lists not numbering - list refactor
  src/angular/projects/spark-angular/src/lib/components/sprk-list-item/sprk-list-item.component.spec.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-list-item/sprk-list-item.component.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-ordered-list/sprk-ordered-list.component.spec.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-ordered-list/sprk-ordered-list.component.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.component.spec.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.component.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.module.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-unordered-list/sprk-unordered-list.component.spec.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-unordered-list/sprk-unordered-list.component.ts
Labels: status: DO NOT MERGE

#1698 Alias Typos and Component Exports
  packages/spark/settings/_settings.scss
  src/angular/projects/spark-angular/src/public_api.ts
Labels: status: PR review

#1701 update list docs code example
  src/patterns/components/lists/angular/code/list.hbs
Labels: status: PR review

#1688 Angular Pagination Refactor
  src/angular/projects/spark-angular/src/lib/components/sprk-ordered-list/sprk-ordered-list.component.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.component.spec.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.component.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-unordered-list/sprk-unordered-list.component.ts
  src/angular/src/app/spark-docs/pagination-docs/pagination-docs.component.ts
  src/patterns/components/pagination/angular/code/default.hbs
  src/patterns/components/pagination/angular/code/long.hbs
  src/patterns/components/pagination/angular/code/pager.hbs
  src/patterns/components/pagination/angular/docs/default.hbs
  src/patterns/components/pagination/angular/docs/long.hbs
  src/patterns/components/pagination/angular/info/default.hbs
  src/patterns/components/pagination/collection.yaml
  src/patterns/components/pagination/default.hbs
  src/patterns/components/pagination/long.hbs
Labels: js: angular, status: DO NOT MERGE, status: PR review

#1718 Update Staging with Master's changes
  packages/spark/components/masthead.js
  packages/spark/package-lock.json
  packages/spark/package.json
Labels: status: PR review

#1711 Ready release version numbers
  packages/spark/package.json
  src/angular/projects/spark-angular/package.json
  src/react/projects/spark-react/package.json
Labels: status: PR review

#1715 add polyfill for CustomEvent, use feature detect for IE11 in vanilla …
  packages/spark/base/datePicker.js
  packages/spark/spark-polyfills.js
  packages/spark/utilities/polyfills/CustomEvent.js
  packages/spark/utilities/polyfills/ObjectAssign.js
Labels: status: PR review

#1723 Masthead Scroll Doc Fix
  src/assets/drizzle/styles/utility/_toolkit-overrides.scss
  src/assets/toolkit/styles/toolkit.scss
Labels: status: PR review

#1722 Update react dev app peerDeps to new spark versions
  src/react/package.json
Labels: status: PR review
