Repository sparkdesignsystem/spark-design-system, pull requests merged in 2019-09, with the labels that each got.

#1728 Add use case to Angular Pagination test page
  src/angular/src/app/spark-docs/pagination-docs/pagination-docs.component.ts
Labels: status: DO NOT MERGE, status: PR review

#1756 React Masthead Enhanced Scrolling Functionality
  src/patterns/components/masthead/collection.yaml
  src/react/projects/spark-react/src/SprkMasthead/SprkMasthead.js
  src/react/projects/spark-react/src/SprkMasthead/SprkMasthead.test.js
  src/react/src/routes/SprkMastheadDefaultDocs/SprkMastheadDefaultDocs.js
  src/react/src/routes/SprkMastheadExtendedDocs/SprkMastheadExtendedDocs.js
Labels: status: PR review

#1764 testing if theres a value before running the formatter, add a test
  packages/spark/base/monetaryInput.js
  packages/spark/tests/monetaryInput.tests.js
Labels: status: PR review

#1741 update spark-react to get built with webpack, output version for vani…
  gulp/angular/spark-angular/spark-angular.gulpfile.js
  packages/spark/package-lock.json
  packages/spark/package.json
  packages/spark/spark.js
  packages/spark/utilities/versionCheck.js
  packages/spark/webpack.config.js
  src/angular/projects/spark-angular/ng-package.json
  src/angular/projects/spark-angular/package-lock.json
  src/angular/projects/spark-angular/package.json
  src/angular/projects/spark-angular/src/environment/environment.ts
  src/angular/projects/spark-angular/src/lib/spark-angular.module.ts
  src/react/package-lock.json
  src/react/projects/spark-react/package-lock.json
  src/react/projects/spark-react/package.json
  src/react/projects/spark-react/src/Utilities/VersionCheck/VersionCheck.js
  src/react/projects/spark-react/src/index.js
  src/react/projects/spark-react/webpack.config.js
Labels: status: PR review

#1762 updated font sizing
  packages/spark/settings/_settings.scss
  src/patterns/components/inputs/collection.yaml
  src/patterns/fundamentals/typography/body-one.hbs
  src/patterns/fundamentals/typography/body-three.hbs
  src/patterns/fundamentals/typography/body-two.hbs
Labels: status: PR review

#1763 Angular Masthead Enhanced Scrolling Functionality
  src/angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.spec.ts
  src/angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
  src/patterns/components/masthead/collection.yaml
Labels: js: angular, status: PR review

#1892 Percent Vanilla Updates
  packages/spark/base/inputs/_svg-icon-input.scss
  packages/spark/base/inputs/_text-input.scss
  packages/spark/settings/_settings.scss
  src/patterns/components/inputs/collection.yaml
Labels: status: PR review

#1770 Percentage Input (Vanilla)
  packages/spark/base/inputs/_input-container.scss
  packages/spark/base/inputs/_labels.scss
  packages/spark/base/inputs/_svg-icon-input.scss
  packages/spark/base/inputs/_text-icon-input.scss
  packages/spark/base/inputs/_text-input.scss
  packages/spark/settings/_settings.scss
  src/data/icons.yaml
  src/data/inputs.yaml
  src/patterns/components/inputs/collection.yaml
  src/patterns/components/inputs/date-disabled.hbs
  src/patterns/components/inputs/date-error.hbs
  src/patterns/components/inputs/date-state-switcher.hbs
  src/patterns/components/inputs/date.hbs
  src/patterns/components/inputs/datepicker-disabled.hbs
  src/patterns/components/inputs/datepicker-error.hbs
  src/patterns/components/inputs/datepicker-state-switcher.hbs
  src/patterns/components/inputs/datepicker.hbs
  src/patterns/components/inputs/helper-text.hbs
  src/patterns/components/inputs/password-disabled.hbs
  src/patterns/components/inputs/password-error.hbs
  src/patterns/components/inputs/password-state-switcher.hbs
  src/patterns/components/inputs/password.hbs
  src/patterns/components/inputs/percentage-disabled.hbs
  src/patterns/components/inputs/percentage-error.hbs
  src/patterns/components/inputs/percentage-input-state-switcher.hbs
  src/patterns/components/inputs/percentage.hbs
  src/patterns/components/inputs/phone-disabled.hbs
  src/patterns/components/inputs/phone-error.hbs
  src/patterns/components/inputs/phone-state-switcher.hbs
  src/patterns/components/inputs/phone.hbs
Labels: status: DO NOT MERGE, status: PR review

#2043 Angular percentage input
  packages/spark/base/inputs/_svg-icon-input.scss
  src/angular/projects/spark-angular/src/lib/components/inputs/sprk-icon-input-container/sprk-icon-input-container.component.ts
  src/angular/src/app/spark-docs/input-docs/input-docs.component.ts
  src/patterns/components/inputs/angular/code/percentage-disabled.hbs
  src/patterns/components/inputs/angular/code/percentage-error.hbs
  src/patterns/components/inputs/angular/code/percentage.hbs
  src/patterns/components/inputs/percentage-disabled.hbs
  src/patterns/components/inputs/percentage-error.hbs
  src/patterns/components/inputs/percentage.hbs
Labels: js: angular, status: PR review

#1777 Add Huge Select - Angular
  src/angular/projects/spark-angular/src/lib/directives/inputs/sprk-input/sprk-input.directive.spec.ts
  src/angular/projects/spark-angular/src/lib/directives/inputs/sprk-input/sprk-input.directive.ts
  src/angular/src/app/spark-docs/input-docs/input-docs.component.ts
  src/patterns/components/inputs/angular/code/select-huge-disabled.hbs
  src/patterns/components/inputs/angular/code/select-huge-error.hbs
  src/patterns/components/inputs/angular/code/select-huge.hbs
  src/patterns/components/inputs/select-huge-disabled.hbs
  src/patterns/components/inputs/select-huge-error.hbs
  src/patterns/components/inputs/select-huge.hbs
Labels: status: PR review

#1772 REACT: Add Huge Select
  src/patterns/components/inputs/collection.yaml
  src/patterns/components/inputs/react/code/select-huge-disabled.hbs
  src/patterns/components/inputs/react/code/select-huge-error.hbs
  src/patterns/components/inputs/react/code/select-huge.hbs
  src/patterns/components/inputs/react/global-info.hbs
  src/patterns/components/inputs/select-huge-disabled.hbs
  src/patterns/components/inputs/select-huge-error.hbs
  src/patterns/components/inputs/select-huge.hbs
  src/react/projects/spark-react/src/SprkInput/SprkSelectionInput/SprkSelectionInput.js
  src/react/projects/spark-react/src/SprkInput/SprkSelectionInput/SprkSelectionInput.test.js
  src/react/projects/spark-react/src/SprkInput/SprkTextInput/SprkTextInput.js
  src/react/projects/spark-react/src/SprkInput/SprkTextInput/SprkTextInput.test.js
  src/react/projects/spark-react/src/SprkInput/components/SprkInputIconCheck.js
  src/react/projects/spark-react/src/SprkInput/components/SprkInputLabel.js
  src/react/projects/spark-react/src/SprkInput/components/SprkLabelLocationCheck.js
  src/react/projects/spark-react/src/SprkInput/components/SprkTextareaCheck.js
  src/react/src/routes/SprkInputDocs/SprkSelectionInputDocs/SprkSelectionInputDocs.js
  src/react/src/routes/SprkInputDocs/SprkTextInputDocs/SprkTextInputDocs.js
  src/react/src/routes/SprkMastheadExtendedDocs/SprkMastheadExtendedDocs.js
Labels: status: DO NOT MERGE

#2046 React percentage input
  src/patterns/components/inputs/percentage-disabled.hbs
  src/patterns/components/inputs/percentage-error.hbs
  src/patterns/components/inputs/percentage.hbs
  src/patterns/components/inputs/react/code/percentage-disabled.hbs
  src/patterns/components/inputs/react/code/percentage-error.hbs
  src/patterns/components/inputs/react/code/percentage.hbs
  src/patterns/components/inputs/react/global-info.hbs
  src/react/projects/spark-react/src/SprkInput/SprkSelectionInput/SprkSelectionInput.js
  src/react/projects/spark-react/src/SprkInput/SprkSelectionInput/SprkSelectionInput.test.js
  src/react/projects/spark-react/src/SprkInput/SprkTextInput/SprkTextInput.js
  src/react/projects/spark-react/src/SprkInput/SprkTextInput/SprkTextInput.test.js
  src/react/projects/spark-react/src/SprkInput/components/SprkInputIconCheck.js
  src/react/projects/spark-react/src/SprkInput/components/SprkInputIconCheck.test.js
  src/react/projects/spark-react/src/SprkInput/components/SprkInputLabel.js
  src/react/projects/spark-react/src/SprkInput/components/SprkLabelLocationCheck.js
  src/react/projects/spark-react/src/SprkInput/components/SprkTextareaCheck.js
  src/react/src/routes/SprkInputDocs/SprkSelectionInputDocs/SprkSelectionInputDocs.js
  src/react/src/routes/SprkInputDocs/SprkTextInputDocs/SprkTextInputDocs.js
  src/react/src/routes/SprkMastheadExtendedDocs/SprkMastheadExtendedDocs.js
Labels: js: angular, status: PR review

#2049 Angular --prod build bug fix
  src/angular/projects/spark-angular/package.json
  src/angular/projects/spark-angular/src/lib/directives/inputs/sprk-input/sprk-input.directive.ts
Labels: status: PR review

#2064 updates spark js and gets the html storybook working
  .gitignore
  package.json
  spark/base/inputs/vanilla/hugeInput.js
  spark/base/links/vanilla/links.stories.js
  spark/components/accordions/vanilla/accordions.stories.js
  spark/components/alerts/vanilla/alerts.stories.js
  spark/components/awards/vanilla/awards.stories.js
  spark/components/buttons/vanilla/button.stories.js
  spark/components/card/vanilla/card.stories.js
  spark/components/dictionary/vanilla/dictionary.stories.js
  spark/components/dividers/vanilla/dividers.stories.js
  spark/components/dropdown/vanilla/dropdown.stories.js
  spark/components/footer/vanilla/footer.stories.js
  spark/components/highlight-board/vanilla/highlight-board.stories.js
  spark/components/icons/vanilla/icons.stories.js
  spark/components/masthead/vanilla/masthead.stories.js
  spark/components/modals/vanilla/modals.stories.js
  spark/components/pagination/vanilla/pagination.stories.js
  spark/components/promo/vanilla/promo.stories.js
  spark/components/spinners/vanilla/spinners.stories.js
  spark/components/stepper/vanilla/stepper.stories.js
  spark/components/tabs/vanilla/tabs.stories.js
  spark/components/toggle/vanilla/toggle.stories.js
  spark/manifests/spark/.npmignore
  spark/manifests/spark/package-lock.json
  spark/manifests/spark/spark-exports.js
  spark/manifests/spark/spark-polyfills.js
  spark/manifests/spark/spark.js
  spark/manifests/spark/webpack.config.js
  spark/objects/box/vanilla/box.stories.js
  spark/objects/centered-column/vanilla/centered-column.stories.js
  spark/objects/flag/vanilla/flag.stories.js
  spark/objects/horizontal-list/vanilla/horizontal-list.stories.js
  spark/objects/stack/vanilla/stack.stories.js
  spark/objects/vertical-list/vanilla/vertical-list.stories.js
  spark/utilities/helpers/vanilla/addClassIfNotEmpty.js
  spark/utilities/helpers/vanilla/toggleClassWithValue.js
  spark/utilities/helpers/vanilla/versionCheck.js
  spark/utilities/overrides/styles/_overrides.scss
  spark/utilities/polyfills/vanilla/CustomEvent.js
  spark/utilities/polyfills/vanilla/ObjectAssign.js
  vanilla/.storybook/addons.js
  vanilla/.storybook/config.js
  vanilla/.storybook/presets.js
  vanilla/.storybook/webpack.config.js
  vanilla/package-lock.json
  vanilla/package.json
Labels: status: PR review

#2063 React components
  storybook-spark-theme.js
Labels: status: PR review

#2072 Adds React Dropdown to Storybook
  spark/components/dropdown/react/SprkDropdown.stories.js
Labels: status: PR review

#2068 Add SprkCard React to Storybook
  spark/components/card/react/SprkCard.js
  spark/components/card/react/SprkCard.stories.js
  spark/components/card/react/components/SprkCardHighlightedHeader/SprkCardHighlightedHeader.js
  spark/components/card/react/components/SprkCardHighlightedHeader/SprkCardHighlightedHeader.test.js
  spark/components/card/react/components/SprkCardTeaser/SprkCardTeaser.js
  spark/components/card/react/components/SprkCardTeaser/SprkCardTeaser.test.js
Labels: js: react, status: PR review

#2073 Add Footer Storybook
  spark/components/card/react/SprkCard.stories.js
  spark/components/card/react/SprkCard.test.js
  spark/components/card/react/components/SprkCardTeaser/SprkCardTeaser.test.js
  spark/components/footer/react/SprkFooter.js
  spark/components/footer/react/SprkFooter.stories.js
  spark/components/footer/react/SprkFooter.test.js
  spark/components/footer/react/components/SprkFooterAwards/SprkFooterAwards.js
  spark/components/footer/react/components/SprkFooterAwards/SprkFooterAwards.test.js
  spark/components/footer/react/components/SprkFooterConnectIcons/SprkFooterConnectIcons.js
  spark/components/footer/react/components/SprkFooterConnectIcons/SprkFooterConnectIcons.test.js
  spark/components/footer/react/components/SprkFooterGlobalSection/SprkFooterGlobalSection.js
  spark/components/footer/react/components/SprkFooterGlobalSection/SprkFooterGlobalSection.test.js
Labels: js: react, status: PR review
