Repository sparkdesignsystem/spark-design-system, pull requests merged in 2020-04, with the labels that each got.

#3003 HTML Award
  html/components/award.stories.js
Labels: status: PR review

#3005 HTML Footer
  html/components/footer.stories.js
  src/data/sass-modifiers.json
Labels: status: PR review

#3008 update react toggle to button
  react/package-lock.json
  react/package.json
  react/src/components/footer/components/SprkFooterAwards/SprkFooterAwards.test.js
  react/src/components/toggle/SprkToggle.js
  react/src/components/toggle/SprkToggle.test.js
Labels: status: PR review

#2999 Update Angular, React and HTML Toggle components
  angular/package-lock.json
  angular/package.json
  angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.ts
  html/components/_toggle.scss
  html/components/masthead.js
  html/components/toggle.js
  html/components/toggle.stories.js
  html/settings/_settings.scss
  html/utilities/generateAriaControls.js
  react/src/components/toggle/SprkToggle.js
  src/data/sass-modifiers.json
  src/data/sass-vars.json
Labels: status: PR review

#3034 lock up focus-visible
  angular/package.json
  react/package.json
Labels: status: PR review

#3021 Update React Footer Story
  react/src/components/footer/SprkFooter.stories.js
Labels: status: PR review

#2998 Upgrade spark-angular to Angular 9
  angular/angular.json
  angular/package-lock.json
  angular/package.json
  angular/projects/spark-angular/package-lock.json
  angular/projects/spark-angular/package.json
  angular/projects/spark-angular/src/environment/environment.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.interfaces.ts
  angular/projects/spark-angular/tsconfig.lib.json
  angular/projects/spark-angular/tsconfig.lib.prod.json
  angular/tsconfig.json
  html/package-lock.json
  html/package.json
  react/package-lock.json
  react/package.json
  src/pages/installing-spark/angular.mdx
Labels: status: DO NOT MERGE

#3035 add a sort function for graphql nodes
  src/hooks/use-using-spark.js
  src/util/compareEdges.js
Labels: status: PR review

#3040 update Tabs documentation on site
  src/pages/using-spark/components/tabs.mdx
Labels: status: PR review

#3036 Add aria-controls to angular masthead narrow nav, update sprk-toggle, update SprkToggle
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.ts
  react/src/components/toggle/SprkToggle.js
  react/src/components/toggle/SprkToggle.test.js
Labels: status: PR review

#3044 update center width column
  html/settings/_settings.scss
  src/data/sass-modifiers.json
  src/data/sass-vars.json
Labels: status: PR review

#3039 Anything inside Masthead toggles need aria-controls
  html/components/_masthead.scss
  html/settings/_settings.scss
  react/package.json
  react/src/components/masthead/SprkMasthead.js
  react/src/components/masthead/SprkMasthead.test.js
  react/src/components/masthead/components/SprkMastheadAccordion/SprkMastheadAccordion.js
  react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.js
  react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.test.js
  react/src/components/masthead/components/SprkMastheadMenuIcon/SprkMastheadMenuIcon.js
  react/src/components/masthead/components/SprkMastheadNarrowNav/SprkMastheadNarrowNav.js
  src/data/sass-modifiers.json
  src/data/sass-vars.json
Labels: js: react, status: PR review

#3047 Update Masthead Accordion Item - Angular
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion-item/sprk-masthead-accordion-item.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion-item/sprk-masthead-accordion-item.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion-item/sprk-masthead-accordion-item.module.ts
  html/components/_masthead.scss
  html/settings/_settings.scss
  react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.js
  src/data/sass-modifiers.json
  src/data/sass-vars.json
Labels: status: PR review

#3050 HTML Masthead Accordion
  html/components/masthead.stories.js
Labels: status: PR review

#3051 Angular Bugs - Table & Modal
  angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-table/sprk-table.component.ts
Labels: status: PR review

#3052 re-add sassdoc
  angular/package-lock.json
  angular/package.json
  html/package-lock.json
  html/package.json
  package-lock.json
  package.json
  react/package-lock.json
  react/package.json
Labels: status: PR review

#3053 Add max-width: 100% utility and inputs modifier
  html/base/inputs/_input-container.scss
  html/settings/_settings.scss
  html/utilities/_utilities.scss
  src/components/Footer.js
  src/data/sass-modifiers.json
  src/data/sass-utilities.json
  src/data/sass-vars.json
Labels: status: PR review

#3057 update installing icons docs
  src/pages/installing-spark/installing-icons.mdx
Labels: status: PR review

#3059 update Font Install docs
  src/pages/installing-spark/installing-fonts.mdx
Labels: status: PR review

#3060 update installing spark docs
  src/pages/installing-spark.mdx
Labels: status: PR review

#3075 add preventDefault for dropdown toggle
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
Labels: status: PR review

#3077 Change to a more accessible green
  html/settings/_colors.scss
  src/data/sass-modifiers.json
  src/data/sass-vars.json
Labels: scope: all pkgs, status: PR review

#3083 Highlight Board cannot have a sole secondary cta
  react/src/components/highlight-board/SprkHighlightBoard.js
  react/src/components/highlight-board/SprkHighlightBoard.test.js
  src/data/sass-modifiers.json
  src/pages/using-spark/components/highlight-board.mdx
Labels: js: react, status: PR review

#3089 Gatsby background
  src/scss/_spark-theme.scss
Labels: status: PR review

#3073 Checkboxes - HTML
  angular/projects/spark-angular/src/lib/components/inputs/Checkbox.stories.ts
  html/base/_inputs.scss
  html/base/inputs/Checkbox.stories.js
  html/base/inputs/_checkbox.scss
  html/base/inputs/checkbox.js
  html/settings/_settings.scss
  html/spark-exports.js
  html/tests/checkbox.tests.js
  html/tests/generateIdForInput.tests.js
  html/utilities/generateIdForInput.js
  react/src/base/inputs/Checkbox.stories.js
  src/data/sass-modifiers.json
  src/data/sass-vars.json
  src/pages/using-spark/components/input.mdx
Labels: status: PR review

#3085 Update Radios!
  angular/package-lock.json
  angular/projects/spark-angular/package.json
  angular/projects/spark-angular/src/environment/environment.ts
  angular/projects/spark-angular/src/lib/components/inputs/Radio.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
  html/base/_inputs.scss
  html/base/inputs/Radio.stories.js
  html/base/inputs/_inputs.scss
  html/base/inputs/_radio.scss
  html/base/inputs/radioInput.js
  html/package-lock.json
  html/package.json
  html/settings/_settings.scss
  html/spark-exports.js
  html/tests/masthead.tests.js
  html/tests/radioInput.tests.js
  react/package-lock.json
  react/package.json
  react/src/base/inputs/Radio.stories.js
  src/data/sass-modifiers.json
  src/pages/using-spark/components/input.mdx
Labels: status: DO NOT MERGE, status: PR review

#3101 Update Radio and Checkbox - React
  html/base/inputs/_checkbox.scss
  html/settings/_settings.scss
  react/src/base/inputs/SprkSelectionInput/SprkSelectionInput.js
  react/src/base/inputs/SprkSelectionInput/SprkSelectionInput.test.js
  src/data/sass-modifiers.json
  src/data/sass-vars.json
Labels: status: PR review

#3106 Update homepage images
  src/components/layouts/Layout.js
  src/data/sass-modifiers.json
  src/images/components.svg
  src/images/designers.svg
  src/images/developers.svg
  src/images/foundations.svg
  src/images/guides.svg
  src/images/news-and-updates.svg
  src/images/powerlines.svg
  src/images/utilities.svg
  src/pages/index.js
Labels: status: PR review, type: documentation

#3086 Add docs and color update images
  html/components/_stepper.scss
  html/settings/_settings.scss
  src/data/sass-modifiers.json
  src/data/sass-vars.json
  src/images/colors-on-dark.png
  src/images/colors-on-dark@2x.png
  src/images/colors-on-dark@3x.png
  src/images/colors-on-light.png
  src/images/colors-on-light@2x.png
  src/images/colors-on-light@3x.png
  src/images/do-not-mix-colors.png
  src/images/do-not-use-accents-in-large-amounts.png
  src/images/do-not-use-dark-bgs-for-text.png
  src/images/do-not-use-gradients.png
  src/pages/using-spark/foundations/color.mdx
Labels: scope: all pkgs, status: PR review, type: documentation

#3103 Add Skip Nav to Gatsby Site
  gatsby-browser.js
  package-lock.json
  package.json
  src/components/layouts/Layout.js
  src/scss/_spark-theme.scss
Labels: status: DO NOT MERGE

#3112 update input border colors to darker gray
  html/settings/_settings.scss
Labels: status: PR review, type: Design Enhancement

#3120 revert label font size
  html/settings/_settings.scss
Labels: status: PR review

#3121 Spark Radio - focus and hover style
  html/base/inputs/_radio.scss
Labels: Component: Inputs, a11y

#3109 Checkbox & Radio - Angular
  angular/projects/spark-angular/src/lib/components/inputs/sprk-selection-item-container/sprk-selection-item-container.component.spec.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-selection-item-container/sprk-selection-item-container.component.ts
  html/components/masthead.js
  html/components/toggle.js
  html/objects/_box.scss
  html/spark-exports.js
  html/tests/generateAriaControls.tests.js
  html/tests/toggleAriaExpanded.tests.js
  html/utilities/generateAriaControls.js
  html/utilities/toggleAriaExpanded.js
  src/data/sass-modifiers.json
  src/data/sass-utilities.json
  src/data/sass-vars.json
Labels: status: PR review

#3124 Selection color and gitignore updates
  html/settings/_settings.scss
  src/data/sass-modifiers.json
Labels: scope: all pkgs, status: PR review
