Repository sparkdesignsystem/spark-design-system, pull requests merged in 2020-10, with the labels that each got.

#3480 add proptypes to ContextSubMenu
  src/components/ContextSubMenu.js
Labels: Hacktoberfest, status: PR review

#3544 Update to banner message
  html/utilities/validation/isValidPhone.js
  html/utilities/validation/isValidSSN.js
  html/utilities/validation/setValidTextInput.js
  src/components/ContentWrapper.js
  src/components/ContextSubMenu.js
  src/components/CssUtilityTable.js
  src/components/Footer.js
  src/components/Header.js
  src/components/InstallingSparkDocsMenu.js
  src/components/layouts/HomepageLayout.js
  src/components/layouts/Layout.js
  src/components/layouts/PrinciplesLayout.js
  src/components/layouts/UsingSparkLayout.js
  src/components/markdown-render/a.js
  src/pages/index.js
Labels: hacktoberfest-accepted

#3487 Alert updates
  angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.stories.ts
Labels: status: PR review

#3485 update html spinner
  html/components/button.stories.js
  html/components/spinners.js
  html/tests/spinners.tests.js
Labels: status: PR review

#3558 Link Updates
  angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.directive.ts
  angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.stories.ts
  react/src/base/links/SprkLink.js
  react/src/base/links/SprkLink.stories.js
  react/src/base/links/SprkLink.test.js
Labels: status: PR review

#3538 Fix focus for React modal component
  react/src/components/modals/SprkModal.js
Labels: status: PR review

#3484 Doc clarity
  src/components/DevDocLinks.js
  src/pages/using-spark.mdx
  src/pages/using-spark/components/accordion.mdx
  src/pages/using-spark/components/alert.mdx
  src/pages/using-spark/components/award.mdx
  src/pages/using-spark/components/box.mdx
  src/pages/using-spark/components/button.mdx
  src/pages/using-spark/foundations/color-accessibility.mdx
  src/pages/using-spark/foundations/color-usage.mdx
  src/pages/using-spark/foundations/css-utilities.mdx
  src/pages/using-spark/foundations/sass-variables.mdx
  src/pages/using-spark/foundations/space.mdx
  src/pages/using-spark/foundations/typography.mdx
  src/scss/components/_blockquote.scss
Labels: status: PR review, type: documentation

#3560 Toggle Updates - React
  react/src/components/awards/SprkAward.js
  react/src/components/footer/components/SprkFooterAwards/SprkFooterAwards.js
  react/src/components/toggle/SprkToggle.js
  react/src/components/toggle/SprkToggle.stories.js
  react/src/components/toggle/SprkToggle.test.js
Labels: status: PR review

#3564 React Accordion Updates
  react/src/components/accordions/SprkAccordion.js
  react/src/components/accordions/SprkAccordion.stories.js
  react/src/components/accordions/SprkAccordion.test.js
  react/src/components/accordions/components/SprkAccordionItem/SprkAccordionItem.js
  react/src/components/accordions/components/SprkAccordionItem/SprkAccordionItem.test.js
Labels: status: PR review

#3548 React Award API Updates
  react/src/components/awards/SprkAward.js
  react/src/components/awards/SprkAward.stories.js
  react/src/components/awards/SprkAward.test.js
  react/src/components/footer/components/SprkFooterAwards/SprkFooterAwards.js
  react/src/objects/stack/SprkStack.js
Labels: status: PR review

#3565 React Tabs Updates
  react/src/components/tabs/SprkTabs.js
  react/src/components/tabs/components/SprkTabsButton/SprkTabsButton.js
  react/src/components/tabs/components/SprkTabsButton/SprkTabsButton.test.js
  react/src/components/tabs/components/SprkTabsPanel/SprkTabsPanel.js
  react/src/components/tabs/components/SprkTabsPanel/SprkTabsPanel.test.js
  react/src/components/toggle/SprkToggle.test.js
Labels: changes requested

#3550 Angular Award API Updates
  angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-stack/sprk-stack.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-stack/sprk-stack.component.ts
Labels: status: PR review

#3588 Toggle Updates - Angular
  angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.stories.ts
  react/src/components/footer/components/SprkFooterAwards/SprkFooterAwards.js
  react/src/components/toggle/SprkToggle.js
  react/src/components/toggle/SprkToggle.test.js
Labels: status: PR review

#3590 Add a README to the React package
  react/README.md
Labels: changes requested

#3552 React Button API Upgrades - separate Sprkpinner - Add isDisabled
  html/components/_buttons.scss
  react/src/components/buttons/SprkButton.js
  react/src/components/buttons/SprkButton.stories.js
  react/src/components/buttons/SprkButton.test.js
  react/src/components/spinners/SprkSpinner.js
  react/src/components/spinners/SprkSpinner.test.js
Labels: Component: Buttons, js: react, status: PR review

#3592 Angular Accordion API Upgrades
  angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.stories.ts
  src/pages/using-spark/components/accordion.mdx
Labels: status: PR review

#3599 Add analyticsString to angular model close button
  angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.component.ts
Labels: changes requested

#3602 update icon color for simple links in masthead on hover
  html/components/_masthead.scss
  html/settings/_settings.scss
Labels: status: PR review
