Repository sparkdesignsystem/spark-design-system, pull requests merged in 2020-08, with the labels that each got.

#3319 Centered column: Update analytics string api
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.ts
  angular/projects/spark-angular/src/lib/directives/sprk-centered-column/sprk-centered-column.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/sprk-centered-column/sprk-centered-column.directive.ts
  react/src/objects/centered-column/SprkCenteredColumn.js
  react/src/objects/centered-column/SprkCenteredColumn.test.js
Labels: js: angular, js: react, status: PR review

#3305 updates version, adds script to run schematics from build
  angular/package.json
  angular/projects/spark-angular/package.json
  angular/projects/spark-angular/src/environment/environment.ts
Labels: status: PR review

#3303 Dictionary Upgrades
  angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-link/sprk-link.component.ts
  angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.stories.ts
  react/src/components/dictionary/SprkDictionary.js
  react/src/components/dictionary/SprkDictionary.test.js
Labels: status: PR review

#3322 adds messaging around angular schematics
  src/pages/installing-spark/angular.mdx
Labels: status: PR review

#3321 Flag: Update api, fix errors and formatting
  .eslintrc
  angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts
  react/src/components/flag/SprkFlag.js
  react/src/components/flag/SprkFlag.test.js
Labels: Component: Flag, js: angular, js: react, status: PR review

#3320 Tooltip Upgrades
  angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.ts
  react/src/components/tooltip/SprkTooltip.js
  react/src/components/tooltip/SprkTooltip.stories.js
  react/src/components/tooltip/SprkTooltip.test.js
Labels: status: PR review

#3342 Box Upgrades
  angular/projects/spark-angular/src/lib/directives/sprk-box/sprk-box.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/sprk-box/sprk-box.directive.ts
  react/src/objects/box/SprkBox.js
  react/src/objects/box/SprkBox.stories.js
  react/src/objects/box/SprkBox.test.js
Labels: status: PR review

#3344 Divider upgrades
  angular/projects/spark-angular/src/lib/components/sprk-divider/sprk-divider.stories.ts
  angular/projects/spark-angular/src/lib/directives/sprk-divider/sprk-divider.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/sprk-divider/sprk-divider.directive.ts
  angular/projects/spark-angular/src/lib/directives/sprk-divider/sprk-divider.module.ts
  angular/projects/spark-angular/src/lib/directives/sprk-divider/sprk-divider.stories.ts
  angular/projects/spark-angular/src/lib/spark-angular.module.ts
  angular/projects/spark-angular/src/public-api.ts
  react/src/components/dividers/SprkDivider.js
  react/src/components/dividers/SprkDivider.stories.js
Labels: status: PR review

#3343 Reactbugfix
  react/src/components/buttons/SprkButton.js
Labels: status: PR review

#3346 Update icon API
  angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.component.ts
  react/src/components/icons/SprkIcon.js
  react/src/components/icons/SprkIcon.test.js
Labels: js: angular, js: react, status: PR review

#3351 adds loading attr to iframes, set to lazy
  src/components/ComponentPreview.js
Labels: status: PR review

#3347 Heading Upgrades
  angular/projects/spark-angular/src/lib/directives/sprk-heading/sprk-heading.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/sprk-heading/sprk-heading.directive.ts
  react/src/base/typography/SprkHeading/SprkHeading.js
  react/src/base/typography/SprkHeading/SprkHeading.stories.js
  react/src/base/typography/SprkHeading/SprkHeading.test.js
Labels: status: PR review

#3358 Update SprkButton & SprkAward propTypes
  react/src/components/awards/SprkAward.js
  react/src/components/awards/SprkAward.test.js
  react/src/components/buttons/SprkButton.js
  react/src/components/buttons/SprkButton.test.js
Labels: status: PR review

#3354 Tooltip animation
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.stories.ts
  html/components/_tooltip.scss
  html/components/tooltip.js
  html/components/tooltip.stories.js
  html/settings/_settings.scss
  react/src/components/tooltip/SprkTooltip.js
Labels: status: PR review

#3389 Add stroke width to menu icon and new vars
  html/components/_menu.scss
  html/settings/_settings.scss
Labels: status: PR review

#3388 update icon sizes in docs page for icons
  src/pages/using-spark/components/icon.mdx
Labels: status: PR review

#3391 update spinners in buttons & remove colors
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.ts
  html/components/_spinners.scss
  html/components/button.stories.js
  html/settings/_colors.scss
  html/settings/_settings.scss
  html/utilities/_utilities.scss
  react/src/components/buttons/SprkButton.js
  react/src/components/buttons/SprkButton.test.js
  react/src/components/spinners/SprkSpinner.js
  react/src/components/spinners/SprkSpinner.test.js
  src/scss/_settings.scss
Labels: status: DO NOT MERGE

#3392 Link updates
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
  html/base/_links.scss
  html/components/_masthead.scss
  html/components/accordion.stories.js
  html/components/masthead.stories.js
  html/components/modal.stories.js
  html/settings/_settings.scss
  react/src/components/accordions/SprkAccordion.stories.js
Labels: status: PR review

#3399 Change HTML and Ng tooltip button types
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.ts
  html/components/tooltip.stories.js
Labels: status: PR review

#3397 converts tooltip placement css to use percentages instead of variables
  html/components/_tooltip.scss
  html/settings/_settings.scss
Labels: status: PR review
