Repository sparkdesignsystem/spark-design-system, pull requests merged in 2020-11, with the labels that each got.

#3620 update icons link
  gatsby-config.js
Labels: status: PR review

#3608 Fix uniqueIds from incrementing on toggle
  react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.js
  react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.test.js
  react/src/components/toggle/SprkToggle.js
  react/src/components/toggle/SprkToggle.test.js
Labels: status: PR review

#3555 Angular Button API Upgrades - separate into spinner directive
  angular/projects/spark-angular/src/lib/directives/sprk-button/sprk-button.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/sprk-button/sprk-button.directive.ts
  angular/projects/spark-angular/src/lib/directives/sprk-button/sprk-button.module.ts
  angular/projects/spark-angular/src/lib/directives/sprk-button/sprk-button.stories.ts
  angular/projects/spark-angular/src/lib/directives/sprk-spinner/sprk-spinner.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/sprk-spinner/sprk-spinner.directive.ts
  angular/projects/spark-angular/src/lib/directives/sprk-spinner/sprk-spinner.module.ts
  angular/projects/spark-angular/src/lib/spark-angular.module.ts
  angular/projects/spark-angular/src/public-api.ts
  html/components/_buttons.scss
  react/src/components/buttons/SprkButton.js
  react/src/components/buttons/SprkButton.stories.js
  react/src/components/buttons/SprkButton.test.js
Labels: Component: Buttons, js: angular, status: PR review

#3642 HTML Button Upgrades (Accessibility, API, Spiner)
  README.md
  angular/projects/spark-angular/src/lib/directives/sprk-button/sprk-button.directive.ts
  html/components/button.stories.js
  html/components/spinners.js
  html/tests/spinners.tests.js
  src/pages/installing-spark/html-environment-setup.mdx
Labels: Component: Buttons, js: HTML, status: PR review

#3655 Update design-principles.mdx
  src/pages/principles/design-principles.mdx
Labels: status: PR review, type: documentation

#3656 Design Tokens Documentation
  netlify.toml
  src/components/SassVarTable.js
  src/pages/installing-spark/angular.mdx
  src/pages/installing-spark/react.mdx
  src/pages/using-spark/foundations/design-tokens.mdx
Labels: a11y, type: documentation

#3657 Update contrast charts
  src/images/accessibility-chart-1.png
  src/images/accessibility-chart-1@2x.png
  src/images/accessibility-chart-1@3x.png
  src/images/accessibility-chart-2.png
  src/images/accessibility-chart-2@2x.png
  src/images/accessibility-chart-2@3x.png
  src/images/contrast-chart-1-high-res.jpg
  src/images/contrast-chart-2-high-res.jpg
Labels: Gatsby, status: PR review, type: documentation

#3665 Release fixes
  react/src/components/dropdown/SprkDropdown.js
  react/src/components/toggle/SprkToggle.js
Labels: status: PR review

#3659 Update banner message in V13
  src/components/layouts/Layout.js
Labels: status: DO NOT MERGE, status: PR review

#3660 update banner message
  src/components/layouts/Layout.js
Labels: status: DO NOT MERGE, status: PR review

#3672 update message banner on main
  src/components/layouts/Layout.js
Labels: Main, status: PR review

#3674 Update HTML Spinner Docs
  html/components/button.stories.js
Labels: status: PR review
