Repository sparkdesignsystem/spark-design-system, pull requests merged in 2020-03, with the labels that each got.

#2818 Keyboard Tabbing - HTML Mobile Masthead
  html/components/masthead.stories.js
  src/pages/installing-spark/html-installation.mdx
Labels: status: PR review

#2827 Update to HTML Environment Setup Guide
  src/pages/installing-spark/html-environment-setup.mdx
Labels: status: PR review

#2882 HTML Tutorial Clarification
  src/pages/installing-spark/html-environment-setup.mdx
  src/pages/installing-spark/html-installation.mdx
Labels: status: PO approved

#2889 Add sprkLink Directive
  angular/projects/spark-angular/src/lib/components/sprk-link/sprk-link.component.ts
  angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.directive.ts
  angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.module.ts
  angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.stories.ts
  angular/projects/spark-angular/src/lib/spark-angular.module.ts
Labels: status: PR review

#2883 Add anchor id tags to headings
  src/components/markdown-render/h1.js
  src/components/markdown-render/h2.js
  src/components/markdown-render/h3.js
  src/components/markdown-render/h4.js
Labels: status: PR review

#2896 Add type search to search inputs
  angular/projects/spark-angular/src/lib/components/inputs/Search.stories.ts
  html/base/inputs/Search.stories.js
  react/src/base/inputs/Search.stories.js
Labels: status: PR review

#2905 Add youtube videos to docs site and footer
  src/components/Footer.js
  src/pages/installing-spark/html-add-components.mdx
  src/pages/installing-spark/html-environment-setup.mdx
  src/pages/installing-spark/html-installation.mdx
Labels: status: PR review

#2895 Update components to use sprkLink directive
  angular/package.json
  angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion-item/sprk-masthead-accordion-item.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion-item/sprk-masthead-accordion-item.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion-item/sprk-masthead-accordion-item.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion/sprk-masthead-accordion.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-accordion/sprk-masthead-accordion.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle-animations.ts
  angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.stories.ts
  angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.directive.ts
Labels: status: PR review

#2903 Centered Column
  angular/projects/spark-angular/src/lib/directives/sprk-box/sprk-box.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/sprk-centered-column/sprk-centered-column.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/sprk-centered-column/sprk-centered-column.directive.ts
  angular/projects/spark-angular/src/lib/directives/sprk-centered-column/sprk-centered-column.module.ts
  angular/projects/spark-angular/src/lib/directives/sprk-centered-column/sprk-centered-column.stories.ts
  html/settings/_settings.scss
  react/src/objects/centered-column/SprkCenteredColumn.js
  react/src/objects/centered-column/SprkCenteredColumn.stories.js
  react/src/objects/centered-column/SprkCenteredColumn.test.js
  src/pages/using-spark/components/centered-column.mdx
Labels: status: PR review

#2915 Update Spinner Dark Color and Add Secondary Spinner Story to HTML
  html/components/_spinners.scss
  html/components/button.stories.js
  html/settings/_settings.scss
  src/data/sass-modifiers.json
  src/data/sass-vars.json
  src/pages/using-spark/components/button.mdx
Labels: status: PR review

#2911 Refactor flag into flexbox, add reverse
  html/objects/_flag.scss
  html/objects/flag.stories.js
  src/pages/using-spark/components/flag.mdx
Labels: status: PR review

#2919 Add Secondary Spinner to React
  react/src/components/buttons/SprkButton.js
  react/src/components/buttons/SprkButton.stories.js
  react/src/components/buttons/SprkButton.test.js
  src/pages/using-spark/components/button.mdx
Labels: status: PR review

#2918 Flex flag react
  html/objects/_flag.scss
  html/objects/flag.stories.js
  react/src/components/flag/SprkFlag.js
  react/src/components/flag/SprkFlag.stories.js
  react/src/components/flag/SprkFlag.test.js
  react/src/spark-exports-react.js
  src/pages/using-spark/components/flag.mdx
Labels: status: PR review

#2923 Add sprk-flag component to Angular
  angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.stories.ts
  angular/projects/spark-angular/src/lib/spark-angular.module.ts
  src/pages/using-spark/components/flag.mdx
Labels: status: PR review

#2925 Link Deprecation Docs and Warning
  angular/projects/spark-angular/src/lib/components/sprk-link/sprk-link.component.ts
  angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.stories.ts
Labels: status: PR review

#2961 HTML Masthead - add aria-controls and aria-expanded
  html/components/masthead.js
  html/components/toggle.js
  html/spark-exports.js
  html/tests/generateAriaControls.tests.js
  html/tests/masthead.tests.js
  html/tests/toggleAriaExpanded.tests.js
  html/utilities/generateAriaControls.js
  html/utilities/toggleAriaExpanded.js
Labels: status: DO NOT MERGE, status: PR review

#2959 add aria label to spinner buttons
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.directive.ts
  html/components/button.stories.js
  html/components/spinners.js
  html/tests/spinners.tests.js
  react/package.json
  react/src/components/buttons/SprkButton.js
  react/src/components/buttons/SprkButton.test.js
  src/pages/installing-spark/angular.mdx
Labels: status: PR review

#2969 dom-slider Upgrade
  html/components/toggle.js
  html/package-lock.json
  html/package.json
  html/tests/toggle.tests.js
  package-lock.json
Labels: status: PR review

#2960 Add utility and to HTML story
  html/components/toggle.js
  html/components/toggle.stories.js
  html/tests/toggle.tests.js
  html/utilities/_utilities.scss
  src/data/sass-utilities.json
Labels: status: PR review

#2953 Angular Accordion - add `aria-expanded` and change element
  angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.ts
  html/components/_accordions.scss
  html/settings/_settings.scss
  src/data/sass-modifiers.json
  src/data/sass-vars.json
Labels: status: PR review

#2970 Update accordion item trigger to be a button and add tests
  angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.ts
  html/components/_accordions.scss
  html/settings/_settings.scss
  react/src/components/accordions/components/SprkAccordionItem/SprkAccordionItem.js
  react/src/components/accordions/components/SprkAccordionItem/SprkAccordionItem.test.js
  src/data/sass-vars.json
Labels: status: PR review

#3002 HTML Accordion
  html/components/accordion.stories.js
Labels: status: PR review
