Repository sparkdesignsystem/spark-design-system, pull requests merged in 2020-01, with the labels that each got.

#2492 update SBs to rc.5 to remove Stories headings that are not needed
  angular/package-lock.json
  angular/package.json
  html/package-lock.json
  html/package.json
  html/tests/hugeInput.tests.js
  react/package-lock.json
  react/package.json
Labels: status: PR review

#2499 Add Footer docs to NDS
  src/pages/using-spark/components/footer.mdx
Labels: status: PR review

#2497 Add Accordion docs to NDS
  angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.stories.ts
  html/components/accordion.stories.js
  src/pages/using-spark/components/accordion.mdx
Labels: status: PR review

#2495 Modal docs
  angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.stories.ts
  html/components/modal.stories.js
  react/src/components/modals/SprkModal.stories.js
  src/pages/using-spark/components/modal.mdx
  storybook-utilities/markdownDocumentationLinkBuilder.js
Labels: status: PR review

#2501 Add Divider docs to NDS
  src/pages/using-spark/components/divider.mdx
Labels: status: PR review

#2505 Add Dropdown docs to NDS
  src/pages/using-spark/components/dropdown.mdx
Labels: status: PR review

#2503 Add Button docs to NDS
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.stories.ts
  html/components/button.stories.js
  react/src/components/buttons/SprkButton.stories.js
  src/pages/using-spark/components/button.mdx
Labels: status: PR review

#2500 add subcomponents to SBs where needed
  angular/package-lock.json
  angular/package.json
  angular/projects/spark-angular/src/lib/components/inputs/Checkbox.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Date.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/DatePicker.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/HelperText.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/HugeSelect.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/HugeText.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Monetary.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Password.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Percentage.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Phone.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Radio.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/SSN.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Search.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Select.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Text.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Textarea.stories.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-datepicker/sprk-datepicker.directive.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-field-error/sprk-field-error.directive.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-helper-text/sprk-helper-text.directive.ts
Labels: status: PR review

#2506 Add Link docs to NDS
  angular/projects/spark-angular/src/lib/components/sprk-link/sprk-link.stories.ts
  html/base/link.stories.js
  react/src/base/links/SprkLink.stories.js
  src/pages/using-spark/components/link.mdx
Labels: status: PR review

#2507 Add Dictionary docs to NDS
  src/pages/using-spark/components/dictionary.mdx
Labels: status: PR review

#2502 Add Masthead to NDS
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
  html/components/masthead.stories.js
  react/src/components/masthead/SprkMasthead.stories.js
  src/pages/using-spark/components/masthead.mdx
Labels: status: PR review

#2509 Update Story names
  angular/projects/spark-angular/src/lib/components/inputs/Search.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-stack/sprk-stack.stories.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.stories.ts
  html/base/inputs/Date.stories.js
  html/base/inputs/DatePicker.stories.js
  html/base/inputs/Monetary.stories.js
  html/base/inputs/Password.stories.js
  html/base/inputs/Phone.stories.js
  html/base/inputs/SSN.stories.js
  html/base/link.stories.js
  html/components/card.stories.js
  html/components/dictionary.stories.js
  html/components/divider.stories.js
  html/components/dropdown.stories.js
  html/components/highlight-board.stories.js
  html/components/icons.stories.js
  html/components/masthead.stories.js
  html/components/promo.stories.js
  html/components/tabs.stories.js
  react/src/components/card/SprkCard.stories.js
  react/src/components/dividers/SprkDivider.stories.js
  react/src/components/icons/SprkIcon.stories.js
  react/src/components/modals/SprkModal.stories.js
  src/pages/using-spark/components/divider.mdx
  src/pages/using-spark/components/link.mdx
  src/pages/using-spark/components/masthead.mdx
Labels: status: PR review

#2511 color updates after review with Jane
  html/settings/_colors.scss
  src/components/ColorSwatchGrid.js
  src/images/do-not-overuse-red.png
  src/pages/using-spark/foundations/color.mdx
Labels: status: PR review

#2515 add centered column docs to gatsby
  html/objects/centered-column.stories.js
  src/pages/using-spark/components/centered-column.mdx
Labels: status: PR review

#2514 add box content to gatsby
  src/pages/using-spark/components/box.mdx
Labels: status: PR review

#2518 update datepicker story to resolve datepicker already declared error
  angular/projects/spark-angular/src/lib/components/inputs/DatePicker.stories.ts
  html/base/inputs/DatePicker.stories.js
  react/src/base/inputs/DatePicker.stories.js
Labels: status: PR review

#2516 add flag docs to gatsby
  src/pages/using-spark/components/flag.mdx
Labels: status: PR review

#2513 add award page doc content
  src/pages/using-spark/components/award.mdx
Labels: status: PR review

#2512 add card content to gatsby
  src/pages/using-spark/components/card.mdx
Labels: status: PR review

#2521 quoting glob
  angular/package.json
  html/package.json
  package.json
  react/package.json
Labels: status: PR review

#2522 Add Highlight Board docs to NDS
  angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.stories.ts
  html/components/highlight-board.stories.js
  react/src/components/highlight-board/SprkHighlightBoard.stories.js
  src/pages/using-spark/components/highlight-board.mdx
Labels: status: PR review

#2523 Add Table docs to NDS
  src/pages/using-spark/components/table.mdx
Labels: status: PR review

#2532 Add Pagination docs to NDS
  angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.stories.ts
  html/components/pagination.stories.js
  src/pages/using-spark/components/pagination.mdx
Labels: status: PR review

#2531 Add Toggle docs to NDS
  src/pages/using-spark/components/toggle.mdx
Labels: status: PR review

#2530 Add Stepper docs to NDS
  html/components/stepper.stories.js
  react/src/components/stepper/SprkStepper.stories.js
  src/pages/using-spark/components/stepper.mdx
Labels: status: PR review

#2525 Add Tabs docs to NDS
  angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.stories.ts
  html/components/tabs.stories.js
  react/src/components/tabs/SprkTabs.stories.js
  src/pages/using-spark/components/tabs.mdx
Labels: status: PR review

#2533 Promo docs for NDS
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.component.ts
  react/src/components/card/components/SprkCardTeaser/SprkCardTeaser.js
  react/src/components/highlight-board/SprkHighlightBoard.js
  react/src/components/promo/SprkPromo.js
  src/pages/using-spark/components/card.mdx
  src/pages/using-spark/components/promo.mdx
Labels: status: PR review

#2524 add docs iframe height html
  angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.stories.ts
  html/base/inputs/Checkbox.stories.js
  html/base/inputs/Date.stories.js
  html/base/inputs/DatePicker.stories.js
  html/base/inputs/HelperText.stories.js
  html/base/inputs/HugeSelect.stories.js
  html/base/inputs/HugeText.stories.js
  html/base/inputs/Monetary.stories.js
  html/base/inputs/Password.stories.js
  html/base/inputs/Percentage.stories.js
  html/base/inputs/Phone.stories.js
  html/base/inputs/Radio.stories.js
  html/base/inputs/SSN.stories.js
  html/base/inputs/Search.stories.js
  html/base/inputs/Select.stories.js
  html/base/inputs/Text.stories.js
  html/base/inputs/Textarea.stories.js
  html/base/link.stories.js
  html/base/list.stories.js
  html/base/table.stories.js
  html/base/typography.stories.js
  html/components/accordion.stories.js
  html/components/alert.stories.js
  html/components/award.stories.js
  html/components/button.stories.js
  html/components/card.stories.js
  html/components/dictionary.stories.js
  html/components/divider.stories.js
  html/components/dropdown.stories.js
  html/components/footer.stories.js
  html/components/highlight-board.stories.js
  html/components/icons.stories.js
  html/components/masthead.stories.js
  html/components/modal.stories.js
  html/components/pagination.stories.js
  html/components/promo.stories.js
  html/components/stepper.stories.js
  html/components/tabs.stories.js
  html/components/toggle.stories.js
  html/objects/box.stories.js
  html/objects/centered-column.stories.js
  html/objects/flag.stories.js
  html/objects/stack.stories.js
Labels: status: PR review

#2537 add accessibility guidelines page to gatsby
  src/pages/principles/accessibility-guidelines.mdx
Labels: status: PR review

#2536 Add Class Naming Convention Docs to NDS
  src/components/PrinciplesDocsMenu.js
  src/pages/principles/class-naming-convention.mdx
Labels: status: PR review

#2546 Update SB Versions
  angular/package-lock.json
  angular/package.json
  html/package-lock.json
  html/package.json
  react/package-lock.json
  react/package.json
Labels: status: PR review

#2540 Update HTML flag img to be smaller by using an icon instead so that it stacks nicely in iframe
  html/objects/flag.stories.js
  react/src/components/modals/SprkModal.stories.js
Labels: status: PR review

#2538 set inlineStories to false to fix Modal iframe height issue for react SB
  react/src/components/modals/SprkModal.stories.js
Labels: status: PR review

#2544 add spacing docs to nds
  src/pages/using-spark/foundations/space.mdx
Labels: status: PR review

#2541 Add Typography docs to NDS
  html/base/typography.stories.js
  src/pages/using-spark/foundations/typography.mdx
Labels: status: PR review

#2549 Update logos on site
  angular/.storybook/storybook-spark-theme.js
  angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.stories.ts
  html/components/award.stories.js
  html/components/footer.stories.js
  html/components/masthead.stories.js
  html/components/promo.stories.js
  html/objects/flag.stories.js
  react/src/components/awards/SprkAward.stories.js
  react/src/components/footer/SprkFooter.stories.js
  react/src/components/masthead/SprkMasthead.stories.js
  react/src/components/promo/SprkPromo.stories.js
  src/components/site-logo.js
  storybook-utilities/getStorybookInstance.js
  storybook-utilities/storybook-theming/storybook-spark-theme.js
Labels: status: PR review

#2543 2526 html icons update
  angular/.storybook/config.js
  angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.stories.ts
  html/.storybook/config.js
  html/components/icons.stories.js
  react/.storybook/config.js
  react/src/components/icons/SprkIcon.stories.js
  storybook-utilities/icon-loader.js
  storybook-utilities/icon-utilities/icon-loader.js
  storybook-utilities/icon-utilities/icon-name-util.js
  storybook-utilities/storybook-theming/_docs.scss
Labels: status: PR review

#2557 update angular links
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
Labels: status: PR review

#2564 add google analytics to nds
  angular/.storybook/addons.js
  angular/package-lock.json
  angular/package.json
  gatsby-config.js
  html/.storybook/addons.js
  html/package-lock.json
  html/package.json
  package-lock.json
  package.json
  react/.storybook/addons.js
  react/package-lock.json
  react/package.json
Labels: status: PR review

#2553 2274 icon gatsby
  angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.stories.ts
  html/components/icons.stories.js
  react/src/components/icons/SprkIcon.stories.js
  src/components/ComponentPreview.js
  src/pages/using-spark/components/icon.mdx
Labels: status: PR review

#2610 update side nav links to be simple SprkLink
  src/components/ContextSubMenu.js
  src/components/InstallingSparkDocsMenu.js
  src/components/PrinciplesDocsMenu.js
  src/scss/components/_menu.scss
Labels: status: PR review

#2609 fix typo to fix principles nav bug
  gatsby-config.js
Labels: status: PR review

#2608 add installing icons docs to gatsby
  src/pages/installing-spark/installing-icons.mdx
Labels: status: PR review

#2601 update footer copyright on NDS
  src/components/Footer.js
Labels: status: PR review

#2587 Stepper Updates
  html/components/stepper.stories.js
Labels: status: PR review

#2591 Update React Links
  react/.storybook/preview-head.html
  react/src/base/links/SprkLink.stories.js
  react/src/components/buttons/SprkButton.stories.js
  react/src/components/card/SprkCard.stories.js
  react/src/components/dropdown/SprkDropdown.stories.js
  react/src/components/highlight-board/SprkHighlightBoard.stories.js
  react/src/components/masthead/SprkMasthead.stories.js
  react/src/components/promo/SprkPromo.stories.js
Labels: status: PR review

#2600 Update SBs to stable version
  angular/package-lock.json
  angular/package.json
  html/package-lock.json
  html/package.json
  react/package-lock.json
  react/package.json
Labels: status: PR review

#2586 Improve image on promos
  angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.stories.ts
  html/components/promo.stories.js
  react/src/components/promo/SprkPromo.stories.js
Labels: scope: all pkgs, status: PR review

#2498 React prop comments
  react/src/base/inputs/SprkDatePickerInput/SprkDatePickerInput.js
  react/src/base/inputs/SprkErrorContainer/SprkErrorContainer.js
  react/src/base/inputs/SprkRevealInput/SprkRevealInput.js
  react/src/base/inputs/SprkSelectionInput/SprkSelectionInput.js
  react/src/base/inputs/SprkTextInput/SprkTextInput.js
  react/src/base/inputs/components/SprkInputElement/SprkInputElement.js
  react/src/base/links/SprkLink.js
  react/src/base/lists/SprkList.js
  react/src/base/lists/SprkListItem.js
  react/src/base/tables/SprkTable.js
  react/src/components/accordions/SprkAccordion.js
  react/src/components/accordions/components/SprkAccordionItem/SprkAccordionItem.js
  react/src/components/alerts/SprkAlert.js
  react/src/components/awards/SprkAward.js
  react/src/components/buttons/SprkButton.js
  react/src/components/card/SprkCard.js
  react/src/components/card/components/SprkCardHighlightedHeader/SprkCardHighlightedHeader.js
  react/src/components/card/components/SprkCardTeaser/SprkCardTeaser.js
  react/src/components/dictionary/SprkDictionary.js
  react/src/components/dividers/SprkDivider.js
  react/src/components/dropdown/SprkDropdown.js
  react/src/components/footer/SprkFooter.js
  react/src/components/footer/components/SprkFooterAwards/SprkFooterAwards.js
  react/src/components/footer/components/SprkFooterConnectIcons/SprkFooterConnectIcons.js
  react/src/components/footer/components/SprkFooterGlobalSection/SprkFooterGlobalSection.js
  react/src/components/highlight-board/SprkHighlightBoard.js
  react/src/components/icons/SprkIcon.js
  react/src/components/masthead/SprkMasthead.js
  react/src/components/masthead/components/SprkMastheadAccordion/SprkMastheadAccordion.js
  react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.js
  react/src/components/masthead/components/SprkMastheadBigNav/SprkMastheadBigNav.js
  react/src/components/masthead/components/SprkMastheadDropdown/SprkMastheadDropdown.js
  react/src/components/masthead/components/SprkMastheadLittleNav/SprkMastheadLittleNav.js
  react/src/components/masthead/components/SprkMastheadMenuIcon/SprkMastheadMenuIcon.js
  react/src/components/masthead/components/SprkMastheadNarrowNav/SprkMastheadNarrowNav.js
  react/src/components/masthead/components/SprkMastheadSelector/SprkMastheadSelector.js
  react/src/components/modals/CloseButton.js
  react/src/components/modals/Mask.js
  react/src/components/modals/ModalFooter.js
  react/src/components/modals/SprkModal.js
  react/src/components/pagination/SprkPagination.js
  react/src/components/promo/SprkPromo.js
  react/src/components/spinners/SprkSpinner.js
  react/src/components/stepper/SprkStepper.js
  react/src/components/stepper/components/SprkStepperSlider/SprkStepperSlider.js
  react/src/components/stepper/components/SprkStepperStep/SprkStepperStep.js
  react/src/components/tabs/SprkTabs.js
  react/src/components/tabs/components/SprkTabsButton/SprkTabsButton.js
  react/src/components/tabs/components/SprkTabsPanel/SprkTabsPanel.js
  react/src/components/toggle/SprkToggle.js
  react/src/objects/stack/SprkStack.js
  react/src/objects/stack/components/SprkStackItem/SprkStackItem.js
Labels: js: react, status: PR review

#2622 Update page structure & links
  gatsby-config.js
  src/components/ContextMenu.js
  src/components/ContextSubMenu.js
  src/components/InstallingSparkDocsMenu.js
  src/components/UsingSparkDocsMenu.js
  src/components/site-logo.js
  src/pages/installing-spark.mdx
  src/pages/installing-spark/angular.mdx
  src/pages/installing-spark/react.mdx
  src/pages/installing-spark/setting-up-your-environment.mdx
  src/pages/installing-spark/vanilla-add-components.mdx
  src/pages/installing-spark/vanilla-environment-setup.mdx
  src/pages/installing-spark/vanilla-installation.mdx
  src/pages/principles/design-principles.mdx
  src/pages/using-spark.mdx
Labels: status: PR review

#2623 Gatsby: Change to "Default Link"
  src/pages/using-spark/components/link.mdx
Labels: status: PR review, type: documentation

#2621 Add Spark Masthead And Create Homepage
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts
  gatsby-browser.js
  react/src/components/card/SprkCard.js
  react/src/components/card/SprkCard.stories.js
  react/src/components/card/SprkCard.test.js
  react/src/components/card/components/SprkCardTeaser/SprkCardTeaser.js
  src/components/ContextMenu.js
  src/components/Header.js
  src/components/InstallingSparkDocsMenu.js
  src/components/Menu.js
  src/components/PrinciplesDocsMenu.js
  src/components/UsingSparkDocsMenu.js
  src/components/layouts/Layout.js
  src/components/layouts/UsingSparkLayout.js
  src/components/site-logo.js
  src/hooks/use-installing-spark.js
  src/hooks/use-principle-spark.js
  src/hooks/use-using-spark.js
  src/pages/index.js
  src/pages/using-spark/foundations/color.mdx
  src/scss/_settings.scss
  src/scss/_spark-theme.scss
  src/scss/components/_header.scss
  src/scss/components/_layout.scss
  src/scss/objects/_color-swatch-grid.scss
Labels: status: PR review

#2658 Add Installing Fonts Guide to NDS
  src/components/layouts/Layout.js
  src/components/markdown-render/blockquote.js
  src/components/markdown-render/inlineCode.js
  src/components/markdown-render/table.js
  src/pages/installing-spark/installing-fonts.mdx
  src/pages/installing-spark/installing-icons.mdx
  src/scss/components/_blockquote.scss
  src/scss/main.scss
Labels: status: ready to merge

#2667 2654 angular ie edge
  angular/.storybook/webpack.config.js
  angular/package-lock.json
  angular/package.json
  html/.storybook/preview-head.html
  html/.storybook/webpack.config.js
  html/package-lock.json
  html/package.json
  react/.storybook/preview-head.html
  react/.storybook/webpack.config.js
  react/package-lock.json
  react/package.json
  storybook-utilities/icon-utilities/icon-loader.js
Labels: status: PR review

#2686 handle snyk notices
  .gitignore
  angular/package-lock.json
  angular/package.json
  gatsby-config.js
  html/package-lock.json
  html/package.json
  package-lock.json
  package.json
  react/package-lock.json
  react/package.json
  src/data/sass-modifiers.json
  src/data/sass-vars.json
Labels: status: PR review

#2683 Add inset tall/short and misc space options to Box!
  html/objects/_box.scss
  src/pages/using-spark/components/box.mdx
Labels: status: PR review

#2685 Spark-react masthead bug fix
  react/src/components/masthead/SprkMasthead.js
  react/src/components/masthead/components/SprkMastheadAccordion/SprkMastheadAccordion.js
  react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.js
  react/src/components/masthead/components/SprkMastheadNarrowNav/SprkMastheadNarrowNav.js
  src/components/Header.js
Labels: status: PR review

#2691 pkg json updates
  angular/projects/spark-angular/package.json
  html/package-lock.json
  html/package.json
  react/package-lock.json
  react/package.json
  react/src/components/dictionary/SprkDictionary.js
Labels: status: PR review

#2692 Input JS file updates
  html/base/inputs/dateInput.js
  html/base/inputs/datePicker.js
  html/base/inputs/hugeInput.js
  html/base/inputs/monetaryInput.js
  html/base/inputs/passwordInput.js
  html/base/inputs/phoneInput.js
  html/base/inputs/requiredSelect.js
  html/base/inputs/requiredTextInput.js
  html/base/inputs/requiredTick.js
  html/base/inputs/ssnInput.js
  html/spark-exports.js
  html/spark.js
  html/tests/dateInput.tests.js
  html/tests/datePicker.tests.js
  html/tests/hugeInput.tests.js
  html/tests/monetaryInput.tests.js
  html/tests/phoneInput.tests.js
  html/tests/requiredTextInput.tests.js
  html/tests/requiredTick.tests.js
  html/tests/ssnInput.tests.js
Labels: status: PR review

#2693 add list docs to gatsby
  src/pages/using-spark/components/list.mdx
Labels: status: PR review

#2659 NDS Bug List
  angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.component.ts
  html/base/link.stories.js
  html/components/alert.stories.js
  html/components/card.stories.js
  html/components/icons.stories.js
  react/src/components/card/SprkCard.js
  react/src/components/card/components/SprkCardTeaser/SprkCardTeaser.js
  react/src/components/masthead/SprkMasthead.stories.js
  react/src/components/modals/SprkModal.stories.js
  react/src/components/promo/SprkPromo.js
  src/components/ComponentPreview.js
  src/components/DevDocLinks.js
  src/pages/installing-spark/installing-icons.mdx
  src/pages/using-spark/components/button.mdx
  src/pages/using-spark/components/dictionary.mdx
  src/pages/using-spark/components/flag.mdx
  src/pages/using-spark/components/highlight-board.mdx
  src/pages/using-spark/components/icon.mdx
  src/pages/using-spark/components/masthead.mdx
  src/pages/using-spark/components/modal.mdx
  src/pages/using-spark/components/promo.mdx
  src/pages/using-spark/components/table.mdx
  storybook-utilities/getStorybookInstance.js
  storybook-utilities/markdownDocumentationLinkBuilder.js
Labels: status: PR review

#2697 add a11y guidelines to nds
  src/pages/principles/accessibility-guidelines.mdx
Labels: status: PR review

#2695 add guidelines special request
  src/pages/docs/accessibility.hbs
Labels: status: PR review

#2689 Gatsby at latest spark-react
  angular/.storybook/config.js
  angular/.storybook/webpack.config.js
  angular/package-lock.json
  angular/package.json
  angular/projects/spark-angular/package-lock.json
  angular/projects/spark-angular/package.json
  html/.storybook/config.js
  html/.storybook/webpack.config.js
  html/package-lock.json
  html/package.json
  package-lock.json
  package.json
  react/.storybook/config.js
  react/package-lock.json
  react/package.json
  react/src/components/masthead/SprkMasthead.js
Labels: status: PR review

#2699 2131 angular ssr
  angular/projects/spark-angular/package.json
  angular/projects/spark-angular/src/environment/environment.ts
  angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
  angular/projects/spark-angular/src/lib/spark-angular.module.ts
Labels: status: PR review

#2688 Remove unnecessary gitignores
  .gitignore
  angular/.gitignore
  html/.gitignore
  makefile
  react/.gitignore
Labels: status: PR review

#2700 beta publish versions
  angular/projects/spark-angular/package.json
  angular/projects/spark-angular/src/environment/environment.ts
  react/package.json
Labels: status: PR review

#2701 Add Stack Docs to NDS
  src/pages/using-spark/components/stack.mdx
Labels: status: PR review
