Repository sparkdesignsystem/spark-design-system, pull requests merged in 2020-07, with the labels that each got.

#3232 3186 react huge radio
  angular/projects/spark-angular/src/lib/components/inputs/sprk-radio-item/sprk-radio-item.component.spec.ts
  angular/projects/spark-angular/src/lib/spark-angular.module.ts
  angular/projects/spark-angular/src/public-api.ts
  html/base/inputs/Radio.stories.js
  html/components/tooltip.js
  html/components/tooltip.stories.js
  html/settings/_settings.scss
  html/spark-exports.js
  react/src/base/inputs/Radio.stories.js
  react/src/base/inputs/SprkFieldset/SprkFieldset.js
  react/src/base/inputs/SprkFieldset/SprkFieldset.test.js
  react/src/base/inputs/SprkHelperText/SprkHelperText.js
  react/src/base/inputs/SprkHelperText/SprkHelperText.test.js
  react/src/base/inputs/SprkLegend/SprkLegend.js
  react/src/base/inputs/SprkLegend/SprkLegend.test.js
  react/src/base/inputs/SprkRadio/SprkRadioGroup/SprkRadioGroup.js
  react/src/base/inputs/SprkRadio/SprkRadioGroup/SprkRadioGroup.test.js
  react/src/base/inputs/SprkRadio/SprkRadioItem/SprkRadioItem.js
  react/src/base/inputs/SprkRadio/SprkRadioItem/SprkRadioItem.test.js
  react/src/components/tooltip/SprkTooltip.js
  react/src/components/tooltip/SprkTooltip.stories.js
  react/src/components/tooltip/SprkTooltip.test.js
  react/src/spark-exports-react.js
  react/src/utilities/helpers/addPropsToMatchingComponents/addPropsToMatchingComponents.js
  react/src/utilities/helpers/addPropsToMatchingComponents/addPropsToMatchingComponents.test.js
  src/pages/using-spark/components/input.mdx
Labels: status: PR review

#3218 React checkbox + huge
  angular/projects/spark-angular/src/lib/components/inputs/sprk-radio-item/sprk-radio-item.component.spec.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-radio-item/sprk-radio.stories.ts
  html/base/inputs/Checkbox.stories.js
  html/base/inputs/HugeCheckbox.stories.js
  html/base/inputs/_checkbox.scss
  html/settings/_settings.scss
  react/src/base/inputs/Checkbox.stories.js
  react/src/base/inputs/SprkCheckbox.stories.js
  react/src/base/inputs/SprkCheckbox/SprkCheckboxGroup/SprkCheckboxGroup.js
  react/src/base/inputs/SprkCheckbox/SprkCheckboxGroup/SprkCheckboxGroup.test.js
  react/src/base/inputs/SprkCheckbox/SprkCheckboxItem/SprkCheckboxItem.js
  react/src/base/inputs/SprkCheckbox/SprkCheckboxItem/SprkCheckboxItem.test.js
  react/src/base/inputs/SprkLegend/SprkLegend.test.js
  react/src/base/inputs/SprkRadio.stories.js
  react/src/spark-exports-react.js
  react/src/utilities/helpers/addPropstoMatchingComponents/addPropsToMatchingComponents.js
  react/src/utilities/helpers/addPropstoMatchingComponents/addPropsToMatchingComponents.test.js
  src/pages/using-spark/components/input.mdx
Labels: js: HTML, js: react, status: PR review

#3170 Angular Tooltip Component
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.stories.ts
  angular/projects/spark-angular/src/lib/spark-angular.module.ts
  angular/projects/spark-angular/src/public-api.ts
  html/components/tooltip.js
  react/src/components/tooltip/SprkTooltip.js
  src/pages/using-spark/components/tooltips.mdx
Labels: status: PR review

#3260 remove old sass vars
  html/settings/_settings.scss
Labels: status: PR review

#3262 Correct api to isDisabled
  react/src/base/inputs/SprkCheckbox.stories.js
  react/src/base/inputs/SprkCheckbox/SprkCheckboxItem/SprkCheckboxItem.js
  react/src/base/inputs/SprkCheckbox/SprkCheckboxItem/SprkCheckboxItem.test.js
  react/src/base/inputs/SprkLegend/SprkLegend.js
  react/src/base/inputs/SprkLegend/SprkLegend.test.js
  react/src/base/inputs/SprkRadio.stories.js
  react/src/base/inputs/SprkRadio/SprkRadioItem/SprkRadioItem.js
  react/src/base/inputs/SprkRadio/SprkRadioItem/SprkRadioItem.test.js
Labels: js: react, status: PR review

#3248 Angular Checkbox Huge
  angular/projects/spark-angular/src/lib/components/inputs/Checkbox.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-checkbox-group/sprk-checkbox-group.component.spec.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-checkbox-group/sprk-checkbox-group.component.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-checkbox-group/sprk-checkbox-group.module.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-checkbox-item/sprk-checkbox-item.component.spec.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-checkbox-item/sprk-checkbox-item.component.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-checkbox-item/sprk-checkbox-item.module.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-checkbox-item/sprk-checkbox.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-radio-group/sprk-radio-group.component.spec.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-checkbox-input/sprk-checkbox-input.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-checkbox-input/sprk-checkbox-input.directive.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-checkbox-input/sprk-checkbox-input.module.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-checkbox-label/sprk-checkbox-label.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-checkbox-label/sprk-checkbox-label.directive.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-checkbox-label/sprk-checkbox-label.module.ts
  angular/projects/spark-angular/src/lib/spark-angular.module.ts
  angular/projects/spark-angular/src/public-api.ts
Labels: status: PR review

#3264 Tooltip Updates
  html/components/_tooltip.scss
Labels: status: PR review

#3265 Release Fixes
  html/settings/_settings.scss
  react/src/base/inputs/SprkCheckbox/SprkCheckboxGroup/SprkCheckboxGroup.js
  react/src/base/inputs/SprkCheckbox/SprkCheckboxItem/SprkCheckboxItem.js
  react/src/base/inputs/SprkCheckbox/SprkCheckboxItem/SprkCheckboxItem.test.js
  react/src/base/inputs/SprkRadio/SprkRadioItem/SprkRadioItem.js
  react/src/base/inputs/SprkRadio/SprkRadioItem/SprkRadioItem.test.js
  src/pages/using-spark/components/input.mdx
Labels: status: PR review

#3271 tooltip spacing at narrow layouts (HTML and React)
  html/components/tooltip.js
  react/src/components/tooltip/SprkTooltip.js
Labels: status: PR review

#3283 Updates example text for tooltips
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.stories.ts
  html/components/tooltip.stories.js
  react/src/components/tooltip/SprkTooltip.stories.js
  src/images/tooltips.png
  src/pages/using-spark/components/tooltip.mdx
Labels: status: PR review

#3288 Guide typo
  src/pages/installing-spark/react.mdx
Labels: status: PR review

#3263 Aria bug rerender
  angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.component.ts
Labels: js: angular, status: PR review

#3290 Replace shown trigger text with the title rather than the value
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
Labels: type: !BREAKING!

#3302 Stack upgrades
  angular/projects/spark-angular/src/lib/components/sprk-stack/sprk-stack.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-stack/sprk-stack.component.ts
  react/src/objects/stack/SprkStack.js
  react/src/objects/stack/SprkStack.stories.js
  react/src/objects/stack/SprkStack.test.js
  react/src/objects/stack/components/SprkStackItem/SprkStackItem.js
Labels: status: PR review

#3143 Add Angular CLI Schematics support to spark-angular
  angular/package-lock.json
  angular/package.json
  angular/projects/spark-angular/package.json
  angular/projects/spark-angular/schematics/README.md
  angular/projects/spark-angular/schematics/collection.json
  angular/projects/spark-angular/schematics/ng-add/html-manipulation.ts
  angular/projects/spark-angular/schematics/ng-add/index.ts
  angular/projects/spark-angular/schematics/ng-add/schema.json
  angular/projects/spark-angular/schematics/ng-add/schema.ts
  angular/projects/spark-angular/tsconfig.schematics.json
Labels: js: angular, status: PR review
