Repository sparkdesignsystem/spark-design-system, pull requests merged in 2020-06, with the labels that each got.

#3164 PR Template Update
  .github/pull_request_template.md
Labels: status: PR review

#3153 Fixed disabled prop bug
  react/src/components/buttons/SprkButton.js
  react/src/components/buttons/SprkButton.test.js
Labels: status: PR review

#3157 Huge Radio Inputs - HTML
  html/base/inputs/HugeRadio.stories.js
  html/base/inputs/_radio.scss
  html/settings/_settings.scss
  src/pages/using-spark/components/input.mdx
Labels: status: PR review

#3165 update background color of disabled radio
  html/base/inputs/_radio.scss
  html/settings/_settings.scss
Labels: status: PR review

#3149 Add huge checkbox
  html/base/inputs/HugeCheckbox.stories.js
  html/base/inputs/_checkbox.scss
  html/settings/_settings.scss
  src/data/sass-utilities.json
  src/pages/using-spark/components/input.mdx
Labels: js: HTML, status: PR review

#3167 add note about sticky masthead/IE11 to story files
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
  html/components/masthead.stories.js
  react/src/components/masthead/SprkMasthead.stories.js
Labels: status: PR review

#3182 Add Accordion guideline to point to Toggle if only one item
  angular/package-lock.json
  angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.stories.ts
  html/components/accordion.stories.js
  html/package-lock.json
  package-lock.json
  react/package-lock.json
  react/src/components/accordions/SprkAccordion.stories.js
  src/pages/using-spark/components/accordion.mdx
Labels: scope: all pkgs, status: PR review

#3181 Update stylelint to --fix, add prettier for ts files
  .prettierrc
  angular/projects/spark-angular/src/lib/components/inputs/Checkbox.stories.ts
  html/base/inputs/hugeInput.js
  html/components/_alerts.scss
  package.json
Labels: status: PR review

#3225 Gatsby Site - Axe Fixes
  src/components/DevDocLinks.js
  src/components/InstallingSparkDocsMenu.js
  src/components/PrinciplesDocsMenu.js
  src/components/UsingSparkDocsMenu.js
  src/components/layouts/Layout.js
  src/components/markdown-render/h3.js
  src/components/markdown-render/h4.js
Labels: status: PR review

#3227 Add new angular radio group, radio item, radio input, radio label components
  angular/angular.json
  angular/projects/spark-angular/src/lib/components/inputs/Radio.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-radio-group/sprk-radio-group.component.spec.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-radio-group/sprk-radio-group.component.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-radio-group/sprk-radio-group.module.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-radio-item/sprk-radio-item.component.spec.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-radio-item/sprk-radio-item.component.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-radio-item/sprk-radio-item.module.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-radio-item/sprk-radio.stories.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-field-error/sprk-field-error.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-fieldset/sprk-fieldset.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-fieldset/sprk-fieldset.directive.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-fieldset/sprk-fieldset.module.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-helper-text/sprk-helpler-text.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-legend/sprk-legend.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-legend/sprk-legend.directive.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-legend/sprk-legend.module.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-radio-input/sprk-radio-input.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-radio-input/sprk-radio-input.directive.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-radio-input/sprk-radio-input.module.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-radio-label/sprk-radio-label.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-radio-label/sprk-radio-label.directive.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-radio-label/sprk-radio-label.module.ts
  angular/projects/spark-angular/src/lib/spark-angular.module.ts
  angular/projects/spark-angular/src/public-api.ts
  html/base/inputs/HugeRadio.stories.js
  html/base/inputs/Radio.stories.js
  html/base/inputs/_radio.scss
  src/pages/using-spark/components/input.mdx
  storybook-utilities/storybook-theming/scss/_spark-angular-manifest.scss
Labels: status: PR review

#3217 React Tooltip Component
  html/components/tooltip.js
  react/src/components/tooltip/SprkTooltip.js
  react/src/components/tooltip/SprkTooltip.stories.js
  react/src/components/tooltip/SprkTooltip.test.js
  react/src/spark-exports-react.js
  src/pages/using-spark/components/tooltips.mdx
Labels: status: PR review
