Repository sparkdesignsystem/spark-design-system, pull requests merged in 2020-12, with the labels that each got.

#3677 Filter Tokens Page
  src/components/SassVarTable.js
  src/components/TokenTable.js
  src/pages/using-spark/foundations/design-tokens.mdx
  styles/tokens/input.json
Labels: type: documentation

#3680 Add Formatters and Validation to React Package
  react/src/jest-config.js
  react/src/spark-exports-react.js
  react/src/utilities/formatters/sprkFormatDate.js
  react/src/utilities/formatters/sprkFormatDate.test.js
  react/src/utilities/formatters/sprkFormatMonetary.js
  react/src/utilities/formatters/sprkFormatMonetary.test.js
  react/src/utilities/formatters/sprkFormatPhone.js
  react/src/utilities/formatters/sprkFormatPhone.test.js
  react/src/utilities/formatters/sprkFormatSSN.js
  react/src/utilities/formatters/sprkFormatSSN.test.js
  react/src/utilities/validation/sprkIsValidDate.js
  react/src/utilities/validation/sprkIsValidDate.test.js
  react/src/utilities/validation/sprkIsValidMonetary.js
  react/src/utilities/validation/sprkIsValidMonetary.test.js
  react/src/utilities/validation/sprkIsValidPhone.js
  react/src/utilities/validation/sprkIsValidPhone.test.js
  react/src/utilities/validation/sprkIsValidSSN.js
  react/src/utilities/validation/sprkIsValidSSN.test.js
  styles/android/spark_design_tokens_dimens.xml
Labels: status: PR review

#3658 HTML Autocomplete
  angular/package.json
  angular/projects/spark-angular/package-lock.json
  angular/projects/spark-angular/package.json
  html/components/autocomplete.js
  html/components/autocomplete.stories.js
  html/package-lock.json
  html/package.json
  html/setup-jest.js
  html/spark-exports.js
  html/spark.js
  html/tests/autocomplete.tests.js
  html/tests/generateAriaOwns.tests.js
  html/tests/isElementVisible.tests.js
  html/tests/masthead.tests.js
  html/utilities/generateAriaOwns.js
  html/utilities/isElementVisible.js
  html/utilities/keypress.js
  html/utilities/resetListItems.js
  react/package-lock.json
  react/package.json
  src/images/autocomplete/Addresstwolines.png
  src/images/autocomplete/Default_NotSelected.png
  src/images/autocomplete/Focused_withoutsearch.png
  src/images/autocomplete/NoLabelAbove.png
  src/images/autocomplete/NoMatches.png
  src/images/autocomplete/NoSearchIcon.png
  src/images/autocomplete/Searchacrosscategories.png
  src/images/autocomplete/SelectingOption.png
  src/images/autocomplete/Typing.png
  src/pages/using-spark/components/autocomplete.mdx
  styles/_spark.scss
  styles/android/spark_design_tokens_colors.xml
  styles/android/spark_design_tokens_dimens.xml
  styles/android/spark_design_tokens_strings.xml
  styles/base/inputs/_input-container.scss
  styles/components/_autocomplete.scss
  styles/ios/SparkDesignTokens.swift
  styles/package-lock.json
  styles/package.json
  styles/tokens/autocomplete.json
  styles/tokens/input.json
Labels: status: PR review

#3707 Larger Autocomplete Gatsby images
  src/images/autocomplete/Active Typing@2x.png
  src/images/autocomplete/No Results Found@2x.png
  src/images/autocomplete/No Search Icon@2x.png
  src/images/autocomplete/Selecting Options@2x.png
  src/images/autocomplete/address_two_lines@2x.png
  src/images/autocomplete/focused_without_search@2x.png
  src/images/autocomplete/no_label@2x.png
  src/images/autocomplete/search_across_categories@2x.png
  src/pages/using-spark/components/autocomplete.mdx
Labels: status: PR review

#3714 HTML Autocomplete Beta Updates
  html/components/autocomplete.stories.js
Labels: status: DO NOT MERGE
