Repository sparkdesignsystem/spark-design-system, pull requests merged in 2020-02, with the labels that each got.

#2702 Add favicons
  angular/.storybook/manager-head.html
  angular/package.json
  gatsby-config.js
  html/.storybook/manager-head.html
  html/package.json
  react/.storybook/manager-head.html
  react/package.json
  src/components/layouts/HomepageLayout.js
  src/components/layouts/InstallingSparkLayout.js
  src/components/layouts/Layout.js
  src/components/layouts/PrinciplesLayout.js
  src/components/layouts/UsingSparkLayout.js
  src/components/seo.js
  src/images/spark-logo.svg
  src/pages/using-spark.mdx
  storybook-utilities/favicon/android-chrome-192x192.png
  storybook-utilities/favicon/android-chrome-512x512.png
  storybook-utilities/favicon/apple-touch-icon.png
  storybook-utilities/favicon/browserconfig.xml
  storybook-utilities/favicon/favicon-16x16.png
  storybook-utilities/favicon/favicon-32x32.png
  storybook-utilities/favicon/favicon.ico
  storybook-utilities/favicon/mstile-150x150.png
  storybook-utilities/favicon/safari-pinned-tab.svg
  storybook-utilities/favicon/site.webmanifest
Labels: status: PR review

#2706 adding redirects file
  _redirects
Labels: status: PR review

#2696 Add Input Docs
  angular/.storybook/config.js
  angular/projects/spark-angular/src/lib/components/inputs/Date.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/DatePicker.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/HelperText.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Monetary.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Phone.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/SSN.stories.ts
  html/.storybook/config.js
  html/base/inputs/Date.stories.js
  html/base/inputs/DatePicker.stories.js
  html/base/inputs/HelperText.stories.js
  html/base/inputs/HugeSelect.stories.js
  html/base/inputs/HugeText.stories.js
  html/base/inputs/Monetary.stories.js
  html/base/inputs/Password.stories.js
  html/base/inputs/Phone.stories.js
  html/base/inputs/SSN.stories.js
  react/.storybook/config.js
  react/src/base/inputs/Date.stories.js
  react/src/base/inputs/DatePicker.stories.js
  react/src/base/inputs/HelperText.stories.js
  react/src/base/inputs/Monetary.stories.js
  react/src/base/inputs/Phone.stories.js
  react/src/base/inputs/SSN.stories.js
  src/pages/using-spark/components/input.mdx
  storybook-utilities/components/AdditionalInputInfo.js
Labels: status: PR review

#2703 CSS Utility Docs
  html/utilities/_clearfix.scss
  html/utilities/_spacing.scss
  html/utilities/_utilities.scss
  html/utilities/_width.scss
  src/components/CssUtilityTable.js
  src/components/layouts/Layout.js
  src/components/markdown-render/h4.js
  src/data/sass-modifiers.json
  src/data/sass-utilities.json
  src/pages/using-spark/foundations/css-utilities.mdx
Labels: status: DO NOT MERGE, status: PR review

#2694 add in some of the assets from Jane to homepage
  .github/pull_request_template.md
  .gitignore
  package-lock.json
  react/src/components/footer/SprkFooter.js
  react/src/components/masthead/SprkMasthead.js
  react/src/components/masthead/components/SprkMastheadAccordion/SprkMastheadAccordion.js
  react/src/components/masthead/components/SprkMastheadAccordionItem/SprkMastheadAccordionItem.js
  react/src/components/masthead/components/SprkMastheadBigNav/SprkMastheadBigNav.js
  react/src/components/masthead/components/SprkMastheadDropdown/SprkMastheadDropdown.js
  react/src/components/masthead/components/SprkMastheadLittleNav/SprkMastheadLittleNav.js
  react/src/components/masthead/components/SprkMastheadNarrowNav/SprkMastheadNarrowNav.js
  react/src/components/stepper/SprkStepper.stories.js
  src/components/Footer.js
  src/components/layouts/Layout.js
  src/images/components.svg
  src/images/designers.svg
  src/images/developers.svg
  src/images/foundations.svg
  src/images/news-and-updates.svg
  src/images/powerlines.svg
  src/images/utilities.svg
  src/pages/index.js
  src/pages/installing-spark.mdx
  src/pages/using-spark.mdx
  src/pages/using-spark/components/stepper.mdx
  src/pages/using-spark/foundations/sass-variables.mdx
  src/scss/components/_layout.scss
Labels: status: PR review

#2713 Update Footer stories with sister company logos
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
  html/components/footer.stories.js
  react/src/components/footer/SprkFooter.stories.js
  storybook-utilities/getStorybookInstance.js
Labels: status: PR review

#2711 Add angular docs
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
  angular/projects/spark-angular/src/lib/directives/inputs/sprk-button/sprk-button.stories.ts
  html/base/typography.stories.js
  html/components/button.stories.js
  html/components/dropdown.stories.js
  html/components/footer.stories.js
  html/components/masthead.stories.js
  html/utilities/spacing.stories.js
  react/src/components/buttons/SprkButton.stories.js
  react/src/components/dropdown/SprkDropdown.stories.js
  react/src/components/footer/SprkFooter.stories.js
  react/src/components/masthead/SprkMasthead.stories.js
  src/images/installing-spark/angular/style-check.png
  src/pages/index.js
  src/pages/installing-spark/angular.mdx
  src/pages/installing-spark/installing-fonts.mdx
  src/pages/using-spark/components/box.mdx
  src/pages/using-spark/components/button.mdx
  src/pages/using-spark/components/divider.mdx
  src/pages/using-spark/components/dropdown.mdx
  src/pages/using-spark/components/footer.mdx
  src/pages/using-spark/components/input.mdx
  src/pages/using-spark/components/masthead.mdx
  src/pages/using-spark/foundations/space.mdx
  src/pages/using-spark/foundations/typography.mdx
  src/scss/_settings.scss
  src/scss/_spark-theme.scss
Labels: status: PR review

#2712 React installation guides
  src/images/installing-spark/react/button-loaded.png
  src/images/installing-spark/react/react-app.png
  src/images/installing-spark/react/style-check.png
  src/pages/installing-spark/react.mdx
Labels: status: PR review

#2719 version bumps for publish
  angular/projects/spark-angular/package-lock.json
  angular/projects/spark-angular/package.json
  angular/projects/spark-angular/src/environment/environment.ts
  html/.npmignore
  html/package-lock.json
  html/package.json
  package-lock.json
  package.json
  react/.npmignore
  react/package-lock.json
  react/package.json
Labels: status: PR review

#2721 New Doc Site Clean Up
  angular/projects/spark-angular/src/lib/components/inputs/Password.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.stories.ts
  html/base/inputs/Password.stories.js
  html/components/alert.stories.js
  react/src/components/alerts/SprkAlert.stories.js
  src/pages/using-spark/components/alert.mdx
  src/pages/using-spark/components/button.mdx
  src/pages/using-spark/components/dropdown.mdx
  src/pages/using-spark/components/highlight-board.mdx
  src/scss/_spark-theme.scss
Labels: status: PR review

#2731 add export for SprkStepper
  react/src/spark-exports-react.js
Labels: status: PR review

#2681 Add content for Installation Guides
  .eslintignore
  src/components/Header.js
  src/components/markdown-render/inlineCode.js
  src/components/markdown-render/table.js
  src/hooks/use-installing-spark.js
  src/images/installing-spark/angular/angular-spinner.gif
  src/images/installing-spark/html/bundled-js.png
  src/images/installing-spark/html/bundled-spark.png
  src/images/installing-spark/html/folder-structure.png
  src/images/installing-spark/html/green-bg.png
  src/images/installing-spark/html/hello-spark.png
  src/images/installing-spark/html/html-spinner.gif
  src/images/installing-spark/react/button-loaded.png
  src/images/installing-spark/react/react-app.png
  src/images/installing-spark/react/react-spinner.gif
  src/images/installing-spark/react/style-check.png
  src/pages/installing-spark.mdx
  src/pages/installing-spark/angular.mdx
  src/pages/installing-spark/html-add-components.mdx
  src/pages/installing-spark/html-environment-setup.mdx
  src/pages/installing-spark/html-installation.mdx
  src/pages/installing-spark/installing-fonts.mdx
  src/pages/installing-spark/installing-icons.mdx
  src/pages/installing-spark/react.mdx
  src/pages/installing-spark/vanilla-add-components.mdx
  src/pages/installing-spark/vanilla-environment-setup.mdx
  src/pages/installing-spark/vanilla-installation.mdx
  src/scss/_spark-theme.scss
Labels: status: DO NOT MERGE, status: PR review

#2720 Quick NDS Clean up - refactor code snippets line
  src/components/markdown-render/inlineCode.js
Labels: status: PR review

#2734 add list of variants and jump links for inputs
  src/pages/using-spark/components/input.mdx
  src/scss/_spark-theme.scss
Labels: status: PR review

#2741 Remove repeating subnav items
  src/components/Header.js
Labels: status: PR review

#2742 NDS Cleanup - Katie
  src/pages/using-spark/foundations/space.mdx
Labels: status: PR review

#2737 NDS Cleanup
  src/pages/installing-spark.mdx
  src/pages/installing-spark/angular.mdx
  src/pages/installing-spark/html-installation.mdx
  src/pages/using-spark/components/input.mdx
  src/scss/_spark-theme.scss
Labels: status: DO NOT MERGE

#2749 Redirects fix
  _redirects
  netlify.toml
Labels: status: PR review

#2748 Fix mixed inline code+text link
  src/pages/installing-spark/html-installation.mdx
Labels: status: PR review, type: documentation

#2754 adding redirect rules
  netlify.toml
Labels: status: PR review

#2761 SprkBox - React
  html/objects/box.stories.js
  react/src/base/links/SprkLink.js
  react/src/base/links/SprkLink.test.js
  react/src/objects/box/SprkBox.js
  react/src/objects/box/SprkBox.stories.js
  react/src/objects/box/SprkBox.test.js
  react/src/objects/stack/SprkStack.js
  react/src/objects/stack/SprkStack.test.js
  src/pages/using-spark/components/box.mdx
Labels: status: PR review

#2752 Make the cards on the Gatsby pages more flexible
  src/pages/index.js
  src/scss/_settings.scss
  src/scss/components/_layout.scss
  src/scss/objects/_color-swatch-grid.scss
Labels: status: PR review

#2755 Update sprk-table in Angular
  angular/projects/spark-angular/src/lib/components/sprk-table/sprk-table.component.ts
Labels: status: PR review

#2770 Angular Tabs - Arrow Key/Disabled Behavior
  angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.component.ts
  html/components/_tabs.scss
Labels: status: DO NOT MERGE, status: PR review

#2768 Adds ctaIcon input to sprk-card in Angular
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.component.ts
Labels: status: PR review

#2800 update failing test
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.component.spec.ts
Labels: status: PR review

#2769 add type components
  angular/projects/spark-angular/src/lib/directives/sprk-heading/sprk-heading.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/sprk-heading/sprk-heading.directive.ts
  angular/projects/spark-angular/src/lib/directives/sprk-heading/sprk-heading.module.ts
  angular/projects/spark-angular/src/lib/directives/sprk-heading/sprk-heading.stories.ts
  angular/projects/spark-angular/src/lib/directives/sprk-text/sprk-text.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/sprk-text/sprk-text.directive.ts
  angular/projects/spark-angular/src/lib/directives/sprk-text/sprk-text.module.ts
  angular/projects/spark-angular/src/lib/directives/sprk-text/sprk-text.stories.ts
  angular/projects/spark-angular/src/lib/spark-angular.module.ts
  html/base/typography.stories.js
  react/src/base/typography/SprkHeading/SprkHeading.js
  react/src/base/typography/SprkHeading/SprkHeading.stories.js
  react/src/base/typography/SprkHeading/SprkHeading.test.js
  react/src/base/typography/SprkText/SprkText.js
  react/src/base/typography/SprkText/SprkText.stories.js
  react/src/base/typography/SprkText/SprkText.test.js
  react/src/spark-exports-react.js
  src/pages/using-spark/foundations/typography.mdx
  storybook-utilities/components/AdditionalInputInfo.js
Labels: status: PR review

#2803 Hotfix & Doc site grid updates
  react/src/base/inputs/SprkSelectionInput/SprkSelectionInput.js
  react/src/base/inputs/SprkSelectionInput/SprkSelectionInput.test.js
  src/pages/index.js
  src/scss/_settings.scss
  src/scss/components/_layout.scss
  src/scss/objects/_color-swatch-grid.scss
Labels: status: PR review

#2798 [BUG] Awards Component will display a gap between images - Angular
  angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.component.ts
Labels: status: PR review

#2760 Angular Box Component
  angular/.storybook/config.js
  angular/projects/spark-angular/src/lib/directives/sprk-box/sprk-box.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/sprk-box/sprk-box.directive.ts
  angular/projects/spark-angular/src/lib/directives/sprk-box/sprk-box.module.ts
  angular/projects/spark-angular/src/lib/directives/sprk-box/sprk-box.stories.ts
  angular/projects/spark-angular/src/lib/spark-angular.module.ts
  react/src/spark-exports-react.js
  src/pages/using-spark/components/box.mdx
Labels: status: PR review

#2775 change htmlFor to id on input
  react/src/base/inputs/SprkErrorContainer/SprkErrorContainer.js
  react/src/base/inputs/components/SprkInputElement/SprkInputElement.js
Labels: status: PR review

#2804 Spark-react fixes
  react/.npmignore
  react/package.json
  react/rollup.config.js
Labels: status: DO NOT MERGE

#2810 IE 11 Masthead Bug
  html/components/_masthead.scss
Labels: status: PR review

#2797 Fix Wait Modal display bug [IE 11] [3 Frameworks]
  angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.stories.ts
  html/components/_modals.scss
  html/components/modal.stories.js
  react/src/components/modals/SprkModal.js
Labels: status: PO review

#2807 fix masthead SB bugs
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
  html/.storybook/config.js
  html/components/masthead.stories.js
  react/src/components/masthead/SprkMasthead.stories.js
Labels: status: PR review

#2790 Apply keyboard tab navigation only when focus is on tabs
  angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-tabbed-navigation/sprk-tabbed-navigation.component.ts
Labels: status: PR review

#2819 Angular Monetary Updates
  angular/projects/spark-angular/src/lib/components/inputs/Monetary.stories.ts
  angular/projects/spark-angular/src/lib/directives/inputs/formatters/sprk-formatter-monetary/sprk-formatter-monetary.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/inputs/formatters/sprk-formatter-monetary/sprk-formatter-monetary.directive.ts
Labels: js: angular, status: PR review
