Repository sparkdesignsystem/spark-design-system, pull requests merged in 2021-06, with the labels that each got.

#3990 Bug fix: Use type display one wide variable for type display one on wide viewports
  styles/android/spark_design_tokens_font_dimens.xml
  styles/base/_typography.scss
  styles/ios/SparkDesignTokens.swift
  styles/tokens/typography.json
Labels: scope: all pkgs, status: PR review

#3994 Add a containerAdditionalClasses input for tooltip
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.ts
  react/src/components/tooltip/SprkTooltip.js
  react/src/components/tooltip/SprkTooltip.test.js
Labels: Component: Tooltip

#3974 Angular Autocomplete
  angular/projects/spark-angular/src/lib/components/sprk-autocomplete/directives/sprk-autocomplete-input-container/sprk-autocomplete-input-container.directive.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-autocomplete/directives/sprk-autocomplete-input-container/sprk-autocomplete-input-container.directive.ts
  angular/projects/spark-angular/src/lib/components/sprk-autocomplete/directives/sprk-autocomplete-input-container/sprk-autocomplete-input-container.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-autocomplete/directives/sprk-autocomplete-result/sprk-autocomplete-result.directive.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-autocomplete/directives/sprk-autocomplete-result/sprk-autocomplete-result.directive.ts
  angular/projects/spark-angular/src/lib/components/sprk-autocomplete/directives/sprk-autocomplete-result/sprk-autocomplete-result.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-autocomplete/directives/sprk-autocomplete-results/sprk-autocomplete-results.directive.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-autocomplete/directives/sprk-autocomplete-results/sprk-autocomplete-results.directive.ts
  angular/projects/spark-angular/src/lib/components/sprk-autocomplete/directives/sprk-autocomplete-results/sprk-autocomplete-results.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-autocomplete/sprk-autocomplete.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-autocomplete/sprk-autocomplete.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-autocomplete/sprk-autocomplete.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-autocomplete/sprk-autocomplete.stories.ts
  angular/projects/spark-angular/src/lib/spark-angular.module.ts
  angular/projects/spark-angular/src/lib/utilities/keypress/keypress.spec.ts
  angular/projects/spark-angular/src/lib/utilities/keypress/keypress.ts
  angular/projects/spark-angular/src/public-api.ts
  html/utilities/keypress.js
  src/pages/using-spark/components/autocomplete.mdx
  styles/components/_autocomplete.scss
  styles/ios/SparkDesignTokens.swift
  styles/tokens/autocomplete.json
Labels: status: PR review

#3997 Revert Lodash Import
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
Labels: status: PR review

#4001 Autocomplete Click Fix
  angular/projects/spark-angular/src/lib/components/sprk-autocomplete/sprk-autocomplete.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-autocomplete/sprk-autocomplete.component.ts
Labels: status: PR review

#4013 Add some clarifying documentation for masthead
  html/components/masthead.stories.js
Labels: status: PR review, type: documentation
