Repository sparkdesignsystem/spark-design-system, pull requests merged in 2021-01, with the labels that each got.

#3705 Publish December Jan 4th, 2020
  angular/package.json
  angular/projects/spark-angular/package-lock.json
  angular/projects/spark-angular/package.json
  angular/projects/spark-angular/src/environment/environment.ts
  html/components/autocomplete.js
  html/components/autocomplete.stories.js
  html/package-lock.json
  html/package.json
  html/setup-jest.js
  html/spark-exports.js
  html/spark.js
  html/tests/autocomplete.tests.js
  html/tests/generateAriaOwns.tests.js
  html/tests/isElementVisible.tests.js
  html/tests/masthead.tests.js
  html/utilities/generateAriaOwns.js
  html/utilities/isElementVisible.js
  html/utilities/keypress.js
  html/utilities/resetListItems.js
  package.json
  react/package-lock.json
  react/package.json
  src/images/autocomplete/Active Typing@2x.png
  src/images/autocomplete/Addresstwolines.png
  src/images/autocomplete/Default_NotSelected.png
  src/images/autocomplete/Focused_withoutsearch.png
  src/images/autocomplete/No Results Found@2x.png
  src/images/autocomplete/No Search Icon@2x.png
  src/images/autocomplete/NoLabelAbove.png
  src/images/autocomplete/NoMatches.png
  src/images/autocomplete/NoSearchIcon.png
  src/images/autocomplete/Searchacrosscategories.png
  src/images/autocomplete/Selecting Options@2x.png
  src/images/autocomplete/SelectingOption.png
  src/images/autocomplete/Typing.png
  src/images/autocomplete/address_two_lines@2x.png
  src/images/autocomplete/focused_without_search@2x.png
  src/images/autocomplete/no_label@2x.png
  src/images/autocomplete/search_across_categories@2x.png
  src/pages/using-spark/components/autocomplete.mdx
  styles/_spark.scss
  styles/android/spark_design_tokens_colors.xml
  styles/android/spark_design_tokens_dimens.xml
  styles/android/spark_design_tokens_strings.xml
  styles/base/inputs/_input-container.scss
  styles/components/_autocomplete.scss
  styles/ios/SparkDesignTokens.swift
  styles/package-lock.json
  styles/package.json
  styles/tokens/autocomplete.json
  styles/tokens/input.json
Labels: status: DO NOT MERGE

#3731 Accessibility updates for docs site
  package.json
  src/components/ComponentPreview.js
  src/components/Header.js
  src/components/InstallingSparkDocsMenu.js
  src/components/PrinciplesDocsMenu.js
  src/components/UsingSparkDocsMenu.js
  src/components/layouts/Layout.js
  src/components/markdown-render/inlineCode.js
  src/pages/index.js
  src/pages/installing-spark/angular.mdx
  src/pages/installing-spark/html-add-components.mdx
  src/pages/installing-spark/html-environment-setup.mdx
  src/pages/installing-spark/html-installation.mdx
  src/pages/installing-spark/installing-icons.mdx
  src/pages/installing-spark/react.mdx
  src/pages/using-spark/components/accordion.mdx
  src/pages/using-spark/components/alert.mdx
  src/pages/using-spark/components/award.mdx
  src/pages/using-spark/components/box.mdx
  src/pages/using-spark/components/button.mdx
  src/pages/using-spark/components/card.mdx
  src/pages/using-spark/components/centered-column.mdx
  src/pages/using-spark/components/dictionary.mdx
  src/pages/using-spark/components/divider.mdx
  src/pages/using-spark/components/dropdown.mdx
  src/pages/using-spark/components/flag.mdx
  src/pages/using-spark/components/footer.mdx
  src/pages/using-spark/components/highlight-board.mdx
  src/pages/using-spark/components/icon.mdx
  src/pages/using-spark/components/input.mdx
  src/pages/using-spark/components/link.mdx
  src/pages/using-spark/components/list.mdx
  src/pages/using-spark/components/masthead.mdx
  src/pages/using-spark/components/modal.mdx
  src/pages/using-spark/components/pagination.mdx
  src/pages/using-spark/components/promo.mdx
  src/pages/using-spark/components/stack.mdx
  src/pages/using-spark/components/stepper.mdx
  src/pages/using-spark/components/table.mdx
  src/pages/using-spark/components/tabs.mdx
  src/pages/using-spark/components/toggle.mdx
  src/pages/using-spark/components/tooltip.mdx
  src/pages/using-spark/foundations/color-usage.mdx
  src/pages/using-spark/foundations/space.mdx
  src/pages/using-spark/foundations/typography.mdx
  src/scss/_spark-theme.scss
  src/scss/components/_code.scss
  src/scss/main.scss
  src/scss/vendor/_prism.scss
Labels: status: PR review

#3744 Update Huge stories
  html/base/inputs/HugeSelect.stories.js
  html/base/inputs/HugeText.stories.js
  html/base/inputs/Select.stories.js
  html/base/inputs/Text.stories.js
  react/src/base/inputs/DatePicker.stories.js
  react/src/base/inputs/HugeSelect.stories.js
  react/src/base/inputs/HugeText.stories.js
  react/src/base/inputs/Select.stories.js
  react/src/base/inputs/Text.stories.js
  src/pages/using-spark/components/input.mdx
Labels: status: PR review

#3746 Update twitter handle to @SparkDesignSys, update master to main
  README.md
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
  gatsby-config.js
  netlify.toml
  react/README.md
  src/components/Footer.js
  src/pages/index.js
  src/pages/installing-spark.mdx
  src/pages/installing-spark/installing-fonts.mdx
  src/pages/installing-spark/installing-icons.mdx
Labels: status: PR review, type: documentation

#3792 update link underline color
  styles/android/spark_design_tokens_colors.xml
  styles/android/spark_design_tokens_strings.xml
  styles/ios/SparkDesignTokens.swift
  styles/tokens/link.json
Labels: status: PR review

#3797 fixes #3719 update angular huge story text label to match html/react
  angular/projects/spark-angular/src/lib/components/inputs/Text.stories.ts
Labels: status: PR review

#3802 remove sprk-u-Width-100 class from SprkInput component
  react/src/base/inputs/Date.stories.js
  react/src/base/inputs/HelperText.stories.js
  react/src/base/inputs/Monetary.stories.js
  react/src/base/inputs/Password.stories.js
  react/src/base/inputs/Phone.stories.js
  react/src/base/inputs/SSN.stories.js
  react/src/base/inputs/Search.stories.js
  react/src/base/inputs/SprkInput/SprkInput.js
  react/src/base/inputs/SprkInput/SprkInput.test.js
  react/src/base/inputs/Text.stories.js
Labels: status: PR review

#3793 Add new SprkTextarea component to Spark
  react/src/base/inputs/SprkTextarea/SprkTextarea.js
  react/src/base/inputs/SprkTextarea/SprkTextarea.test.js
  react/src/base/inputs/Textarea.stories.js
  react/src/setup.test.js
  react/src/spark-exports-react.js
Labels: status: PR review

#3796 SprkDatePicker
  react/src/base/inputs/DatePicker.stories.js
  react/src/base/inputs/SprkDatePicker/SprkDatePicker.js
  react/src/base/inputs/SprkDatePicker/SprkDatePicker.test.js
  react/src/spark-exports-react.js
Labels: status: PR review

#3821 React SprkFieldError
  react/src/base/inputs/Date.stories.js
  react/src/base/inputs/DatePicker.stories.js
  react/src/base/inputs/HelperText.stories.js
  react/src/base/inputs/Monetary.stories.js
  react/src/base/inputs/Password.stories.js
  react/src/base/inputs/Percentage.stories.js
  react/src/base/inputs/Phone.stories.js
  react/src/base/inputs/SSN.stories.js
  react/src/base/inputs/Search.stories.js
  react/src/base/inputs/Select.stories.js
  react/src/base/inputs/SprkCheckbox.stories.js
  react/src/base/inputs/SprkFieldError/SprkFieldError.js
  react/src/base/inputs/SprkFieldError/SprkFieldError.test.js
  react/src/base/inputs/SprkRadio.stories.js
  react/src/base/inputs/Text.stories.js
  react/src/base/inputs/Textarea.stories.js
  react/src/spark-exports-react.js
Labels: status: PR review

#3784 SprkTextInput aria-describedby
  react/src/base/inputs/SprkTextInput/SprkTextInput.js
  react/src/base/inputs/SprkTextInput/SprkTextInput.test.js
  react/src/base/inputs/components/SprkInputElement/SprkInputElement.js
Labels: status: PR review

#3820 Add New React Select Input
  react/src/base/inputs/Select.stories.js
  react/src/base/inputs/SprkSelect/SprkSelect.js
  react/src/base/inputs/SprkSelect/SprkSelect.test.js
  react/src/spark-exports-react.js
Labels: changes requested, status: PR review
