Repository sparkdesignsystem/spark-design-system, pull requests merged in 2021-03, with the labels that each got.

#3863 Tooltip Width bug
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.ts
  html/components/tooltip.js
  html/tests/tooltip.tests.js
  react/src/components/tooltip/SprkTooltip.js
  react/src/components/tooltip/SprkTooltip.test.js
  styles/components/_tooltip.scss
Labels: status: PR review

#3896 Card API Angular Upgrades
  angular/package.json
  angular/projects/spark-angular/src/lib/components/sprk-card/directives/sprk-card-content/sprk-card-content.directive.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/directives/sprk-card-content/sprk-card-content.directive.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/directives/sprk-card-content/sprk-card-content.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/directives/sprk-card-header/sprk-card-header.directive.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/directives/sprk-card-header/sprk-card-header.directive.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/directives/sprk-card-header/sprk-card-header.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/directives/sprk-card-media/sprk-card-media.directive.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/directives/sprk-card-media/sprk-card-media.directive.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/directives/sprk-card-media/sprk-card-media.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts
  angular/projects/spark-angular/src/lib/spark-angular.module.ts
  angular/projects/spark-angular/src/public-api.ts
  html/components/card.stories.js
  styles/components/_card.scss
Labels: status: PR review

#3916 Add orange and remove yellow and pink from Docs
  src/images/accessibility-chart-1.png
  src/images/accessibility-chart-1@2x.png
  src/images/accessibility-chart-1@3x.png
  src/images/accessibility-chart-2.png
  src/images/accessibility-chart-2@2x.png
  src/images/accessibility-chart-2@3x.png
  src/images/contrast-chart-1-high-res.jpg
  src/images/contrast-chart-2-high-res.jpg
  src/images/do-semantic.png
  src/images/do-semantic@2x.png
  src/images/dont-semantic.png
  src/images/dont-semantic@2x.png
  src/images/orange-box-contrast-key.svg
  src/pages/using-spark/foundations/color-accessibility.mdx
  src/pages/using-spark/foundations/color-codes.mdx
  src/pages/using-spark/foundations/color-usage.mdx
  styles/android/spark_design_tokens_colors.xml
  styles/android/spark_design_tokens_strings.xml
  styles/ios/SparkDesignTokens.swift
  styles/tokens/alert.json
  styles/tokens/color.json
  styles/tokens/input.json
  styles/utilities/_utilities.scss
Labels: scope: all pkgs, status: PR review, type: documentation

#3912 Add React Card Upgrades
  html/components/card.stories.js
  react/src/components/card/SprkCard.js
  react/src/components/card/SprkCard.stories.js
  react/src/components/card/SprkCard.test.js
  react/src/components/card/components/SprkCardHighlightedHeader/SprkCardHighlightedHeader.js
  react/src/components/card/components/SprkCardHighlightedHeader/SprkCardHighlightedHeader.test.js
  react/src/components/card/components/SprkCardTeaser/SprkCardTeaser.js
  react/src/components/card/components/SprkCardTeaser/SprkCardTeaser.test.js
Labels: js: react, status: PR review, type: !BREAKING!

#3899 Give Masthead selector its own style namespace
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-selector/sprk-masthead-selector.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-selector/sprk-masthead-selector.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
  html/components/masthead.stories.js
  react/src/components/masthead/components/SprkMastheadSelector/SprkMastheadSelector.js
  react/src/components/masthead/components/SprkMastheadSelector/SprkMastheadSelector.test.js
  styles/android/spark_design_tokens_colors.xml
  styles/android/spark_design_tokens_dimens.xml
  styles/android/spark_design_tokens_strings.xml
  styles/components/_masthead.scss
  styles/ios/SparkDesignTokens.swift
  styles/tokens/masthead.json
Labels: changes requested, scope: all pkgs

#3923 Add orange color utilities
  styles/utilities/_utilities.scss
Labels: status: PR review

#3922 Add guides and validation messaging page
  gatsby-config.js
  src/components/ContextSubMenu.js
  src/components/Header.js
  src/images/guides/validation-anatomy.png
  src/images/guides/validation-anatomy@2x.png
  src/pages/index.js
  src/pages/using-spark/guides.mdx
  src/pages/using-spark/guides/validation-messaging.mdx
Labels: changes requested, type: documentation

#3921 Add Angular Promo Upgrade
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/directives/sprk-promo-content/sprk-promo-content.directive.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/directives/sprk-promo-content/sprk-promo-content.directive.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/directives/sprk-promo-content/sprk-promo-content.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/directives/sprk-promo-heading/sprk-promo-heading.directive.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/directives/sprk-promo-heading/sprk-promo-heading.directive.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/directives/sprk-promo-heading/sprk-promo-heading.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/directives/sprk-promo-media/sprk-promo-media.directive.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/directives/sprk-promo-media/sprk-promo-media.directive.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/directives/sprk-promo-media/sprk-promo-media.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/directives/sprk-promo-subheading/sprk-promo-subheading.directive.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/directives/sprk-promo-subheading/sprk-promo-subheading.directive.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/directives/sprk-promo-subheading/sprk-promo-subheading.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.stories.ts
  html/components/promo.stories.js
  styles/android/spark_design_tokens_dimens.xml
  styles/android/spark_design_tokens_strings.xml
  styles/components/_promo.scss
  styles/ios/SparkDesignTokens.swift
  styles/tokens/promo.json
Labels: status: PR review, type: !BREAKING!

#3924 Add React Promo Upgrades
  react/src/components/promo/SprkPromo.js
  react/src/components/promo/SprkPromo.stories.js
  react/src/components/promo/SprkPromo.test.js
  styles/objects/_flag.scss
Labels: status: PR review, type: !BREAKING!

#3940 Update Modal Buttons
  angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.stories.ts
  html/components/modal.stories.js
  react/src/components/buttons/SprkButton.js
  react/src/components/modals/ModalFooter.js
  react/src/components/modals/SprkModal.js
  react/src/components/modals/SprkModal.stories.js
Labels: status: PR review

#3919 Update Default Link Color
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-selector/sprk-masthead-selector.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead-selector/sprk-masthead-selector.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
  html/components/masthead.stories.js
  react/src/components/masthead/components/SprkMastheadSelector/SprkMastheadSelector.js
  react/src/components/masthead/components/SprkMastheadSelector/SprkMastheadSelector.test.js
  styles/android/spark_design_tokens_colors.xml
  styles/android/spark_design_tokens_strings.xml
  styles/base/_links.scss
  styles/components/_footer.scss
  styles/components/_masthead.scss
  styles/ios/SparkDesignTokens.swift
  styles/tokens/dropdown.json
  styles/tokens/footer.json
  styles/tokens/link.json
  styles/tokens/masthead.json
Labels: status: PR review

#3942 Card Buttons
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts
  html/components/card.stories.js
  react/src/components/card/SprkCard.stories.js
Labels: status: PR review

#3944 Dropdown Secondary Button
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.module.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
  html/components/dropdown.stories.js
  react/src/components/dropdown/SprkDropdown.js
  react/src/components/dropdown/SprkDropdown.stories.js
Labels: status: PR review
