Repository sparkdesignsystem/spark-design-system, pull requests merged in 2021-08, with the labels that each got.

#4043 Rm updates
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  angular/projects/spark-angular/package.json
  angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.stories.ts
  gatsby-config.js
  html/components/dictionary.stories.js
  html/components/footer.stories.js
  html/components/icons.stories.js
  html/package.json
  package.json
  react/README.md
  react/package.json
  react/src/components/dictionary/SprkDictionary.stories.js
  react/src/components/dictionary/SprkDictionary.test.js
  react/src/components/footer/SprkFooter.stories.js
  react/src/components/icons/SprkIcon.stories.js
  src/components/Footer.js
  src/pages/installing-spark.mdx
  src/pages/using-spark.mdx
  src/pages/using-spark/foundations/design-tokens.mdx
  styles/package.json
Labels: status: PR review

#4039 Flip accordion arrow icon & add additional class for optional top border
  angular/projects/spark-angular/src/lib/components/sprk-accordion-item/sprk-accordion-item.component.ts
  html/components/accordion.stories.js
  html/components/toggle.js
  html/tests/toggle.tests.js
  react/src/components/accordions/components/SprkAccordionItem/SprkAccordionItem.js
  styles/android/spark_design_tokens_strings.xml
  styles/components/_accordions.scss
  styles/tokens/accordion.json
Labels: status: PR review

#4044 update icon position in select
  styles/android/spark_design_tokens_strings.xml
  styles/base/inputs/_select.scss
  styles/tokens/input.json
Labels: status: PR review

#4050 main -> staging (created locally)
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  angular/projects/spark-angular/package.json
  angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.stories.ts
  gatsby-config.js
  html/components/button.stories.js
  html/components/dictionary.stories.js
  html/components/footer.stories.js
  html/components/icons.stories.js
  html/components/spinners.js
  html/package-lock.json
  html/package.json
  html/tests/spinners.tests.js
  package.json
  react/README.md
  react/package.json
  react/src/components/dictionary/SprkDictionary.stories.js
  react/src/components/dictionary/SprkDictionary.test.js
  react/src/components/footer/SprkFooter.stories.js
  react/src/components/icons/SprkIcon.stories.js
  src/components/Footer.js
  src/pages/installing-spark.mdx
  src/pages/using-spark.mdx
  src/pages/using-spark/foundations/design-tokens.mdx
  src/pages/using-spark/foundations/typography.mdx
  styles/package.json
Labels: status: PR review

#4054 Publish Aug 12 - isElementVisible and Footer Logo updates
  angular/projects/spark-angular/package-lock.json
  angular/projects/spark-angular/package.json
  angular/projects/spark-angular/src/environment/environment.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
  angular/projects/spark-angular/src/lib/utilities/isElementVisible/isElementVisible.spec.ts
  angular/projects/spark-angular/src/lib/utilities/isElementVisible/isElementVisible.ts
  html/components/footer.stories.js
  react/src/components/footer/SprkFooter.stories.js
  src/components/layouts/Layout.js
  src/components/site-logo.js
  src/pages/using-spark/components/icon.mdx
  src/pages/using-spark/components/link.mdx
Labels: Main

#4056 add classes
  html/base/inputs/DatePicker.stories.js
  html/base/inputs/Search.stories.js
Labels: status: PR review

#4057 Story consistency (labels, spacing, copy) [All]
  angular/projects/spark-angular/src/lib/components/inputs/sprk-checkbox-group/sprk-checkbox-group.component.spec.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-checkbox.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-date.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-datepicker.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-helpertext.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-huge-input-container/sprk-huge-input-container.component.spec.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-icon-input-container/sprk-icon-input-container.component.spec.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-input-container/sprk-input-container.component.spec.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-monetary.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-password.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-percentage.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-phone.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-radio-group/sprk-radio-group.component.spec.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-radio.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-search.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-select.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-selection-container/sprk-selection-container.component.spec.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-ssn.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-text.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-textarea-container/sprk-textarea-container.component.spec.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-textarea.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-accordion/sprk-accordion.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-autocomplete/sprk-autocomplete.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-award/sprk-award.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-dictionary/sprk-dictionary.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-dropdown/sprk-dropdown.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-flag/sprk-flag.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-footer/sprk-footer.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-highlight-board/sprk-highlight-board.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-masthead/sprk-masthead.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-modal/sprk-modal.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-ordered-list/sprk-list.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-pagination/sprk-pagination.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-promo/sprk-promo.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-stack/sprk-stack.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-table/sprk-table.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-tabs/sprk-tabs.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-toggle/sprk-toggle.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.stories.ts
  angular/projects/spark-angular/src/lib/directives/sprk-box/sprk-box.stories.ts
  angular/projects/spark-angular/src/lib/directives/sprk-button/sprk-button.stories.ts
  angular/projects/spark-angular/src/lib/directives/sprk-centered-column/sprk-centered-column.stories.ts
  angular/projects/spark-angular/src/lib/directives/sprk-divider/sprk-divider.stories.ts
  angular/projects/spark-angular/src/lib/directives/sprk-heading/sprk-heading.stories.ts
  angular/projects/spark-angular/src/lib/directives/sprk-link/sprk-link.stories.ts
  html/base/inputs/Checkbox.stories.js
  html/base/inputs/HelperText.stories.js
  html/base/inputs/Radio.stories.js
  react/src/base/inputs/Date.stories.js
  react/src/base/inputs/HelperText.stories.js
  react/src/base/inputs/SprkHelperText/SprkHelperText.js
  react/src/base/inputs/Text.stories.js
Labels: changes requested

#4045 Typography updates
  html/base/typography.stories.js
  src/components/Header.js
  src/components/TypographyTable.js
  src/images/typography/RocketTypeSpecimenGraphic-01.png
  src/images/typography/RocketTypeSpecimenGraphic-01@2x.png
  src/images/typography/pagetitle_dont1.png
  src/images/typography/pagetitle_dont1@2x.png
  src/images/typography/pagetitle_dont2.png
  src/images/typography/pagetitle_dont2@2x.png
  src/images/typography/pagetitles_do.png
  src/images/typography/pagetitles_do@2x.png
  src/pages/using-spark/foundations/typography.mdx
  styles/android/spark_design_tokens_dimens.xml
  styles/android/spark_design_tokens_font_dimens.xml
  styles/android/spark_design_tokens_strings.xml
  styles/base/_typography.scss
  styles/ios/SparkDesignTokens.swift
  styles/tokens/typography.json
Labels: status: PR review
