Repository sparkdesignsystem/spark-design-system, pull requests merged in 2021-04, with the labels that each got.

#3937 Buttons update
  angular/projects/spark-angular/src/lib/directives/sprk-button/sprk-button.directive.spec.ts
  angular/projects/spark-angular/src/lib/directives/sprk-button/sprk-button.directive.ts
  angular/projects/spark-angular/src/lib/directives/sprk-button/sprk-button.stories.ts
  html/components/button.stories.js
  react/src/components/buttons/SprkButton.js
  react/src/components/buttons/SprkButton.stories.js
  react/src/components/buttons/SprkButton.test.js
  src/pages/using-spark/components/button.mdx
  styles/android/spark_design_tokens_colors.xml
  styles/android/spark_design_tokens_dimens.xml
  styles/android/spark_design_tokens_strings.xml
  styles/components/_buttons.scss
  styles/ios/SparkDesignTokens.swift
  styles/tokens/button.json
Labels: changes requested, type: !BREAKING!

#3939 Input colors
  html/base/inputs/Checkbox.stories.js
  html/components/autocomplete.stories.js
  html/components/tooltip.stories.js
  styles/android/spark_design_tokens_colors.xml
  styles/android/spark_design_tokens_dimens.xml
  styles/android/spark_design_tokens_strings.xml
  styles/base/inputs/_checkbox.scss
  styles/base/inputs/_input-container.scss
  styles/base/inputs/_labels.scss
  styles/base/inputs/_radio.scss
  styles/base/inputs/_select.scss
  styles/base/inputs/_text-input.scss
  styles/base/inputs/_textarea.scss
  styles/components/_autocomplete.scss
  styles/components/_dictionary.scss
  styles/ios/SparkDesignTokens.swift
  styles/tokens/autocomplete.json
  styles/tokens/color.json
  styles/tokens/dictionary.json
  styles/tokens/input.json
Labels: status: PR review

#3955 Remove Angular Card Legacy and Update component to use single ng-content
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts
Labels: type: !BREAKING!

#3957 Angular Tooltip Code Coverage
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.spec.ts
Labels: status: PR review

#3959 Use idString when possible
  angular/projects/spark-angular/src/lib/components/inputs/HelperText.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/SSN.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Search.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Select.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/Textarea.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-checkbox-item/sprk-checkbox.stories.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-input-container/sprk-input-container.component.spec.ts
  angular/projects/spark-angular/src/lib/components/inputs/sprk-radio-item/sprk-radio.stories.ts
Labels: status: PR review

#3965 React Disabled Password bug
  react/src/base/inputs/SprkRevealInput/SprkRevealInput.js
Labels: status: PR review

#3962 Text input border with box-shadow combo
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.stories.ts
  html/base/inputs/Radio.stories.js
  html/components/autocomplete.stories.js
  html/components/tooltip.stories.js
  react/src/base/inputs/SprkRadio.stories.js
  react/src/components/tooltip/SprkTooltip.stories.js
  styles/android/spark_design_tokens_colors.xml
  styles/android/spark_design_tokens_dimens.xml
  styles/android/spark_design_tokens_strings.xml
  styles/base/inputs/_checkbox.scss
  styles/base/inputs/_input-container.scss
  styles/base/inputs/_labels.scss
  styles/base/inputs/_radio.scss
  styles/base/inputs/_select.scss
  styles/base/inputs/_text-input.scss
  styles/base/inputs/_textarea.scss
  styles/components/_autocomplete.scss
  styles/ios/SparkDesignTokens.swift
  styles/tokens/autocomplete.json
  styles/tokens/color.json
  styles/tokens/input.json
Labels: status: PR review

#3971 Angular Icon aria-hidden
  angular/projects/spark-angular/src/lib/components/sprk-alert/sprk-alert.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-card/sprk-card.stories.ts
  angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.component.spec.ts
  angular/projects/spark-angular/src/lib/components/sprk-icon/sprk-icon.component.ts
  angular/projects/spark-angular/src/lib/components/sprk-tooltip/sprk-tooltip.component.ts
Labels: status: PR review
